### ISSUE TITLE
Collection helpers

### ISSUE THREAD

**Issue by jbaxleyiii** [apollostack/apollo-client#1]
One of the things I have missed most when using redux as my client side data store, has been the lack of query / sort / filter / etc operations that we had with Mongo.Collection.

Since part of the GQL spec will require id, could we replicate the Mongo collection methods for easy manipulation / fetching of data from the store to use in the UI?

**Comment by stubailo** [comment]
Is lodash not enough? Like `_.findWhere(items, { stuff: "value"})`. That isn't much more complex than `items.find({stuff: "value"})` right?

**Comment by jbaxleyiii** [comment]
@stubailo I was thinking more around nested keys. But after playing around with lodash more, its all I need! Thanks for the advice!

**Comment by stubailo** [comment]
Cool, so hopefully I can get an initial version of this client going this week, and then we can see if it meets your needs and we can collaborate, does that sound good?
