### ISSUE TITLE
apollo-client crashes in brand new create-react-app project

### ISSUE THREAD

**Issue by scf4** [apollostack/apollo-client#1002]
```
Failed to compile.

Error in ./src/~/lodash/_baseClone.js

  110:22  warning  Expected '===' and instead saw '=='  eqeqeq
  110:40  warning  Expected '===' and instead saw '=='  eqeqeq
  115:13  warning  Expected '===' and instead saw '=='  eqeqeq
  115:33  warning  Expected '===' and instead saw '=='  eqeqeq
  130:21  warning  Missing '()' invoking a constructor  new-parens
  139:17  error    'keysIn' is not defined              no-undef

✖ 6 problems (1 error, 5 warnings)
```

**Comment by stubailo** [comment]
I'm confused - this looks like a lint error _inside lodash_, and doesn't have anything to do with Apollo Client. Can you use `lodash` inside CRA? Also, shouldn't there be a `node_modules` in the path somewhere? Why did this stuff end up in `./src`?

**Comment by scf4** [comment]
It's in `./src/node_modules/lodash...`. Seems I ran `yarn` in the `src` dir instead. 

The error only appeared when including Apollo. My bad!
