### ISSUE TITLE
Should fail with an error if object has no id, but dataIdFromObject is provided

### ISSUE THREAD

**Issue by ghirlekar** [apollostack/apollo-client#1005]
I am using apollo-client: 0.5.10 and am generally very happy with it, but I ran into an issue today.

I use UUIDs and pass in `dataIdFromObject: o => o.id` to ApolloClient.

My schema is such
```
type Order {
    id: ID
    name: String!
    customer: Customer!
  }
type Customer {
    id: ID
    name: String!
  }
```

I have two components with a query attached to each.
List component -> Does not request customer id.
Detail component -> Requests customer id.

If I neglect to request the id of the customer, all is fine. Apollo identifies the customer object by it's path from the order object. If the customer id is requested, it identifies using it's id.

However, if I first load the detail view component and then the list view component, Apollo client fails with a `reducerError: { }`.

I realize there is no way for Apollo client to realize that the previous `b1b90e60-bb7d-11e6-bfe4-c729b3627509` is the same as this `'$7d2b5960-bb8b-11e6-bfe4-c729b3627509.customer`, but can it throw an error to complain about the lack of an id on the customer object? It threw no errors to the console and the object wrapped with the query also had no error prop on data. The only indication was with redux devtools.

**Comment by stubailo** [comment]
> but can it throw an error to complain about the lack of an id on the customer object

Unfortunately because not all objects in your schema will have an ID, this isn't easy - we can't just error when there's no ID in general. But we have some ideas for dev tools and lint plugins that can help catch this kind of bug.

**Comment by helfer** [comment]
Yeah, unfortunately there's not much we can do at the moment. See also #380

**Comment by ghirlekar** [comment]
Great. Thanks for your help and sorry for the trouble. #380 is far better explained and I should have researched more before opening an issue.
