### ISSUE TITLE
 Use apolloclient on server

### ISSUE THREAD

**Issue by julian-rare** [apollostack/apollo-client#1006]
I'm building a isomorphic app that does server side rendering, wen I try to use the apollo client on the server side like:

```
import ApolloClient from 'apollo-client';
import {meteorClientConfig} from 'meteor/apollo';

const client = new ApolloClient(meteorClientConfig());

```
It fails, server command line log shows that meteorClientConfig is not a function.

Wen I put a condition

```
var client = {};
if(Meteor.isClient){
    client = new ApolloClient(meteorClientConfig());
    console.log(client);
}

```
It works but that means the server cant access the db, only the browser.

**Comment by stubailo** [comment]
This is an issue with the Meteor integration - as you said, the problem is that `meteorClientConfig` is not available on the server, because it is for the client. Please open an issue here: https://github.com/apollostack/meteor-integration
