### ISSUE TITLE
Switch to TypeScript 2.1 and use object spread instead of assign

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#1011]
Finally! https://blogs.msdn.microsoft.com/typescript/2016/12/07/announcing-typescript-2-1/

**Comment by helfer** [comment]
I just updated to TS 2.1, so someone could start working on this! Any volunteers?

**Comment by johnthepink** [comment]
I can handle!

**Comment by helfer** [comment]
This is done now. 🙂

**Comment by intellix** [comment]
TS 2.1 isn't supported by Angular2 yet. I guess we have to wait for support to land there before we can use it :)

**Comment by stubailo** [comment]
You can still use the new version of AC though!
