### ISSUE TITLE
Stop queries before reset the store

### ISSUE THREAD

**Issue by flodlc** [apollostack/apollo-client#1012]
Hello, 

I'm trying to reset the store with client.resetStore() but all my queries are refetched.
Is it possible to stop all queries before resetting the store, or just empty the store without refetching all queries ?
I'm using apollo with react and react-router.

Thanks !

**Comment by helfer** [comment]
@flodlc why do you want to stop all queries? Are you not displaying anything in the UI any more? If you unmount the components which had queries, then the corresponding queries should automatically be stopped.

**Comment by flodlc** [comment]
You are right, but it looks like stopped queries of unmounted components are also refetched.
I've seen the issue #960 and it seems to be the same issue.
Do you plan to change this behaviour ?

**Comment by helfer** [comment]
@flodlc alright, in that case I will close this issue as a duplicate. As you can see PR #960 to fix this is already under way.
