### ISSUE TITLE
Can't resolve 'lodash/xxx'

### ISSUE THREAD

**Issue by Hongbo-Miao** [apollostack/apollo-client#1030]
My apollo-client version is 0.5.18. I tried to add Apollo in latest [angular/universal-starter](https://github.com/angular/universal-starter).

I got the error below when I try to start my app. The full log is [here](http://paste.ofcode.org/35BbdWHngB5PFqK8Se6TNef). Below are part of the logs.

```
    ERROR in ./~/apollo-client/store.js
    Module not found: Error: Can't resolve 'lodash/assign' in '/my-project/node_modules/apollo-client'
     @ ./~/apollo-client/store.js 7:13-37
     @ ./~/apollo-client/index.js
     @ ./~/apollo-client-rxjs/build/src/RxApolloClient.js
     @ ./~/apollo-client-rxjs/build/src/index.js
     @ ./~/angular2-apollo/build/src/Angular2Apollo.js
     @ ./~/angular2-apollo/build/src/index.js
     @ ./src/+app/+about/about.component.ts
     @ ./src/+app/+about/about.module.ts
     @ ./src/+app/app.module.ts
     @ ./src/browser.module.ts
     @ ./src/client.ts

    ERROR in ./~/apollo-client/ApolloClient.js
    Module not found: Error: Can't resolve 'lodash/assign' in '/my-project/node_modules/apollo-client'
     @ ./~/apollo-client/ApolloClient.js 4:13-37
     @ ./~/apollo-client/index.js
     @ ./~/apollo-client-rxjs/build/src/RxApolloClient.js
     @ ./~/apollo-client-rxjs/build/src/index.js
     @ ./~/angular2-apollo/build/src/Angular2Apollo.js
     @ ./~/angular2-apollo/build/src/index.js
     @ ./src/+app/+about/about.component.ts
     @ ./src/+app/+about/about.module.ts
     @ ./src/+app/app.module.ts
     @ ./src/browser.module.ts
     @ ./src/client.ts
```

**Comment by helfer** [comment]
@Hongbo-Miao I'm not sure what's happening, because lodash is clearly a dependency in package.json. Did you try removing node_modules and reinstalling everything?

**Comment by Hongbo-Miao** [comment]
@helfer Yeah, I tried, it does not help.

However, after adding lodash explicitly (`yarn add lodash`) in the app, it won't show the error.

I will keep going first. Feel free to close if need.

**Comment by helfer** [comment]
@Hongbo-Miao in that case I think it's probably not an Apollo Client issue...

**Comment by Hongbo-Miao** [comment]
@helfer oh because the [old demo](https://github.com/kamilkisiela/universal-starter-apollo) does not need add lodash explicitly. Same code for Apollo part.

Weird, I will close it now.

**Comment by intellix** [comment]
I'm actually getting this now with my angular-cli project. It doesn't seem to happen in angular2-githunt but happens in my project. I can't tell at all what's different but I'm receiving about 20 errors or so.
