### ISSUE TITLE
Error: Can't find field xx on object xx

### ISSUE THREAD

**Issue by nicolaslopezj** [apollostack/apollo-client#1031]
I'm getting this error a lot, on different Types. I can't find any pattern for this error

For example

```
Uncaught Error: Network error: Can't find field investmentContract({"userId":"LeJemoi6P6LGHskET","amount":2000000,"benefits":[{"identifier":"cancha","count":2}]}) on object (Event:xe9mgZ59nD75F5f9N)
```

When I run this is the console

```js
apollo.store.getState().apollo.data['Event:xe9mgZ59nD75F5f9N']['investmentContract({"userId":"LeJemoi6P6LGHskET","amount":2000000,"benefits":[{"identifier":"cancha","count":2}]})']
```

I get ```undefined```

Other example:

```
Uncaught Error: Network error: Can't find field searchEvent({"filter":"m"}) on object (ROOT_QUERY)
```

**Comment by nicolaslopezj** [comment]
The error message is always for the previous query variables

**Comment by helfer** [comment]
@nicolaslopezj what events do you see when you look at the redux devtools? It may help to have a somewhat minimal example that runs only a single query and then changes the variables.

**Comment by nicolaslopezj** [comment]
![image](https://cloud.githubusercontent.com/assets/2042567/21128129/33a7e960-c0d7-11e6-9467-a073b5e2a888.png)

**Comment by nicolaslopezj** [comment]
When the first query fails, it doesn't make any more queries (in the same HoC).

**Comment by nicolaslopezj** [comment]
This error is only present in ```apollo-client@0.5.19```

**Comment by helfer** [comment]
@nicolaslopezj you mean it works fine on 0.5.18?

**Comment by nicolaslopezj** [comment]
Yes it does

**Comment by rovansteen** [comment]
I can confirm that I'm also having this issue since upgrading to `apollo-client@0.5.19`. No problems in `0.5.18`.

**Comment by helfer** [comment]
@rovansteen are you also seeing it a lot? Any pattern that could help identifying the issue?

**Comment by rovansteen** [comment]
I noticed it on a query that's invoked when the user types in a search field (it's throttled for a short period), so there were multiple queries in a short amount of time. I didn't notice a pattern apart from that it occurred after a few queries. I'll try and investigate it further tomorrow.

**Comment by helfer** [comment]
@rovansteen so no resetStore involved at all? In that case I'm very surprised that you don't have the same issue with 0.5.18 (are you sure about that?).

**Comment by nicolaslopezj** [comment]
no resetStore for me. The error appears very very much, is unusable

**Comment by rovansteen** [comment]
@helfer nope I'm not using `resetStore` at all.

**Comment by helfer** [comment]
@nicolaslopezj @rovansteen okay, and you're 100% sure that this bug was not present in 0.5.18? I'm surprised that this is not affecting more people if it's as common as you say it is.

Could one of you provide me with a minimal reproduction so I can get to the bottom of this?

**Comment by rovansteen** [comment]
Could there be something in `apollo-client@0.5.20` that fixes this problem? I tried to reproduce this issue in the latest version but failed to do so.

**Comment by nicolaslopezj** [comment]
Seems fixed in ```apollo-client@0.5.20```

**Comment by helfer** [comment]
@nicolaslopezj @rovansteen as far as I can tell there is no commit related to this in 0.5.20, but I'm glad it works for you now!

**Comment by nicolaslopezj** [comment]
Magic...

**Comment by nicolaslopezj** [comment]
I'm getting this error again. In version ```0.5.20``` and on... I don't know what could be the problem. I think something with the store

**Comment by chitswe** [comment]
I am new to apollo-client. I also occur the same problem here. I am implementing search box for my project. I watch onChange event on text box and call `refetch` with new search term. The above error occur when user type search fast (when I call `refetch` again before I got previous query result). Is it recommended to implement search box query like that?. If I am wrong, please guide me. 

Schema
`
type Employee{
        id:Int!
        Name:String
    }
 type Query{
        employee(search:String):[Employee]
    }`

Error is as follow.

`
store.js:13 Caught an exception! Error: Network error: Can't find field employee({"search":"Th"}) on object (ROOT_QUERY) {
  "employee({\"search\":\"\"})": [
    {
      "type": "id",
      "id": "Employee1",
      "generated": false
    },
    {
      "type": "id",
      "id": "Employee2",
      "generated": false
    },
    {
      "type": "id",
      "id": "Employee3",
      "generated": false
    }],
"employee({\"search\":\"T\"})": [
    {
      "type": "id",
      "id": "Employee3",
      "generated": false
    },
    {
      "type": "id",
      "id": "Employee4",
      "generated": false
    },
    {
      "type": "id",
      "id": "Employee5",
      "generated": false
    }]
}
Perhaps you want to use the `returnPartialData` option?
`

I also set `returnPartialData` options to `false`.

Thanks

**Comment by dcmagine** [comment]
@nicolaslopezj I got this too and in my case there was something with the store. My initial state contained queries (from server-side rendering) which I think is wrong judging from [this check](https://github.com/apollostack/apollo-client/blob/master/src/store.ts#L161):
```javascript
  if ( initialState && initialState[reduxRootKey] && initialState[reduxRootKey]['queries']) {
    throw new Error('Apollo initial state may not contain queries, only data');
  }
```
Unfortunately that check never gets hit in v0.5.24 so it wasn't that obvious.

## Solution
In my case it was to remove `queries` and `mutations` when bootstrapping the client-side code:
```
if (state['apollo']) {
  state['apollo'].queries = {};
  state['apollo'].mutations = {};
}
```

## Details
I have a button in the UI that triggers a query which gets `queryId` 1 (because `queryId` [gets reset client-side](https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L158)). But since there is already a query with `queryId` 1 (from server-side rendering) the old query is fetched from `queries` and that query has `loading` set to `false` which causes `apollo-client` to try to resolve the result of the query solely from the store and that's what caused my `Network error: Can't find field xx on object xx` (which has nothing to do with the network).

[This check](https://github.com/apollostack/apollo-client/blob/master/src/queries/store.ts#L66) could also have saved me some trouble. It gets hit but it's also swallowed:
```javascript
    if (previousQuery && previousQuery.queryString !== action.queryString) {
      // XXX we're throwing an error here to catch bugs where a query gets overwritten by a new one.
      // we should implement a separate action for refetching so that QUERY_INIT may never overwrite
      // an existing query (see also: https://github.com/apollostack/apollo-client/issues/732)
      throw new Error('Internal Error: may not update existing query string in store');
    }
```

**Comment by helfer** [comment]
@chitswe and @dcmagine, it sounds like you're describing different issues.

@chitswe This sounds like a race condition, and it seems to be triggered when set variables changes the query before the first result has returned. Can you open a separate issue detailing that? Then we can tag it as a bug, get a failing test and fix it.

@dcmagine Are you saying that the check for `initialState` not to contain any queries is never hit, and you actually managed to provide an initial state with queries in it? If you didn't do that by just providing your own redux store, then please file a separate issue so we can track it and fix it.

Thanks to both of you in advance!

**Comment by helfer** [comment]
@chitswe thanks, I saw that later! 🙂

**Comment by ffxsam** [comment]
Still having this problem with `apollo-client@2.2.0`. My query is pretty straightforward:

```js
      query: gql`
        {
          tracks {
            items {
              id
              name
              key
            }
          }
        }
      `,
```

And I'm getting `Error sending the query 'tracks' Error: Can't find field tracks on object (ROOT_QUERY) undefined.`
