### ISSUE TITLE
Question : is it depending on Apollo-server ?

### ISSUE THREAD

**Issue by AhmadEl-Banna** [apollostack/apollo-client#105]
is it depending on Apollo-server ? or i can use it with watchQuery with any custom GraphQl servers

**Comment by johnthepink** [comment]
You will be able to use it with any GraphQL server. Just create a network interface and pass it to the client. 

See here: http://docs.apollostack.com/apollo-client/#createNetworkInterface

**Comment by stubailo** [comment]
Note that reactivity is not yet implemented, but we will have manual query refetching and polling pretty soon.
