### ISSUE TITLE
Update reducer is not firing

### ISSUE THREAD

**Issue by 0x6e6562** [apollostack/apollo-client#1052]
I'm trying to get an [update reducer](http://dev.apollodata.com/react/cache-updates.html#resultReducers) to fire upon a successful mutation. However the reducer does not appear to get triggered, even though the round trip to the server was successful.

This is how I configured the reducer:

```js
const ReducerTestWithData = compose(
  graphql(UpdateValueMutation, {
    props: ({ mutate }) => ({
      updateValue: (id, value) => mutate({ variables: {id, value} })
    }),
    options: (ownProps) => ({
      reducer: (prev, action) => {
        console.log("Reducer fired");
        return prev;
      }
    }),
  }),
  connect(
    (state, ownProps) => ({}),
    (dispatch, ownProps) => ({
      dispatch,
    }),
  ),
)(ReducerTest);
```

I'm wondering if there's any extra configuration (for example when setting up the store) that I've missed, or is maybe the `options` stanza wrong?

I've stripped the example down to a bare bones runnable example (see below). In this example, the update is successful, but the reducer does not fire:

```js
import React, { Component, PropTypes } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  TouchableOpacity
} from 'react-native';

import { createStore, combineReducers, applyMiddleware} from 'redux';
import ApolloClient, { createNetworkInterface } from 'apollo-client';
import { ApolloProvider, graphql, compose } from 'react-apollo';
import { connect } from 'react-redux';
import gql from 'graphql-tag';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

class ReducerTest extends Component {

  constructor(props) {
    super(props);
    this.updateValue = this.updateValue.bind(this);
  }

  updateValue() {
    this.props.updateValue(
      "101",
      "some_value"
    ).then(({ data }) => {
      if (!data.errors) {

        let { id, value } = data.updateValue;
        console.log("Successfully updated value (" + value + ") for id (" + id +")");

      } else {
        console.log("Application error: " + error);
      }
    }).catch((error) => {
      console.log("Server error: " + error);
    });
  }

  render() {
    return (
      <View style={{alignItems: 'center', justifyContent: 'center', flex: 1}}>
        <TouchableOpacity onPress={this.updateValue}>
          <Text>UPDATE VALUE</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

ReducerTest.propTypes = {
  updateValue: PropTypes.func.isRequired,
};

const UpdateValueMutation = gql`
  mutation updateValue($id: String!, $value: String!) {
    updateValue(id: $id, value: $value) {
      id
      value
    }
  }
`;

const ReducerTestWithData = compose(
  graphql(UpdateValueMutation, {
    props: ({ mutate }) => ({
      updateValue: (id, value) => mutate({ variables: {id, value} })
    }),
    options: (ownProps) => ({
      reducer: (prev, action) => {
        console.log("Reducer fired");
        return prev;
      }
    }),
  }),
  connect(
    (state, ownProps) => ({}),
    (dispatch, ownProps) => ({
      dispatch,
    }),
  ),
)(ReducerTest);

class ReducerTestContainer extends Component {

  constructor(props) {
    super(props);
    const networkInterface = createNetworkInterface({ uri: 'http://localhost:4000/api' });

    this.client = new ApolloClient({
      networkInterface,
      dataIdFromObject: (result) => {
        if (result.id && result.__typename) {
          return result.__typename + result.id;
        }
        return null;
      },
    });

    this.store = createStore(
      combineReducers({
        apollo: this.client.reducer(),
      }),
      compose(
        applyMiddleware(this.client.middleware()),
      )
    );
  }

  render() {
    return (
      <ApolloProvider store={this.store} client={this.client}>
        <ReducerTestWithData/>
      </ApolloProvider>
    );
  }
}

AppRegistry.registerComponent('reducer_test', () => ReducerTestContainer);

```

**Comment by helfer** [comment]
@0x6e6562 It looks like maybe you want to use `updateQueries` in your case. Reducers are used to update a query's result based on the results of other queries, so they don't run when the query that they're defined on returns, only when other queries return. If you want to update the store directly from the mutation, you should use `updateQueries`, or use the `mutate` property on the observable query and then define `updateQuery`, which will affect just that one query.

Does that make sense? Do you have a suggestion for how we could improve the docs to make this clear?

**Comment by 0x6e6562** [comment]
Hey @helfer  - many thanks for the heads up.

Do you have an example of how to define `updateQuery` in conjunction with the `mutate` property?

In the meantime, I'll port my example to use `updateQueries` and report back on how that went.

Regarding your documentation question: The way I read the docs is that `updateQueries` is just a special case of an update reducer. Furthermore, the impression arose with me that the reducer is a generic way to propagate arbitrary data changes back into the Apollo store. It might the case that I just assumed this behavior, which was an incorrect assumption.

Potentially the way to clarify this in the docs is to make a clearer distinction between handling another query returning versus trying to get a mutation to get reflected in the local Apollo graph?

**Comment by 0x6e6562** [comment]
I've updated this example to use `updateQueries`.

In order to do this, I assumed that there must also be a query to update in the first place (which didn't exist in the first version of the example - that only contained a single mutation). Please excuse the terrible styling if you are trying to run this.

So I've added a component and bound it to a query  - calling the update mutation will hopefully convince Apollo to update it's local store.

However, the `updateQueries` still does not appear to fire - have I misunderstood something?

```js
import React, { Component, PropTypes } from 'react';
import {
  ActivityIndicator,
  AppRegistry,
  StyleSheet,
  Text,
  View,
  ListView,
  TouchableOpacity
} from 'react-native';

import { createStore, combineReducers, applyMiddleware} from 'redux';
import ApolloClient, { createNetworkInterface } from 'apollo-client';
import { ApolloProvider, graphql, compose } from 'react-apollo';
import { connect } from 'react-redux';
import gql from 'graphql-tag';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

class ValueList extends Component {
  constructor(props){
    super(props);

    var ds = new ListView.DataSource({
      rowHasChanged: (r1, r2) => r1.id !== r2.id
    });
    this.state = {
      dataSource: ds.cloneWithRows([]),
    };
  }

  componentWillReceiveProps(nextProps) {
    const { loading, values } = nextProps;
    if (!loading) {
      const { dataSource } = this.state;
      this.setState({
        dataSource: dataSource.cloneWithRows(values),
      });
    }
  }

  render() {

    const { loading, values } = this.props;

    if (loading) {
      return (
        <View style={styles.container} >
          <ActivityIndicator />
        </View>
      );
    }

    return (
      <ListView
        enableEmptySections
        dataSource={this.state.dataSource}
        renderRow={this._renderItem}
        style={styles.listView}
        initialListSize={3}
        automaticallyAdjustContentInsets={false}
      />
    );
  }

  _renderItem = (item) => <Text>{item.value}</Text>
}

const ValueQuery = gql`
  query Value {
    values {
      id
      value
      __typename
    }
  }
`;


const ValueListWithData = graphql(ValueQuery, {
  props: ({ data: { loading, values} }) => ({
    loading, values
  }),
})(ValueList);

class ReducerTest extends Component {

  constructor(props) {
    super(props);
    this.updateValue = this.updateValue.bind(this);
  }

  updateValue() {
    this.props.updateValue(
      "3",
      "baz"
    ).then(({ data }) => {
      if (!data.errors) {

        let { id, value } = data.updateValue;
        console.log("Successfully updated value (" + value + ") for id (" + id +")");

      } else {
        console.log("Application error: " + error);
      }
    }).catch((error) => {
      console.log("Server error: " + error);
    });
  }

  render() {
    return (
      <View style={{alignItems: 'center', justifyContent: 'center', flex: 1}}>
        <View style={{height: 100}}>
          <ValueListWithData/>
        </View>
        <TouchableOpacity onPress={this.updateValue}>
          <Text>UPDATE VALUE</Text>
        </TouchableOpacity>
      </View>
    );
  }
}

ReducerTest.propTypes = {
  updateValue: PropTypes.func.isRequired,
};

const UpdateValueMutation = gql`
  mutation updateValue($id: String!, $value: String!) {
    updateValue(id: $id, value: $value) {
      id
      value
    }
  }
`;

const ReducerTestWithData = compose(
  graphql(UpdateValueMutation, {
    props: ({ mutate }) => ({
      updateValue: (id, value) => mutate({ variables: {id, value} })
    }),
    updateQueries: {
      Value: (prev, { mutationResult }) => {
        console.log("updateQueries fired");
        const newValue = mutationResult.data.updateValue;
        return update(prev, {
          values: {
            $set: newValue,
          },
        });
      },
    },
  }),
  connect(
    (state, ownProps) => ({}),
    (dispatch, ownProps) => ({
      dispatch,
    }),
  ),
)(ReducerTest);

class ReducerTestContainer extends Component {

  constructor(props) {
    super(props);
    const networkInterface = createNetworkInterface({ uri: 'http://localhost:4000/api' });

    this.client = new ApolloClient({
      networkInterface,
      dataIdFromObject: (result) => {
        if (result.id && result.__typename) {
          return result.__typename + result.id;
        }
        return null;
      },
    });

    this.store = createStore(
      combineReducers({
        apollo: this.client.reducer(),
      }),
      compose(
        applyMiddleware(this.client.middleware()),
      )
    );
  }

  render() {
    return (
      <ApolloProvider store={this.store} client={this.client}>
        <ReducerTestWithData/>
      </ApolloProvider>
    );
  }
}

AppRegistry.registerComponent('reducer_test', () => ReducerTestContainer);
```

**Comment by odero** [comment]
Having the same problem as well. I just updated my apollo-client to 0.5.23 and now it's not working. Seems it was working well up until v0.5.21. However the update reducer is not firing on 0.5.22 and 0.5.23.

**Comment by 0x6e6562** [comment]
@odero I originally came across the issue using 0.5.6. When I made a stripped down version to isolate the issue, I used both 0.5.6 (to remain consistent to the original issue) and then uprev'ed to 0.5.21, to see if there was a difference. However, I have not seen any differing behavior across the versions. So I'm thinking that it is more likely my setup is bogus than a regression in the library.

BTW, I just checked the release tags on `apollostack/apollo-client` and the latest I saw was 0.5.21 - am I missing something here?

**Comment by odero** [comment]
@0x6e6562 Now that's interesting. Because the latest npm version is in fact 0.5.23 https://www.npmjs.com/package/apollo-client

**Comment by helfer** [comment]
@0x6e6562 I forgot to push the latest tags. It should be consistent now.

**Comment by 0x6e6562** [comment]
@helfer OK, cool. I've updated to 0.5.23 but I am still seeing the same behavior as before. That said, I'm still assuming that this is a bug in my code rather than a regression in the library.

**Comment by 0x6e6562** [comment]
@helfer Having re-read what [you said previously](https://github.com/apollostack/apollo-client/issues/1052#issuecomment-267731046), I've put the reducer on a different query. As you suggested, this reducer will fire. My misunderstanding came from the fact that I expected the current reducer to fire and hence I thought the mechanism wasn't. So basically the only thing that was broken was my understanding.

**Comment by 0x6e6562** [comment]
@helfer Is it possible to update certain fragments of a previous query result?

Taking the [example from the docs](http://dev.apollodata.com/react/cache-updates.html#updateQueries):

```graphql
 query Comment($repoName: String!) {
  currentUser {
    login
    html_url
  }

  entry(repoFullName: $repoName) {
    id
    postedBy {
      login
      html_url
    }
    createdAt
    comments {
      postedBy {
        login
        html_url
      }
      createdAt
      content
    }
    repository {
      full_name
      html_url
      description
      open_issues_count
      stargazers_count
    }
  }
}
```

Let's say a mutation updates one of the `comments` nodes, is there a reducer syntax to update the store just to update this part of the graph?

Something like:

```js
return update(prev, {
  let comment = action.result.data.updateComment;
  comments(id: comment.id): {
    content: {
      $set: comment.content,
    }
  },
});
```

Or is this just asking for trouble?

**Comment by luckyyang** [comment]
tested at version `2.5.24`, will not trigger the updateQueries

**Comment by helfer** [comment]
@0x6e6562 For updating just a specific node (and not inserting to or removing from a list) I would recommend `dataIdFromObject` (I'd recommend using that instead of `updateQueries` or `reducer` whenever you can). If the updated node has the same global id, then Apollo Client will update that node in the cache, and all queries involving that node will be updated. 

Since the original question has been solved, I'll close this issue. If there's an actual issue, feel free to open a new thread.

**Comment by luckyyang** [comment]
I am not just updating a specific node, my case is mutate then not trigger the updateQueries. If I am not wrong I think use `updateQueries` with `mutate` is the right way as you recommended @helfer

**Comment by luckyyang** [comment]
same code will trigger `updateQueries` at version `2.5.20`(weird that not update node and I will check ), not at version `2.5.24`

**Comment by 0x6e6562** [comment]
@helfer I completely agree and was just about to close this myself, because this isn't really an bug or problem with the apollo client. After having looked into this deeper, what turns out that:

* My understanding of the mechanics of the `updateQueries` and `reducer` were limited
* In the app I had integrated this into I had some questionable usage of redux which just clouded the issue.

After looking at the state of the store in the debugger, I can actually see that the `dataIdFromObject` mechanism is actually causing the store to take on the updates automatically. So I my case, this is all I need - I had just build my app in such a convoluted way that I couldn't see this.

Many thanks for your help, very much appreciated.

**Comment by 0x6e6562** [comment]
@luckyyang Because this thread is slightly off-topic, might it be an idea to isolate a cut down version to reproduce the issue you are experiencing and then open a new issue for this?

**Comment by luckyyang** [comment]
@0x6e6562 sure. I will, thanks

**Comment by luckyyang** [comment]
https://github.com/apollostack/apollo-client/issues/1084
