### ISSUE TITLE
Not able to add custom Variables in request body in Angular 2

### ISSUE THREAD

**Issue by PritiDawdaIntellect** [apollostack/apollo-client#1053]
How to introduce  custom variables in request body similar to default "Variables"   using Apollo-client in Angular 2.
Below is expected request body format:
{
   "query":"",
   "variables":"{}",
   "customVariable1":"{}", //This is additional variable
   "customVariable2":"{}", //This is additional variable
   "operationName":""
}

**Comment by helfer** [comment]
@PritiDawdaIntellect I'm not sure what you want to do that for, but you can use middleware. Hopefully the documentation can help you figure out how: http://dev.apollodata.com/core/network.html#networkInterfaceMiddleware
