### ISSUE TITLE
isomorphic-fetch issues

### ISSUE THREAD

**Issue by johnthepink** [apollostack/apollo-client#107]
So, I found something interesting when integrating apollo-client in to our app. I installed apollo-client in to our library, and then loaded our library in to our app that uses webpack.

isomorphic-fetch throws this error:

```
ReferenceError: self is not defined
```

Looks like this is an ongoing unfixed issue: https://github.com/matthew-andrews/isomorphic-fetch/pull/63

I set up a chain of forks to get it working, but not a permanent solution:

https://github.com/NewSpring/apollo-client/tree/self-fix
https://github.com/NewSpring/isomorphic-fetch/tree/self-fix

**Comment by stubailo** [comment]
Is isomorphic fetch the best option these days? AKA should we be trying to fix their bug, or should we switch to some simpler internal fetching mechanism?

**Comment by johnthepink** [comment]
I like the idea of something simpler internal

**Comment by stubailo** [comment]
What would it be? A different NPM package, or using XHR directly?

**Comment by stubailo** [comment]
I just looked at isomorphic-fetch, and it looks like it's _really_ unmaintained...

**Comment by stubailo** [comment]
Just emailed the author, maybe he'll be interested in some help with it.

**Comment by jbaxleyiii** [comment]
@stubailo I think we should drop both es6-promise and fetch. They are both environment based libraries that modern environment s don't need. I really like the fetch API but would rather give instructions to people to configure fetch / promise as part of their build if they need it then include it in this app.

**Comment by jbaxleyiii** [comment]
#122 removes fetch and promise as part of the lib BTW. I think fetch should be on the dev using the library, not the lib itself. If you are good with that, we can close this

**Comment by stubailo** [comment]
> I think fetch should be on the dev using the library, not the lib itself.

Hmm, this is a bit unfortunate because it means there is more boilerplate to set up the library. I feel like requiring the whole fetch API just to do one POST request is the main problem, IMO?

But for now let's do this until we can maybe just not use fetch anymore...

**Comment by jbaxleyiii** [comment]
@stubailo I can remove fetch today in favor of an existing supported node + browser solution! I'll open a PR tonight with it 👍

**Comment by stubailo** [comment]
Awesome! I'm going to start polishing up docs and example apps so I'll see how much of a hassle it is to get the right environment set up.

**Comment by jbaxleyiii** [comment]
the app should work as is, further discussion can be found here: #126
