### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by kamilkisiela** [apollostack/apollo-client#1074]
```
store.js -> optimistic-data/store.js -> store.js
core/ObservableQuery.js -> core/QueryManager.js -> scheduler/scheduler.js -> core/ObservableQuery.js
core/QueryManager.js -> scheduler/scheduler.js -> core/QueryManager.js
optimistic-data/store.js -> store.js -> optimistic-data/store.js
scheduler/scheduler.js -> core/QueryManager.js -> scheduler/scheduler.js
```

@DxCx

**Comment by helfer** [comment]
@kamilkisiela what is this for? Some tool that cannot handle circular dependencies?

PS: I'm surprised there isn't one between ApolloClient.ts and QueryManager.ts.

**Comment by kamilkisiela** [comment]
@helfer yes, rollup + systemjs for an example. There's [a webpack plugin](https://www.npmjs.com/package/circular-dependency-plugin) that shows all circular dependencies.

We work on some cool thing and this stops us, last missing piece.

**Comment by carloscordon** [comment]
I also managed to hit this issue with rollup. It took quite a while to debug. FWIW, here's the rollup issue for tracking this: https://github.com/rollup/rollup-plugin-commonjs/issues/105
