### ISSUE TITLE
apollo client clear cache

### ISSUE THREAD

**Issue by manuelfink** [apollostack/apollo-client#1075]
Ist it anyhow possible to clear the whole apollo cache?

Right now I have the problem, that on logout and login of another user, the data of the previous user is shown. Right now I work around with forcing a refetch, however this seems to not be the right way in my mind. I'd like to keep the caching functionality of apollo-client and don't like to require a force fetch on every query. 

Thus it is necessary to clear the apollo cache on logout.

**Comment by helfer** [comment]
@manuelfink I think `resetStore` is what you're looking for.

**Comment by manuelfink** [comment]
I guess I have the same issue as #692. I'm trying to access it through Angular2Apollo, which is not passing it down. Reposting it in Angular2Apollo. Thx

**Comment by manuelfink** [comment]
I guess resetStore is not fully what I need. It empties the store and refetches all queries. However, the queries watched by the old user are still in the store and apollo tries to refetch them. However those fail now, since the user is not logged in any more.

Is there any function which resets store and removes all queries from it?

**Comment by helfer** [comment]
@manuelfink you have to actually unsubscribe from the queries whose data you don't want any more before calling `resetStore`. I don't think Apollo Client should even have an option to stop all queries. That should only happen when a component is unrendered.

**Comment by manuelfink** [comment]
Thx, thats really good to know.  However I'm not sure if an destroy all subscriptions from apollo side would not make sense.

What happens inside apollo on unsubscribe, are the subscriptions internally not queried anymore then? Are queries only fetched from the server as long as there are observes on it?

### Whats the prober way to unsubscribe? Is it just like:

```
this.observer = this.postsService.getMyPosts(); 
this.observer.subscribe(...).
ngOnDestroy() {
  this.observer.unsubscribe();
}
```

### subscriptions within services

Using Angular 2 I do have several services eg to provide user information and rights. Some services just pass through the observers do fetch the data within the service on construction of the service. So the service itself subscribes to apollo store once, fetches data and assigns values to itself. Components then access the attributes of the service. Angular 2 constructs the service on first injection. They never get destroyed or unsubscribed in reason of ng2 dependency management. 

Right now I'm just thinking of implementing an unsubscribe and subscribe on the services which are triggered on login / logout. However a loggout may occure due to session expiry and not to a triggered logout.

I'm not jet sure whats the best way to handle unsubscribe in this case? Do you have best practice for this?

**Comment by manuelfink** [comment]
@helfer can you give an example on how to unsubscribe correctly?

**Comment by helfer** [comment]
@manuelfink unless you manually subscribed, you don't have to do anything special. React-apollo automatically unsubscribes when the component that started the query is unmounted.

**Comment by manuelfink** [comment]
I guess angular2-apollo is not automatically unsubscribing. Gonna ad a issue there. Thx.

I guess the following should be enough?

```
let sub = this.apollo.watchQuery({query: query}).subscribe();
sub.unsubscribe();
```

**Comment by kamilkisiela** [comment]
@manuelfink https://github.com/apollostack/angular2-apollo/issues/216#issuecomment-269972750

@helfer I will close it because you already gave the answer.
