### ISSUE TITLE
Clarification on id based cache for mutations

### ISSUE THREAD

**Issue by mmmdreg** [apollostack/apollo-client#1082]
The react-apollo docs on mutations suggest not using the response from mutations directly and instead relying on the ID-based cache. 

I have a mutation that creates an object and returns all the fields of the object needed to display it, including the ID. On running the mutation I see it in the apollo redux store. 

On successful mutation, I display the object by mounting a container that queries for that object by id, with the exact same fields. 

I would expect this would get resolved directly from the cache, but it always makes 2 network calls (the create and the query). Both network responses return exactly the same thing. If I use the nofetch option, the query doesn't resolve. 

Is my understanding/expectation of this behavior correct? If so, are there certain cases where it known to not work, or a specific setup needed to make it work?

**Comment by mmmdreg** [comment]
I guess it works only if the mutation is modifying an existing entity returned by a previous query.

**Comment by helfer** [comment]
@mmmdreg Yes, your understanding is correct. You can give a hint to Apollo Client though by using [cache redirects](http://dev.apollodata.com/react/cache-updates.html#cacheRedirect).
