### ISSUE TITLE
updateQueries will not update the data node

### ISSUE THREAD

**Issue by luckyyang** [apollostack/apollo-client#1085]
updateQueries will not update the data node after successfully get data from graphQl
apollo-client version: 2.5.20
react-apollo version: 0.7.2

### screenshots to illustrate the issue:

before create new data:
![2016-12-23 6 43 08](https://cloud.githubusercontent.com/assets/1963646/21452174/05eb3db2-c940-11e6-874b-629dbc51e180.png)

submit the form and get result from graphQL:
![2016-12-23 6 41 55](https://cloud.githubusercontent.com/assets/1963646/21452176/05ed8612-c940-11e6-8397-8e55c69cedf4.png)

data list not update automatically:
![2016-12-23 6 43 08](https://cloud.githubusercontent.com/assets/1963646/21452174/05eb3db2-c940-11e6-874b-629dbc51e180.png)

after refresh the page got data updated:
![2016-12-23 6 43 34](https://cloud.githubusercontent.com/assets/1963646/21452175/05eb304c-c940-11e6-9f48-66c64b5cf0bc.png)

attach my code:

```js
// graphqlModule/updateQueries/providerList.js

export const providerList = {
  userList: (prev, { mutationResult }) => {
    const result = mutationResult.data.registerWithIdentification

    return update(prev, {
      userList: {
        data: {
          $unshift: [result]
        }
      }
    })
  },
}
```

======

```js
// container.js

import { providerList as updateQueries } from 'graphqlModule/updateQueries/providerList'

  async submit() {
        const res = await mutate({ variables, updateQueries })
  }
```

**Comment by helfer** [comment]
@luckyyang Are you sure that your udpateQuery function even runs? If it runs, it most likely doesn't update because you have an error in it. I recently noticed that errors in reducers get swallowed, so it may be the same here. Make sure to check the entire update function is running, for example by putting a print statement right before the return statement.

**Comment by luckyyang** [comment]
> If it runs, it most likely doesn't update because you have an error in it

@helfer You mean **If it NOT runs** ? I don't see any errors in my code and dev tools.

> for example by putting a print statement right before the return statement

I can see the mutate result has been returned, I put a breakpoint before return statement and got no error and get the update data after refresh the page.

Do you have any idea about that?

**Comment by luckyyang** [comment]
I can get error when use wrong param for update:

```js
   return update(prev, {
      userList: {
        data: {
          **$push: result**
        }
      }
    })
```

![2016-12-26 12 39 16](https://cloud.githubusercontent.com/assets/1963646/21475630/cfc5dc62-cb68-11e6-9b5c-15e845e27896.png)

**Comment by luckyyang** [comment]
works now after I deleted all the data in database, I think It's due to the bad format of my history data. We have changed data schema for several times. close this issue
