### ISSUE TITLE
Query for an specific element in apollo store, which should already by cached

### ISSUE THREAD

**Issue by manuelfink** [apollostack/apollo-client#1086]
Is it anyhow possible to query the store for an specific element, if it is not available query it from graphql server?

E.g. if I come from the list view to the detailed view I may even have the full element within the apollo-client store. However firing a query always results to an query to the apollo server, updating the local store in browser. However I'm looking for the functionality the other way round, look if it is in store, if yes return it, if not query it from server.

An example from angular 2 how they request the service to provide the HeroDetails. Coming from the Heros List they redirect to the HeroDetails. The following is the code from Hero Details which fetches the Hero with a specific id:

```
ngOnInit() {
  this.route.params
    // (+) converts string 'id' to a number
    .switchMap((params: Params) => this.service.getHero(+params['id']))
    .subscribe((hero: Hero) => this.hero = hero);
}
```

However this element maybe already in the store since i queried before in the ListComponent:

```
posts(limit: 30, offset:1) {
  id
  titel
  content
}
```

I could query one element for example by now:

```
postsById (id: 1234) {
  id
  title
  content
}
```

However I rather like to tell apollo which object in the store the request would return and check if it has it already available. If the element is already available return it from local store, if not query it from remote server.

If this is not possible yet, I think this may be an interesting feature.

I'm not sure if this question is better located here or with angular2-apollo?

**Comment by helfer** [comment]
[Cache redirects](http://dev.apollodata.com/react/cache-updates.html#cacheRedirect) may be what you're looking for.

**Comment by manuelfink** [comment]
Yes thats what I'm looking for, thx! This was missing in the angular2-apollo docs. Wouldn't it make sense to add an centralized documentation for for advanced usage of apollo-client and reference it from react and all other clients?
