### ISSUE TITLE
networkStatus is 2 (NetworkStatus.setVariables) for 1st refetch

### ISSUE THREAD

**Issue by fson** [apollostack/apollo-client#1089]
If the `graphql` container has no variables set, calling `refetch` for the first time will set `networkStatus` to 2 (`NetworkStatus.setVariables`) instead of 4 (`NetworkStatus.refetch`).

The reason seems to be [this check](https://github.com/apollostack/apollo-client/blob/ab3d49e7234bf44f9788ef0fd9b5544a2909fa3d/src/queries/store.ts#L82-L92) that compares `previousQuery.variables` with `action.variables` and assumes the action is `setVariables` although it's a refetch. (When the container doesn't have any variables set initially,  `previousQuery.variables` is `undefined` and `action.variables` is `{}`.)

Subsequent refetches correctly set the network status to 4, because then `{}` is compared with `{}`.

<img width="743" alt="screen shot 2016-12-24 at 10 30 39" src="https://cloud.githubusercontent.com/assets/497214/21466099/4f5d1f1c-c9c5-11e6-9bea-c6b4bbdc4a7d.png">

**Comment by helfer** [comment]
@fson Thanks for the detailed bug report!

I think we should probably just set the initial variables to `{}` when they're undefined. That seems like the most consistent thing to do here. Would you have time to make a quick PR?

**Comment by fson** [comment]
@helfer I've implemented the fix in PR #1105.
