### ISSUE TITLE
Query diffing with variables

### ISSUE THREAD

**Issue by johnthepink** [apollostack/apollo-client#109]
It looks like the `minimizedQueryString` in QueryManager doesn't account for named queries, and therefore variables:

```js
const query = {
  query,
  variables,
  forceFetch: false,
}

apolloClient.query(query)
  .then((result) => {
    // yada yada
  });
```

If the original query was:

```
query getThing($thingId: Int!) {
  thing(id: $thingId) {
    title
  }
}
```

Assuming none of the data is current in the store, the minimized query string generated currently is:

```
thing(id: $thingId) {
  title
}
```

Which throws an error on the graph server since the variable isn't defined.

**Comment by stubailo** [comment]
Ooh, that's awkward. OK, maybe we need to pass around variable type definitions wherever we have `SelectionSetWithRoot` instances.

BTW - we want to do an initial open source launch next Tuesday, so keep the bugs coming and I'll try to fix them ASAP!

**Comment by johnthepink** [comment]
@stubailo will do. Thanks!
