### ISSUE TITLE
Uncaught TypeError when initialising ApolloClient

### ISSUE THREAD

**Issue by mattiasewers** [apollostack/apollo-client#110]
This might be something wrong on my part but when I'm calling `const client = new ApolloClient();` I get `Uncaught TypeError: _apolloClient.ApolloClient is not a constructor`, what am I doing wrong? Using webpack

**Comment by stubailo** [comment]
Oh, I think this might be related to default vs. named exports. Let me check.

**Comment by stubailo** [comment]
You need to import it using one of the two code snippets below:

```
import ApolloClient from 'apollo-client';
// or
const ApolloClient = require('apollo-client').default;
```

Let me know if that doesn't work.
