### ISSUE TITLE
mutate with reactivity

### ISSUE THREAD

**Issue by veeramarni** [apollostack/apollo-client#1101]
Is this a right way to use Observable? Although I may use a `map` in between to change few things.

I have not issue right now but want to know whether this would be best practice and will the `mutate` method return an observable in future, so we don't need to wrap with `fromPromise`.

```
  create: (data, callback) => ({ apolloClient, dispatch }) => {
    Observable.fromPromise(apolloClient.mutate({ mutation: CREATE_WORKSPACE,
      variables: { ...data },
    })).subscribe((result) => {
      callback();
      return dispatch({
        type: BOX_CREATE_DONE,
        payload: { result },
      });
    }, error => dispatch({
      type: BOX_CREATE_FAIL,
      payload: { error },
    }));
    return { type: BOX_CREATE_PROGRESS };
  },

```

**Comment by helfer** [comment]
@veeramarni it seems like your question is about observables, not about apollo client. As such, I think the slack channel or stackoverflow will be a better place to ask this question.
