### ISSUE TITLE
optimisticUI fails due to missing returnPartialData

### ISSUE THREAD

**Issue by veeramarni** [apollostack/apollo-client#1102]
Apollo-client version: 0.5.25

Initially, I was not successful in using optimizedUI, after digging a little bit I found out that query namespace (`addWorkspace`)which I used for the query wasn't same as the one in `optimisticResponse`. After correcting it, I was able to get the optimisticUI working fine. 

Now, I have tested it by removing one field (`creator`) in the optimisticUI, and it fails with `Perhaps you want to use the returnPartialData option?`. Not sure where i need to put `returnPartialData` in mutate function as it is not [documented](http://dev.apollodata.com/core/apollo-client-api.html).

graphql types
-----
```
type Workspace {
  _id: ID,
  name: String,
  lang: String,
  description: String
  creator: String,
  createdAt: Date
  updatedAt: Date
}

extend type Mutation {
  addWorkspace(
  name: String!
  description: String
  lang: String
  ): Workspace
}

```
container 
----
```
const mapDispatchToActions = { routeTo, ...boxAction };

export default apolloCompose(
  connect(null, mapDispatchToActions),
  graphql(WORKSPACE_LIST, {
    props: ({ ownProps, data: { workspace, loading } }) => ({
      loading, workspaces: workspace,
    }),
  }),
  graphql(CREATE_WORKSPACE, {
    props: ({ ownProps, mutate }) => ({
      create: (data, callback) => mutate({
      mutation: CREATE_WORKSPACE,
      variables: { ...data },
      optimisticResponse: {
        __typename: 'Mutation',
        addWorkspace: {
          __typename: 'Workspace',
          ...data,
          _id: getUid(),
        },
      },
      updateQueries: {
        returnPartialData: true,
        workspace: (prev, { mutationResult }) => {
          const newWorkspace = mutationResult.data.addWorkspace;
          const newValue = update(prev, { workspace: { $push: [newWorkspace] } });
          logger.info('newVlaue', newValue);
          return newValue;
        },
      },
            });
          },
        },
      }),
    }),
  }),
)(Dashboard);
```

error
--
```
Perhaps you want to use the `returnPartialData` option?
    at new ApolloError (webpack:///./~/apollo-client/errors/ApolloError.js?:31:23)
    at QueryManager.queryListenerForObserver (webpack:///./~/apollo-client/core/QueryManager.js?:196:44)
    at eval (webpack:///./~/apollo-client/core/QueryManager.js?:637:25)
```

**Comment by helfer** [comment]
@veeramarni you can't return partial data in your optimistic response. That would be like saying that you expect the response to be incomplete. Why exactly do you want to omit part of the response?

If you want to omit part of the response because you can't or don't want to have an optimistic update for that part, you could work with a placeholder which has the same shape, but which the UI won't render. It might not be the nicest way, but it should work.

**Comment by youngboy** [comment]
having the same issue here, but don't have any error/warning... took me few hours to figure out why my UI not rendering even if the reducer/updateQueries ran successfully....

in my example 
```
      optimisticResponse: {
        __typename: 'Mutation',
        postMessage: {
          __typename: 'Message',
          id: _.uniqueId('postMessage'),
          author: ownProps.author,
          text,
          type: null,
        },
      },
```

in the cases of 
- if I omit type field, even its value expected to be null
- if `ownProps.author` don't have __typename field

the optimistic update won't work without any warning/error message, which make it harder to debug ....

**Comment by veeramarni** [comment]
@youngboy I think you might have a try catch block somewhere which prevents from throwing the error. 

@helfer Thanks for the clarification.Yes, it wouldn't make sense without using all the fields. But I was wondering how to make it less typing if we have nested data with different `typenames`.

**Comment by calebmer** [comment]
@veeramarni unfortunately, you are just going to need the `__typename`. I’m going to close this issue for now as it looks like we have come to a resolution.

@youngboy if you don’t have a `try`/`catch` block that is catching the error then this is a different issue. If you could open a new issue that would be great 👍
