### ISSUE TITLE
Performance issues when sharing Redux store

### ISSUE THREAD

**Issue by bessey** [apollostack/apollo-client#1107]
As observed by myself and wmertens in #apollo-client-core. Every time an action occurs, Apollo spends a significant amount of time performing a deep equals of its state. Mostly quoting wmertens here:

![image](https://cloud.githubusercontent.com/assets/708200/21574927/850b157e-ceb1-11e6-8636-2b108fea66e7.png)

In particular, https://github.com/apollostack/apollo-client/blob/ab3d49e7234bf44f9788ef0fd9b5544a2909fa3d/src/ApolloClient.ts#L465 gets executed every time I dispatch any action, and it looks at the active queries and does a deep comparison of their results, which takes 200ms in my case.

Seems to me that at the very least, there should be a test there for the action type, so it only fires on types starting with "APOLLO_"

**Comment by bessey** [comment]
Proposed fix found in #1104

**Comment by wmertens** [comment]
Note, #1104 is not a fix for the deep comparison.

**Comment by calebmer** [comment]
This should be fixed by https://github.com/apollostack/apollo-client/pull/1136 where a deep equality check is replaced by a [referential equality check](https://github.com/apollostack/apollo-client/pull/1136/files#diff-f28988ac35502178bef737788c3d4cd5R381) (`===`).
