### ISSUE TITLE
Conflict between apollo-client node and webpack-env definitions

### ISSUE THREAD

**Issue by Aranir** [apollostack/apollo-client#1108]
As soon as I add the apollo-client to my application I receive the following conflicts:

```
Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'RequireFunction', but here has type 'NodeRequire'
```

Which is raised in the folder:
`/node_modules/apollo-client/node_modules/@types/node/index.d.ts`

I know this is more of an issue with how `webpack-env` overwrite the node.d.ts definitions, but has anyone managed to find a way around this?

**Comment by helfer** [comment]
@Aranir we're going to clean up the types and make node typings a dev dependency. After that, this should be resolvable.

**Comment by calebmer** [comment]
The dependency on node types is now a [dev dependency](https://github.com/apollostack/apollo-client/blob/master/package.json#L59) in `0.7.3` 🎉 

Let us know if you have any more problems @Aranir
