### ISSUE TITLE
ApolloQueryObservable not working with rxjs forkJoin #bug

### ISSUE THREAD

**Issue by manuelfink** [apollostack/apollo-client#1109]
I have the problem that I need to resolve two data sources for a screen and can start rendering screen as soon as both are available. However Observable.forkJoin seem not to be working with Apollo. Subscribe is never being called. Is this a bug or am I doing anything wrong?

"angular2-apollo": "^0.8.0"
"apollo-client": "^0.5.23",

```
import {Observable, Subject} from "rxjs/Rx";

let fork = Observable.forkJoin(
  this.apollo.watchQuery({query:query})
);
fork.subscribe({
  (data) => console.log(data);
})
```

**Comment by kamilkisiela** [comment]
here's why https://github.com/apollostack/angular2-apollo/issues/219#issuecomment-269970003
