### ISSUE TITLE
Should we have at least a very simple time based cache invalidation?

### ISSUE THREAD

**Issue by sikanhe** [apollostack/apollo-client#1114]
I think we should at least implement a very simple cache invalidation option for queries. something like

```
client.query({options: {cacheExpireAt: () => Date.now() + 30000 })
```

So that whenever the query gets called again, it forces a refetch if the current time is past the expiration.  

This is not perfect but we should at least have some kind of query based invalidation feature going for now. 

Is there any big downside of adding this ?

**Comment by helfer** [comment]
@sikanhe we've seen increased interest in the topic, so I think it's safe to say that we'll do something on that front soon. Let's keep all discussion related to the topic on #825!
