### ISSUE TITLE
Graphql caching remove headers on each new requests

### ISSUE THREAD

**Issue by atu** [apollostack/apollo-client#1117]
Hey there,

I'm rebuilding my meteor app into an apollo app based on express. Everything went well until I need to implement the accounts system. I'm using passport.js and JWT (because session wasn't working).

I have an issue where the Headers of each request are not being sent to the server. I think caching might be the issue.

Here is my server.js:

```javascript
import 'babel-polyfill'
import http from 'http'
import express from 'express'
import helmet from 'helmet'
import bodyParser from 'body-parser'
import cookieParser from 'cookie-parser'
import session from 'express-session';
import passport from 'passport';
import mongoose from 'mongoose';
import morgan from 'morgan'
import compression from 'compression'
import hpp from 'hpp'
import throng from 'throng'
import { graphqlExpress, graphiqlExpress } from 'graphql-server-express';

import webpack from 'webpack'
import webpackDevMiddleware from 'webpack-dev-middleware'
import webpackHotMiddleware from 'webpack-hot-middleware'

import { isAuthenticated, onAuthenticate, signUp, login, forgot, handleReset } from './auth';
import DefaultServerConfig from './config';
import webpackConfig from '../tools/webpack.client.dev';
import { compileDev, startDev } from '../tools/dx';
import appRenderer from './middleware/app-renderer';
import schema from './api/schema';

export const createServer = (config) => {
  const __PROD__ = config.nodeEnv === 'production'
  const __TEST__ = config.nodeEnv === 'test'
  let assets = null

  const app = express()
  app.disable('x-powered-by')
  app.use(express.static('public'))
  mongoose.Promise = global.Promise;
  mongoose.connect('mongodb://localhost:27017/test');

  if (__PROD__ || __TEST__) {
    app.use(morgan('combined'))
    app.use(helmet())
    app.use(hpp())
    app.use(compression())
    if (__PROD__) {
      assets = require('../assets.json')
    }
  } else {
    app.use(morgan('dev'))
    const compiler = compileDev((webpack(webpackConfig)), config.port)
    app.use(webpackDevMiddleware(compiler, {
      quiet: true,
      watchOptions: {
        ignored: /node_modules/
      }
    }))
    app.use(webpackHotMiddleware(compiler, { log: console.log }))
  }

  // i/o middlewares
  app.use(bodyParser.json())
  app.use(bodyParser.urlencoded({ extended: true }))
  app.use(passport.initialize());

  app.use('/graphiql', graphiqlExpress({
    endpointURL: '/graphql'
  }))

  app.use('/graphql', graphqlExpress((req) => {
    console.log(req.get('authorization') // always empty on the second requests
    return {
      graphiql: true,
      pretty: true,
      schema,
      context: {}
    }
  }));

  // Auth route
  app.post('/api/reset', handleReset(), (req, res, next) => {
    next();
  });

  app.post('/api/forgot', forgot(), (req, res, next) => {
    next();
  });

  app.post('/api/login', login(), (req, res, next) => {
    next();
  });

  app.post('/api/logout', (req, res) => {
    req.logout();
    res.json({logout: true});
  });

  app.post('/api/signup', signUp(), (req, res, next) => {
    next();
  });

  app.use(appRenderer);

  return http.createServer(app)
}

export const startServer = (serverConfig) => {
  const config = { ...DefaultServerConfig, ...serverConfig }
  const server = createServer(config)
  server.listen(config.port, (err) => {
    if (config.nodeEnv === 'production' || config.nodeEnv === 'test') {
      if (err) console.log(err)
      console.log(`server ${config.id} listening on port ${config.port}`)
    } else {
      startDev(config.port, err)
    }
  })
}

if (require.main === module) {
  throng({
    start: (id) => startServer({ id }),
    workers: process.env.WEB_CONCURRENCY || 1,
    lifetime: Infinity
  })
}
```

Here is my apolloClient.js:

```javascript

import ApolloClient, { createNetworkInterface } from 'apollo-client';
import _ from 'lodash';
import log from '../log';

const networkInterface = createNetworkInterface('http://localhost:3000/graphql');

networkInterface.use([{
  applyMiddleware: (req, next) => {
    req.options.headers = new Headers();

    if (typeof window === 'object') {
      const token = localStorage.getItem('nh.token');
      const userId = localStorage.getItem('nh.userId');

      if (!req.options.headers)
        req.options.headers = new Headers();

      if (token)
        req.options.headers.authorization = `Bearer ${token}`;
        req.options.headers.userId = userId;
    }

    next();
  }
}]);

const ApolloClientSingleton = new ApolloClient({
  ssrMode: true,
  networkInterface,
  shouldBatch: true,
  dataIdFromObject: obj => obj.id,
});

export default ApolloClientSingleton;


```

If you have any ideas, I would love to have them :)

**Comment by atu** [comment]
I tried different configuration and `ssrMode: true` seems to be the reason of the issue. How can I keep the ssrMode and have access to the req.headers.authorization.

**Comment by helfer** [comment]
@atu I'm not sure I fully understand what issue you're running into. Can you describe what you're doing, what you expect to see, and what you're seeing instead?

It sounds like you're saying headers aren't properly added with each request to the server? It doesn't seem likely to me that this has anything to do with caching, or even ssrMode for this matter, because we're using SSR and header-based authentication in the GitHunt example app, and everything seems to work fine there. Is it possible that it doesn't work for you when you use SSR because the right tokens are not available on the server when your page is rendered? We've had a similar issue with GitHunt at one point, that we then resolved.

However, if headers are added if you set `ssrMode` to false, but not when you set it to true, then that indicates a bug and we should look into it.

**Comment by atu** [comment]
@helfer Thank you for your answer.

I'm trying to send for each graphql request, the authorization token in the headers.

When `ssrMode: false`, I get the authorization header added.
When `ssrMode: true`, I get the authorization header only on the first request.

Is it clearer?

**Comment by helfer** [comment]
@atu Okay, that's weird. Do you think you could create a failing test case by providing a mock fetch function that checks if it's being called with the right headers?

**Comment by helfer** [comment]
Actually, I just checked our source code and `ssrMode` is used only to disable forceFetch when doing SSR on the server. if there's any connection you should be able to reproduce the issue reliably on every request simply by setting `forceFetch` to true for that query. Can you give that a try?

**Comment by atu** [comment]
@helfer I'm on it :) It would make sense

**Comment by atu** [comment]
@helfer I tried again and it looks that it's working now. I tried to have 2 apolloClient instead of one shared by the server and the client.

It seems to have resolved the issue. I will keep trying and then close this issue.

**Comment by calebmer** [comment]
@atu sounds like you resolved the issue so I’m going to close. Let us know if you find any other Apollo Client bugs 👍
