### ISSUE TITLE
Docs: query batching

### ISSUE THREAD

**Issue by mmmdreg** [apollostack/apollo-client#1126]
First paragraph of 'Query Batching' says 'this batching supports all GraphQL endpoints, including those that do not implement transport-level batching'. 

Later on it says 'Query batching is a transport-level mechanism that works only with servers that support it'. 

This seems contradictory and a quick test shows the first paragraph is no longer true since the batching changes in 0.5.

**Comment by helfer** [comment]
@mmmdreg you're right, we no longer do that kind of query batching. Could you submit a PR to the docs to remove that sentence?

**Comment by mmmdreg** [comment]
https://github.com/apollostack/core-docs/pull/239
