### ISSUE TITLE
Do smarter root query diffing

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#113]
Right now, if you do the following queries in succession:

```
// First
{
  todoList(id: 5) {
    title
    createdAt
    tasks {
      name
      completed
    }
  }
}

// Second
{
  todoList(id: 5) {
    tasks {
      name
      completed
      author
    }
  }
}
```

The query diffing algorithm will refetch:

```
// Current implementation, not 100% efficient
{
  todoList(id: 5) {
    tasks {
      name
      completed
      author
    }
  }
}
```

Instead of:

```
// Desired, completely efficient based on given info
{
  todoList(id: 5) {
    tasks {
      author
    }
  }
}
```

This was a decision to not implement a new query diffing/merging algorithm before alpha. So it still works now, but will refetch some data.

## The fix

In the XXX sections in `diffAgainstStore`: https://github.com/apollostack/apollo-client/blob/8df914c21980fb323699fc795171b2aedf3f98e1/src/data/diffAgainstStore.ts#L186

Instead of bailing out the first time we find a missing field, we should instead traverse all of the subtrees, and make a union of all of the actual missing fields. This requires an algorithm for recursively merging GraphQL SelectionSet ASTs, which isn't hard to build but is non-trivial.

Ideally, this merging algorithm would be a separate, well-tested NPM package that we can bring to the wider community, since it's totally agnostic to Apollo Client.

**Comment by mquandalle** [comment]
Have you inverted the current and desired implementations?

**Comment by stubailo** [comment]
Oh, indeed I have! Thanks for the heads up.

**Comment by stubailo** [comment]
After talking to @martijnwalraven: Another option is to only do this for single fields, but not for arrays. That way the algorithm is much simpler, and we don't end up with some odd edge cases.
