### ISSUE TITLE
[Question] Field names collision in query result.

### ISSUE THREAD

**Issue by pc-lover** [apollostack/apollo-client#1138]
As the [docs](http://dev.apollodata.com/react/queries.html#default-result-props).
I wonder if the root fields in the query can contain fields named "loading" or "error"?
What would happen if they contain those fields?

**Comment by stubailo** [comment]
I think React-Apollo will throw an error. You can avoid those field names incur data easily by using an alias.

**Comment by pc-lover** [comment]
Thanks for the answer. But, in my opinion, I think it'd be more straightforward if the root fields are wrapped in a parent field. What do you think about it?

**Comment by calebmer** [comment]
@pc-lover we can definitely consider that for React Apollo. If you’d like to submit a PR feel free 👍
