### ISSUE TITLE
updateQueries when deleting, how? 

### ISSUE THREAD

**Issue by rnenjoy** [apollostack/apollo-client#1142]
Hello! 

If have trouble finding documentation on this. On a Posts collection, i can easily make a addPost mutation, return the newly created post and have the updateQueries reflect the changes to the store. 

But what if i have a mutation that is deletePost. I will not get anything useful back from graphqlserver since the item is removed. How do i make so the store updates that the entry is deleted and that the ui is in sync?

**Comment by stubailo** [comment]
You can use the ID of the deleted item when updating the queries.

**Comment by rnenjoy** [comment]
Just loop through the array and delete the one and return the new array? Is it that simple? :)

**Comment by stubailo** [comment]
Yep!

**Comment by rnenjoy** [comment]
Ok thanks alot for the help and your awesome work with apollo! You are a true inspiration! :)

**Comment by stubailo** [comment]
If you have a moment to sent a PR to the docs that would be much appreciated!
