### ISSUE TITLE
Specifying production vs. development environment

### ISSUE THREAD

**Issue by Poincare** [apollostack/apollo-client#1153]
There are several parts of Apollo Client that need to know whether Apollo Client is running in a dev or production environment, e.g. transport batching vs. no transport batching, persisted queries vs. no persisted queries, deep freezing results vs. not deep freezing them. 

Instead of replicating this logic and deciding whether or not it is a production environment in several different places, we should just have one central source where the application developer can specify this. This probably makes sense as an option to the `ApolloClient` constructor.

Thoughts?

**Comment by helfer** [comment]
I like the idea of having the logic in a central place, but using `process.env.NODE_ENV` is pretty much the standard, so my suggestion would be to keep that and maybe just provide a tiny util function that's called `isProductionEnv` or something. That way we could always change it later.

Or are there concrete advantages to requiring people to pass that option directly to Apollo Client?

**Comment by Poincare** [comment]
That seems like a fine solution. We should probably add `isProductionEnv` to the ApolloClient class and probably just document it somewhere so I'll keep this issue open until we do.

**Comment by kamilkisiela** [comment]
@helfer I could include it here #1169 

This way we can use it in one of these functions and in every place of apollo-client we could use these functions and not checking `process.env.NODE_ENV` manually.

**Comment by calebmer** [comment]
As https://github.com/apollostack/apollo-client/pull/1169 got merged it looks like we have this now 👍
