### ISSUE TITLE
ApolloProvider causes ReactElementValidator to throw type is invalid error

### ISSUE THREAD

**Issue by Rastamafugg** [apollostack/apollo-client#1162]
I'm trying to set up the Apollo Client into an existing React/Redux app but when I try to render the ApolloProvider element, I get the following error:

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

When I step into the createElement function code generating the problem, I can see that the type parameter is the ApolloProvider instance, which is a React Component, but the validType logic only appears to accept the type parameter as a string or function (See snippet below).  I don't get how this is happening.

```
createElement: function (type, props, children) {
    var validType = typeof type === 'string' || typeof type === 'function';
```

**Comment by helfer** [comment]
Hi @Rastamafugg. Thanks for opening an issue. I think it should go on apollostack/react-apollo. Can you close it here and open it over there? That way it's more likely to get attention from the right people.

**Comment by Rastamafugg** [comment]
Ok, will do, thank you.
