### ISSUE TITLE
Typescript error (+ fix) for ApolloQueryResult definition

### ISSUE THREAD

**Issue by wizardofjoz** [apollostack/apollo-client#1164]
Using Typescript 2.1.4 I get this error:

`Error:(19, 50) TS2314:Generic type 'ApolloQueryResult' requires 1 type argument(s).`

in type definition file: Angular2Apollo.d.ts

I noticed the errors when using the Angular translation tool ng-xi18n with the apollo client.

**It's easily solved** by changing 3 lines to use `Observable<ApolloQueryResult<any>>` instead of the current `Observable<ApolloQueryResult>`

changing lines 17-19 in Angular2Apollo.d.ts to below snippet solves the issue:
```
watchQuery(options: DeprecatedWatchQueryOptions): ApolloQueryObservable<ApolloQueryResult<any>>;
query(options: DeprecatedWatchQueryOptions): Observable<ApolloQueryResult<any>>;
mutate(options: MutationOptions): Observable<ApolloQueryResult<any>>;
```

**Comment by helfer** [comment]
@wizardofjoz yes, this was a breaking change we introduced with version 0.7. I'll make a quick update to the changelog to emphasize the breaking changes.
