### ISSUE TITLE
Paths to internal modules have changed - missing usage of deploy.sh

### ISSUE THREAD

**Issue by kamilkisiela** [apollostack/apollo-client#1170]
Have I missed something or you no longer use `scripts/deploy.sh` to deploy new releases?

Since v0.7 to get something from inside of `apollo-client` we need to use `lib/src` prefix. Before that it was just `apollo-client/path/to/something`.

It's a thing because you guys have used `npm publish` and not `scripts/deploy.sh`. 

Because of that I had to make a change in `angular2-apollo`. Do you plan to do this in every next release or it was just by mistake?

**Comment by helfer** [comment]
Whoa, if that happened I think it was by mistake! Been deploying too many different libraries lately and they all work a bit differently. Let's fix this by writing a `npm run deploy` command for every project.

I will release 0.7.2 right now to fix this.

**Comment by stubailo** [comment]
> Let's fix this by writing a npm run deploy command for every project.

Alternatively you could also have a `prepublish` that checks the files first - IMO having `npm publish` be a thing you can run is pretty nice.

**Comment by helfer** [comment]
@stubailo Ideally we should have both. I agree that it's nice to be able to run `npm publish`, and that would still be possible on nearly every repo. But in my mind nothing beats being able to run the same command on all repos. It's just much less likely that you'll make a mistake that way.

**Comment by helfer** [comment]
0.7.2 released, should be back to normal now.
