### ISSUE TITLE
After server render the page, use initial state on client side, actions of further query does not change state

### ISSUE THREAD

**Issue by shendepu** [apollostack/apollo-client#1187]
This is a SSR setup, all the html string and store state has been retrieved and sent to browser client, and redux store is initialized correctly. But the query generated by operation in browser does not change the store state at all, although the query is sent to server and get response, even the `APPLLO_QUERY_INIT` and `APOLLO_QUERY_RESULT` action is logged by redex dev tool.  And no error produced.

The same code runs through non-SSR can work correctly.

It seems that apollo reducer does not handle the actions or failed to process the action but return previous state, so state is not changed. 

There is one finding I am not sure whether it is the cause :
In the store state received from server in SSR mode, the apollo.queries object has one query which id is `2`, but if run through local, the id is `1`. After server rendering, the first action in browser is '@@INIT', and second `APOLLO_QUERY_INIT` and third `APOLLO_QUERY_RESULT_CLIENT` and the queryId in second and third action is `1`

**Comment by stubailo** [comment]
> But the query generated by operation in browser does not change the store state at all

What kind of change in the store are you looking for? It's not clear from the issue description what behavior you are expecting.

**Comment by shendepu** [comment]
It is simple pagination query. server return first page of data, and in browser, go to next page. It runs completely fine if app is run locally.

Here is some redux dev tool action and state snapshots: 

This should be generated by component loaded in browser from initial state by apollo-client

![image](https://cloud.githubusercontent.com/assets/4743845/22010804/676570e6-dcc6-11e6-9643-d07601aaab09.png)

And it is strange to me that apollo.queries has the query which id is `2`. but it is `1` if run from local.

![image](https://cloud.githubusercontent.com/assets/4743845/22010793/5860dcca-dcc6-11e6-9849-7e9b658dea3d.png)

Below is generated by go to next page on browser

We can see the action actually  has data
![image](https://cloud.githubusercontent.com/assets/4743845/22010823/7fe508e8-dcc6-11e6-9a7d-59dcc7aac33f.png)

but the state does not change at all.

![image](https://cloud.githubusercontent.com/assets/4743845/22010830/89f0d40c-dcc6-11e6-9c8a-17a04a5d1294.png)

**Comment by stubailo** [comment]
Thanks for the more detailed report!

**Comment by shendepu** [comment]
I just added console.log in createApolloReducer function in node_modules. go to next page in browser with SSR version, the reducer is entered at all, while running at local version enter into the reducer as expected.

**Comment by shendepu** [comment]
I further added console.log in redux combineReducers function, there is no actions dispatched into the root reducer, therefore the `APOLLO_*`actions are not dispatched to apollo reducer. 

But the redux dev tool catches the actions. Here I am wondering if the store by apollo-client is same with the one I created. 

The store and client is simply passed to `ApolloProvider`
```
<ApolloProvider store={store} client={client}>
```

I even called client.setStore(store) explicitly in the beginning of application. but it is same.

**Comment by shendepu** [comment]
I hunt it down the problem. It is my issue.

I have below code to makeRootReducer, the missingReducers part is to avoid redux complain if initial state has keys that combineReducers do not have. 
```
export const makeRootReducer = (apolloClient, asyncReducers, initialState) => {
  let missingReducers = { }
  if (initialState !== undefined && typeof initialState === 'object') {
    for (let key in initialState) {
      if (!asyncReducers.hasOwnProperty(key)) {
        missingReducers[key] = () => initialState[key]
      }
    }
  }
  return combineReducers({
    location: locationReducer,
    form: formReducer,
    apollo: apolloClient.reducer(),
    auth: authReducer,
    ...asyncReducers,
    ...missingReducers
  })
}
```

It works fine when running locally because there is no initial state at all, so missingReducers calculation is simply ignored.

The fix is simple that just move `...missingReducers` to the top, otherwise, the apollo reducer is override incorrectly.
```
return combineReducers({
    ...missingReducers, // important to be first!!! If initial state has key of sync reducer,
                        // it will be in missingReducers, put it at first order, so they will
                        // be override by below
    location: locationReducer,
    form: formReducer,
    apollo: apolloClient.reducer(),
    auth: authReducer,
    ...asyncReducers
  })
```

This can be closed.
