### ISSUE TITLE
Record deletion via subscription

### ISSUE THREAD

**Issue by cybernetlab** [apollostack/apollo-client#1190]
Hi!

I'm implementing SubscriptionNetworkInterface to connect to Phoenix through WebSockets and to have data updates via subscription. For now updates are working well and I'm calling `handler(errors, data)` callback to inject data when it was received from WS. This callback provided when subscription is initialized.

The question is - how to handle record deletion? I can form any message on the server side (for example, provide ids to delete in `delete` field - not in `data`) to signal that deletion occurs. But I can't figure how to force apollo-client to delete records from store. Is it possible to do this via `handler(errors, data)` callback or there are another approach for this?

**Comment by calebmer** [comment]
Look into [`updateQueries`](http://dev.apollodata.com/react/cache-updates.html#updateQueries) @cybernetlab. You should be able to create a reducer which filters out an object with a given id from a list effectively deleting it. Let us know if you need any more information 👍
