### ISSUE TITLE
Bug in networkInterface.query

### ISSUE THREAD

**Issue by yurigenin** [apollostack/apollo-client#1199]
When my graphql server is not running and I use a proxy on the web server the response from web server is:
```
body: (...)
bodyUsed: false
headers: Headers
ok: false
status: 504
statusText: "Gateway Timeout"
type: "basic"
url: "http://localhost:7770/graphql"
```
But the networkInterface.query has the following handler:

```javascript
.then(({ response }) => (response as IResponse).json())
```
which throws a parsing error since the body is not a json stream but empty.

The simple fix would be:
```javascript
.then(({ response }) => {
   const iResponse = response as IResponse;
   if (iResponse.ok) {
      return iResponse.json();
   }
   throw new Error('status: ' + iResponse.status + ', statusText: ' + iResponse.statusText);
}
```

**Comment by helfer** [comment]
@yurigenin Thanks for the bug report!

I'd be happy to take a PR from anyone fixing this in the way outlined above. 🙂

**Comment by hakimelek** [comment]
I am going to push the fix, but first, is there a good way to test handling the response?
