### ISSUE TITLE
Setup CD to npm?

### ISSUE THREAD

**Issue by jbaxleyiii** [apollostack/apollo-client#120]
Not sure if you want to or not, but Travis allows auto publish to npm.

https://docs.travis-ci.com/user/deployment/npm/

**Comment by stubailo** [comment]
Yeah that's a great idea! Unfortunately it still doesn't mean we get to publish directly from a PR since that doesn't make a tag, but it's still better I guess?

**Comment by jbaxleyiii** [comment]
@stubailo I wrote this for our usage on circle ci. Any libs we ship to npm get deployed on merge to master. https://github.com/NewSpring/ops-ci-npm-publish.

Either way, just thought I'd mention it :+1:

**Comment by stubailo** [comment]
Yeah @helfer and I were just talking about this the other day, basically I was complaining that it's a hassle to republish manually.

**Comment by jbaxleyiii** [comment]
Automate what's important right? We have a pretty hard and fast rule that if we can't auto deploy something, we don't build it. It's mainly so we can take vacations and not be on call hahah

**Comment by jbaxleyiii** [comment]
Decided that auto deployment isn't the way to go

**Comment by stubailo** [comment]
Yeah to explain further I really want to be able to add people as contributors but not trust them to publish to NPM. Perhaps some auto-deploy with a bot that checks with the admins would work.

**Comment by jbaxleyiii** [comment]
@stubailo I think facebook has a deploy bot and I know github has deployments hooked into hubot. Could be something to do one day 👍 

For now a deploy script:
https://github.com/apollostack/apollo-client/pull/169
