### ISSUE TITLE
updateQueries (and reducer) doesn't change query when prevResult returned server error

### ISSUE THREAD

**Issue by rafrex** [apollostack/apollo-client#1201]
I have a `CurrentUser` query that the server returns an error for when there is no logged in user. When a user logs in I want to update the `CurrentUser` query with what's returned from the mutation.

With `updateQueries` the previous result is a blank object (because the server returned an error the last time the query ran because no current user exists). I return what the query should be updated to based on the mutation result, but `this.props.data` passed in from the `CurrentUser` query hasn't changed and still has `data.error.graphQLErrors...`.

I also tried implementing this with a `reducer` in the `CurrentUser` query instead, but the same problem occurred even though the correct data is available in `action.result.data...`.

Note that if there is already a current user (so the server doesn't return an error), and I log in a different user, the `updateQueries` code works fine, and the result of the mutation with the new user is available in `this.props.data` (this won't happen in practice, but ran the test to make sure the code is working).

```js
updateQueries: {
  CurrentUser: (prev, { mutationResult }) => {
    // prev is a blank object when the server returns an error for the previous result
    console.log(prev);
    return {
      viewer: {
        user: mutationResult.data.loginUser.user,
      },
    };
  },
},
```

Using: `apollo-client` 0.7.3, and `react-apollo` 0.8.1

**Comment by calebmer** [comment]
This will probably be fixed when we refactor errors because currently errors are designed to “blow up” the system. For now, you should avoid errors if you do not intend for them to be fatal. Instead just return null from your initial query instead of an error.

**Comment by rafrex** [comment]
Okay, I'm using scaphold as a backend, so don't have much control over it, but I'll let them know.

**Comment by rafrex** [comment]
Talked to scaphold, and they changed the response to `null`, this fixes my issue as now `updateQueries` works properly, but I think the issue with errors still stands.

**Comment by calebmer** [comment]
Agreed. I’m going to close as we have other issues and documents tracking better GraphQL error handling. It is definitely on our roadmap for 1.0 👍
