### ISSUE TITLE
APOOLQUERY_RESULT result in diff with reducerError from null => {}

### ISSUE THREAD

**Issue by shendepu** [apollostack/apollo-client#1206]
I have a very simple case:

ApolloClient instance is configured with 
```
dataIdFromObject: (result) => {
  if (result.id) return result.__typename + '__' + result.id
  return null
}
```

/positions: is page show list of positions using normal offset-based pagination
/positions/{positionId}: is a page show detail of a position

Both of them use apollo-client and react-apollo to access graphql api and add data to props

Steps reproduce the issue all the time: 

1. Refresh /positions which mout the positions page (container), default with pagination 0 page index (index starts from 0)
2. Click one position go to /positions/{positionId} page, then click position menu back to /positions page, and pagination on /positions page still 0
3. Click pagination to 1, it works fine, then click back to pagination 0, the APOLLO_QUERY_RESULT get reducerError with `{}` snapshot as below

![image](https://cloud.githubusercontent.com/assets/4743845/22133215/f5284022-def9-11e6-938f-e4ab38c7d113.png)

I added some logs in apollo-client library, and found out it actually an exception from apolloReducer, 

```
Error: Store error: the application attempted to write an object with no provided id but the store already contains an id of EmplPositionClass__RW1wbFBvc2l0aW9uQ2xhc3N8UHJvZ3JhbW1lcg== for this object.
    at writeFieldToStore (http://192.168.2.103:3000/vendor.50e80fe9b4505012710a.js:5926:23)
    at http://192.168.2.103:3000/vendor.50e80fe9b4505012710a.js:5819:17
    at Array.forEach (native)
    at writeSelectionSetToStore (http://192.168.2.103:3000/vendor.50e80fe9b4505012710a.js:5813:29)
    at writeFieldToStore (http://192.168.2.103:3000/vendor.50e80fe9b4505012710a.js:5911:9)
    at http://192.168.2.103:3000/vendor.50e80fe9b4505012710a.js:5819:17
    at Array.forEach (native)
    at writeSelectionSetToStore (http://192.168.2.103:3000/vendor.50e80fe9b4505012710a.js:5813:29)
    at http://192.168.2.103:3000/vendor.50e80fe9b4505012710a.js:5961:9
    at Array.map (native)
```

**Comment by shendepu** [comment]
I find out the issue is in my query 

when have the issue the query was 
```
query ($pageIndex: Int) {
  mantle {
    emplPositions (
      periodValid_: true,
      pagination: {
        pageIndex: $pageIndex,
        pageSize: 10,
        orderByField: "-lastUpdatedStamp"
      }) {
      edges {
        node {
          id
          emplPositionId
          fullTimeFlag
          virtualFlag
          virtualRootFlag
          emplPositionClass {
            title
            description
          }
          statusId
          status {
            description
          }
          lastUpdatedStamp
        }
      }
      pageInfo {
        pageIndex
        pageSize
        totalCount
      }
    }
  }
}
```

Notice that emplPositionClass and status field does not have id selectionSet, after adding id to both of them, the issue is gone.

**Comment by shendepu** [comment]
So I wonder, since the ApolloClient support `addTypename` configuration, if it is reasonable also add a `addId` configuration, so graphql request automatically adds id field just linke __typename. 

When graphql backend is ensured supporting id on every object type, adding id in graphql query is kind of tedious.

**Comment by Poincare** [comment]
Unfortunately, the GraphQL spec does not include an `__id` field similar to the `__typename` one so we can't really do this in a universally acceptable way without having information about the schema.
