### ISSUE TITLE
With react-apollo, `updateQueries` only updates queries on components that are mounted

### ISSUE THREAD

**Issue by ckimes89** [apollostack/apollo-client#1211]
I'm assuming this is by design, but unless I'm missing something it seems to make certain patterns hard or impossible. Here's the simple version of a project I have currently:

List page with a list query
Detail page with a single object query (usually loaded from list cache)
Create page that redirects to list page after executing a create mutation

The `create` mutation has an `updateQueries` object that should update the query on the list page. However, because I'm using `react-router`, the list page is unmounted which means the cache will never get updated. Sending the user back to the list page pulls from the cache, so it doesn't show the new data.

Is there a way to update the cache for queries that are not used in a mounted component? Am I fundamentally misusing `updateQueries`?

**Comment by SachaG** [comment]
I think this issue might belong on the [react-apollo](https://github.com/apollostack/react-apollo/) repo. But I'd be curious to know about this as well.

**Comment by bradabelgit** [comment]
Have you experienced something similar? 

I dug into the react-apollo repo a little bit, and all it seems to be doing is pulling the refetch function off of the observableQuery and applying that to the data returned.

See: https://github.com/apollostack/react-apollo/blob/master/src/graphql.tsx#L61
and: https://github.com/apollostack/react-apollo/blob/master/src/graphql.tsx#L465

**Comment by codylandry** [comment]
I'm having issues with this myself.  I have a pattern identical to the OP with react-router where users create, edit and delete 'items'.  In my updateQueries for each mutation, I update the query used on the list page. Each time, the view does not change when redirected back to the list page.

**Comment by helfer** [comment]
@ckimes89 Thanks for filing an isssue! It is the same underlying issue as #1129, so I will close this one to keep things simple. There was a design flaw that we overlooked initially, but we came up with a different solution that we will hopefully finish implementing shortly. The solution will basically be to no longer provide named queries, but instead provide the query that you want to have updated in the `updateQueries` call yourself.

**Comment by SachaG** [comment]
@helfer how would that work with reducers? You'd also provide the reducer for the query you want updated in the mutation container itself?

**Comment by helfer** [comment]
@SachaG We're not yet sure what to do with reducers. We may replace them with some form of a global reducer that doesn't require any specific query to be active.

**Comment by SachaG** [comment]
Oh, that could work. 

Maybe that's another debate, but I wonder if it's a good idea to have both reducers and `updateQueries` though. It seems like having two ways to do the same thing means more work for the Apollo team, and more chances to make mistakes for end users.
