### ISSUE TITLE
ApolloClient is not a constructor

### ISSUE THREAD

**Issue by tizmagik** [apollostack/apollo-client#1212]
Hi. Just following the docs trying to get a simple use case working, and the following produces an error:

```js
const ApolloClient = require('apollo-client');

const client = new ApolloClient();
```

Error is:
```
/workspace/scratch/temp/test.js:3
const client = new ApolloClient();
               ^

TypeError: ApolloClient is not a constructor
    at Object.<anonymous> (/workspace/scratch/temp/test.js:3:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

Same happens with `import` syntax (via Webpack).

**Comment by tizmagik** [comment]
Using `.default` for the require statement gets it to work, which makes sense. But I'm not sure why the `import` syntax via Webpack doesn't work either.

**Comment by tizmagik** [comment]
```js
import { ApolloClient } from 'apollo-client';
```

That works. I'll use that for now. Feel free to close this.

**Comment by turadg** [comment]
@tizmagik this is definitely on your end, not the project. Please close this so the maintainers don't have to read through it.

**Comment by tizmagik** [comment]
@turadg thanks for your insight. While I'm sure it's something on my end, the Webpack configuration I'm using has been working with a number of other modules, so it might be the way this project is exported, actually. I wouldn't be so quick to dismiss that possibility.

Will close for now though as the workaround I've outlined above works fine.

**Comment by stubailo** [comment]
Are you using webpack 2? There was some other issue with it in #1213 

Default exports have definitely been a point of contention between different bundle systems so I wouldn't be surprised if things changed yet again.

**Comment by tizmagik** [comment]
@stubailo ah, yes I am using Webpack 2. Should I reopen this issue?

**Comment by stubailo** [comment]
Can you post a comment on #1213 with this additional info? The best help for us would be if someone could point us at a configured project using Webpack 2 so we can easily test out fixes.

**Comment by tizmagik** [comment]
Sure. I will try and stand up a sample repo and post that as well.
