### ISSUE TITLE
compatability issues with webpack 2.2 rc

### ISSUE THREAD

**Issue by GGAlanSmithee** [apollostack/apollo-client#1213]
After updating to the latest webpack version, I am getting some strange error messages;

```javascript
ERROR in ../~/apollo-client/transport/networkInterface.js
Module not found: Error: Can't resolve 'exports' in '/home/ubuntu/workspace/node_modules/apollo-client/transport'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'exports-loader' instead of 'exports'.
 @ ../~/apollo-client/transport/networkInterface.js 1:0-69
 @ ../~/apollo-client/index.js
 @ ./server.jsx

ERROR in ../~/apollo-client/transport/batchedNetworkInterface.js
Module not found: Error: Can't resolve 'exports' in '/home/ubuntu/workspace/node_modules/apollo-client/transport'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'exports-loader' instead of 'exports'.
 @ ../~/apollo-client/transport/batchedNetworkInterface.js 1:0-69
 @ ../~/apollo-client/index.js
 @ ./server.jsx
```

Since it's me as a user of webpack that is receiving this error, it should probably be fixed by me. But the fact that I am not using `exports-loader` and that no other module is giving me this error, there might be some incompatabilities with this library and webpack 2.

**Comment by stubailo** [comment]
Do you have a simple app with Webpack 2 we can try out? We haven't used it yet and it would be much easier if you could share your config.

**Comment by GGAlanSmithee** [comment]
Hi @stubailo Sorry I've been a bit short on time this weekend, but here is some more info:

The issue was introduced in [this webpac release](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.26) which makes sense, since webpack is no longer auto-prefixing loaders with `-loader`.

For the time being, I fixed it using the [resolveloader-moduleextensions](https://webpack.js.org/configuration/resolve/#resolveloader-moduleextensions) configuration.

**Comment by GGAlanSmithee** [comment]
There were another follow up error:

```javascript
TypeError: __WEBPACK_IMPORTED_MODULE_4_apollo_client_transport_networkInterface___default(...) is not a function
    at createApolloClient (/home/ubuntu/workspace/public/server.js:62331:107)
```

which was fixed by changing 

```javascript
import ApolloClient, {createNetworkInterface} from 'apollo-client'
```

to

```javascript
import ApolloClient from 'apollo-client'
import {createNetworkInterface} from 'apollo-client/transport/networkInterface'
```

Looking at https://github.com/apollostack/apollo-client/blob/master/src/ApolloClient.ts it does not re-export `createNetworkInterface`, is this by design? (it used to work AFAIK)

**Comment by stubailo** [comment]
The main module is index.ts not ApolloClient.ts AFAIK

**Comment by GGAlanSmithee** [comment]
Ah, sorry, my bad. That's weird then..

**Comment by calebmer** [comment]
@GGAlanSmithee I think this may be a problem with your Webpack configuration and not a problem with Apollo Client itself. If you could create a small reproduction repo that would really help us find and solve whatever is happening.

**Comment by GGAlanSmithee** [comment]
@calebmer yeah, it's most certainly a problem with my setup. I will try to get some time and set up a simple reproduction.

**Comment by calebmer** [comment]
Ok I’m going to close until then. Feel free to re-open or open a new issue @GGAlanSmithee if you find undesirable behavior in how Apollo is bundled with your reproduction 👍

**Comment by GGAlanSmithee** [comment]
Would just like to point out that this error has gone away for me since I restructured my webpack config. Unfortunatley, I can not point to any specific issue which caused this, but it does work now, without using `resolveLoader` or any other workaround.

**Comment by jacobk** [comment]
I had this same issue on a project based on [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate) and fixed it by changing the `webpack.base.babel.js` to:

```diff
   plugins: options.plugins.concat([
     new webpack.ProvidePlugin({
       // make fetch available
-      fetch: 'exports?self.fetch!whatwg-fetch',
+      fetch: 'exports-loader?self.fetch!whatwg-fetch',
     }),
```

**Comment by GGAlanSmithee** [comment]
@jacobk yeah, forgot to update this issue, but eventually, I also boiled it down to be a problem with the `fetch` injection. My solution was to remove `fetch` from `webpack.ProvidePlugin` and instead inject it explicitly on the server;

`import 'isomorphic-fetch'`

**Comment by RupenAnjaria** [comment]
I was able to fix this by upating webpack.config.js with below lines:

`          'Promise': 'es6-promise',
          'fetch':   'imports-loader?this=>global!exports-loader?global.fetch!whatwg-fetch'`

Note that we have added -loader after exports
