### ISSUE TITLE
Bug with __typename and values

### ISSUE THREAD

**Issue by poissont** [apollostack/apollo-client#1227]
Hello, I have an issue when I do a particular request, I have the espected result on graphiql, but there is a problem when I get the result on react-apollo.

Here is the **request** :
[Request.txt](https://github.com/apollostack/apollo-client/files/729793/Request.txt)

Expected **Result** : 
[Expected Result.txt](https://github.com/apollostack/apollo-client/files/729788/Espected.Result.txt)

However I get **this result** : 
[Apollo Result.txt](https://github.com/apollostack/apollo-client/files/729787/Apollo.Result.txt)

Some Lines3 are swapped into line2, and some line2 are swapped into complement or line3.

Any solution ? It drives me crazy

**Comment by calebmer** [comment]
What does your `dataIdFromObject` look like?

**Comment by poissont** [comment]
dataIdFromObject: r => r.id

**Comment by calebmer** [comment]
Yep, you will need to include the `__typename` as well. You have two objects with an id of `5`, but different type names. So Apollo thinks they are the same object. Try some variant on:

```js
dataIdFromObject: object => `${object.__typename}-${object.id}`
```

Let me know if you need any more help 👍

**Comment by poissont** [comment]
Well that didn't fixed my problem, with this i get 8 times the same object
[Apollo Result.txt](https://github.com/apollostack/apollo-client/files/731782/Apollo.Result.txt)

**Comment by ryannealmes** [comment]
This fixed my problem, but I am not understanding why the [documentation](http://dev.apollodata.com/react/cache-updates.html#normalization) is the way it is. If you look at the example in the docs

```javascript
import { ApolloClient } from 'react-apollo';
// If your database has unique IDs across all types of objects, you can use
// a very simple function!
const client = new ApolloClient({
  dataIdFromObject: o => o.id
});
```
Doesn't the example then override the default way the dataId is created? i.e. You would return ids without the `__typename` appended. I would have thought the documentation would include the example your are giving. The likelihood of having identical ids is extremely high if you used `dataIdFromObject: r => r.id`, why would the docs give that example? @calebmer

**Comment by ryannealmes** [comment]
After chatting on the apollo channel I see that the comment in the example says `unique IDs`. It's a little obscure. Might be good to draw attention to that a bit more. People using relational databases might not see it.

**Comment by jbinto** [comment]
@ryannealmes I think the salient point is "If your database has unique IDs across all types of objects". NoSQL dbs like Mongo tend to work this way, while relational DBs like Postgres tend to use non-globally unique keys.

**Comment by ryannealmes** [comment]
Ye, noticed the comment, could be helpful to draw a bit more attention to it. Anyway, my 2cents, hopefully this helps other people who glance over the comment!
