### ISSUE TITLE
Switch to Redux observable implementation

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#123]
https://github.com/reactjs/redux/pull/1632

Then maybe we won't need our own shim!

**Comment by arunoda** [comment]
You mean Rxjs?

**Comment by stubailo** [comment]
No, redux has built in observables now. I feel like Rxjs observables are way too heavy to be a standard part of the client, but we should make it possible to use them!

**Comment by arunoda** [comment]
Okay. We'll work on a simple wrapper for Rx.

**Comment by stubailo** [comment]
OK it turns out that using that won't help us at all, because the shim for observable is very simple. Closing in favor of #149 for RxJS.
