### ISSUE TITLE
Add basic guards to avoid firing observer unnecessarily

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#124]
For example, we don't need to recalculate all queries when a `QUERY_STOP` action happens, and this can be easily detected by `===` the `data` field.

**Comment by abhiaiyer91** [comment]
Unsure how to deal with this one. Is this in the reducer when next state is calculated? More info and I'm sure I can get it done.

**Comment by stubailo** [comment]
Assigned to myself to explain task better.

**Comment by stubailo** [comment]
Currently, [broadcastQueries](https://github.com/apollostack/apollo-client/blob/2ba9b95d1c9a83373ee6dcc0d17206bde6ab061c/src/QueryManager.ts#L428) is called every time there is a change in the Redux store.

This then iterates over all of the query listeners, and calls those ([defined here](https://github.com/apollostack/apollo-client/blob/2ba9b95d1c9a83373ee6dcc0d17206bde6ab061c/src/QueryManager.ts#L171)).

That [ends up calling](https://github.com/apollostack/apollo-client/blob/2ba9b95d1c9a83373ee6dcc0d17206bde6ab061c/src/QueryManager.ts#L189) `readSelectionSetFromStore` if certain conditions are met, like if there are no errors, and the query is not loading, etc.

That calls [observer.next](https://github.com/apollostack/apollo-client/blob/2ba9b95d1c9a83373ee6dcc0d17206bde6ab061c/src/QueryManager.ts#L198), even if the query result is the same as before, which could end up re-rendering react components, etc.

The end result is that _every time_ there is a Redux store change, we re-run `readSelectionSetFromStore` and re-fire the `next` on any observable subscribers currently active.

However, the actual query results change pretty rarely! For example, if `state.apollo === previousState.apollo`, then we shouldn't run anything at all. If `state.apollo.data === previousState.apollo.data`, then we don't need to update any query results that we have already sent, etc.

This task is about adding some simple equality checks in the process to avoid firing every single query observable on every store change.

**Comment by jbaxleyiii** [comment]
I added in checks like this on react-apollo. Id be happy to do something similar here!

**Comment by stubailo** [comment]
If we add them here, can we remove them in `react-apollo`? I'd love to centralize this kind of performance optimization rather than having every integration redo it from scratch.

**Comment by jbaxleyiii** [comment]
@stubailo we should be able to!

**Comment by abhiaiyer91** [comment]
```
hasQueryDataChanged 
hasMutationDataChanged
```
@jbaxleyiii 

It seems like this data in `react-apollo` is necessary to control other functions in `connect` via setting and unsetting its value (bool). I think the apollo store can just handle this above the React integration. That way no one will have to a write a lock in their own integrations?

**Comment by abhiaiyer91** [comment]
Solved in [#226](https://github.com/apollostack/apollo-client/pull/226)
