### ISSUE TITLE
Is there a way to remove middleware from networkInterface?

### ISSUE THREAD

**Issue by mzygmunt** [apollostack/apollo-client#1244]
Hello,
Is there a way to remove middleware from networkInterface, which I added by using networkInterface.use([])? I use this middleware to modifying http header, but I want to disable it on specified routes. Thanks for reply!

**Comment by helfer** [comment]
@mzygmunt no, you cannot remove middleware once it's been set. However, you can definitely write your middleware in such a way that it has no effect on certain routes.
