### ISSUE TITLE
API Condense

### ISSUE THREAD

**Issue by BrianRosamilia** [apollostack/apollo-client#135]
I was reading the documentation and had some comments for the methods :

* ApolloClient.query(options)
* ApolloClient.watchQuery(options)

I think these could be condensed into just 

ApolloClient.query(options) with a bit of work

In trying to think of the nicest cleanest way to come up with the API.  I came up with 

* Regular Read -> ApolloClient.query(options) 
* Reactive -> ApolloClient.query(options).changes             (or .subscribe, .feed whatever)

The main reason I'm guessing you didn't do this is because these methods return wildly different objects (Promise vs QueryObservable), but that isn't a huge obstacle.  You could use a deferred promise pattern like shown here : https://github.com/assaf/lazybird/blob/master/index.js (65 lines) which could be more efficient anyway (user never attaches handler?  Don't run the request).   

You'd also have to make it so that calling .changes passes through the query parameter from the Promise in order to create the QueryObservable--but modifying something like the lazybird source shouldn't be too difficult to add this.

I just thought it was interesting to think about/discuss, could reduce API surface area, documentation surface area (currently these two methods share most options), and remove a somewhat ugly 2-word term in the top level API :rocket: 

I'm guessing this isn't often discussed because people in promise land usually stay in promise land and observables are usually kept observables, but API design gets tricky when you are mixing the two.  I think this offers an interesting solution.

Thoughts?

**Comment by stubailo** [comment]
Fun fact: you can already do `ApolloClient#watchQuery(options).result().then(...)`.

In fact, this is exactly what `query` does under the hood: https://github.com/apollostack/apollo-client/blob/941f2b0e3c9e23e8b86ad4f9632c80793441de18/src/QueryManager.ts#L207-L213

However, I feel like it's cleaner to have two separate methods. They also might eventually take different options - for example some options like `returnPartialData` only make sense for reactive queries, and not one-off queries.

Either way, I suspect 90% of developers will be using the provided view layer integrations and not the core API directly, so perhaps it doesn't matter too much?

**Comment by BrianRosamilia** [comment]
Going from plain object to promise was never the hard part! :)

The hard part is having one method that is both a promise and has chainable method(s) to more than promsie methods AND not immediately executing the promise.

> They also might eventually take different options - for example some options like returnPartialData only make sense for reactive queries, and not one-off queries.

In my example, these would be options to the ApolloClient.query(options)**.changes**.  

The API would keep what's the same options with what's the same (queries) and reactive options would be parameters to .changes.

**Comment by stubailo** [comment]
> The hard part is having one method that returns both a promise that has chainable method(s) to more than promsie methods

I feel like returning an object that is both a promise and has some other methods on it is more confusing than just having two API methods.

Also, why is not executing the promise immediately good? Wouldn't you want to start the data fetch as soon as humanly possible?

**Comment by BrianRosamilia** [comment]
I might have done a bad job of explaining what lazybird does to a promise.  Read their docs https://github.com/assaf/lazybird and hopefully you'll see what I'm getting at

**Comment by stubailo** [comment]
Right, I guess I'm saying that if you call `query` and only call `then` like 10 seconds later, it would be great if the data was already there, rather than initiating the load only when `then` is called.

**Comment by jbaxleyiii** [comment]
@BrianRosamilia I agree with @stubailo on this one. I think that adding extra methods to promises gets really hairy to discern what is happening. For instance

```js

const query = client.query({ query: `...`, variables: { one: 1 }).then((data) => {})

vs

const query = client.query({ query: `...`, variables: { one: 1 }).subscribe().then((data) => {}) // wont work
```

the same method that returns different data and has different chaining methods seems more confusing than learning the two query options to me.

**Comment by BrianRosamilia** [comment]
Well, unless you never end up using the data because you branched to a block of code that never needed it in the first place.  

Expanding this debate into lazy vs eager evaluation will blow the lid off the scope of my suggestion :tongue:

**Comment by BrianRosamilia** [comment]
@jbaxleyiii calling .subscribe wouldn't return a promise, it would short circuit right into returning something similar to the QueryObservable as you wouldn't be using promises any longer.

Sorry, I should have included that in the original proposal.

**Comment by jbaxleyiii** [comment]
@BrianRosamilia yeah I think that is the problem to me ;)

The initial action of `client.query({ query: `...`, variables: { one: 1 })` has different chain methods depending on what is next. Sometimes `then, catch, etc` is supported, and sometime it isn't. I think it would be harder to discern with a glance which is which

**Comment by BrianRosamilia** [comment]
Okay yep that is a fair criticism!  :+1: 

But in your code example it was showing the reactive queries with .then which isn't what I meant.

**Comment by stubailo** [comment]
I'd say let's worry about this if we end up with a lot more API calls, but right now I'd say it's pretty minimalist. Another thing I would be concerned about is if people reported that they had trouble with the API.
