### ISSUE TITLE
Set up profiling and CI

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#136]
In order to have informed conversations about performance, we should do CPU profiling of stuff like inserting complex queries into the store, updating the store and rerunning queries, etc.

I'll start investigating some Node.js profiling tools that can help us measure this stuff.

Related to #128

**Comment by stubailo** [comment]
To do this, we probably need to collect more real world scenarios, and it might not be really worth it until we tackle some of the more low-hanging fruit. If we think about making serious changes to the implementation, we should ask for supporting data first, or set up the profiling then.

**Comment by helfer** [comment]
🍂 we can reopen if necessary
