### ISSUE TITLE
Create a local SWAPI to run tests against

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#14]
We should be able to basically cache all of the star wars API data and put it in a static JSON file and resolve requests against that directly.

**Comment by jbaxleyiii** [comment]
I can work on this over the next couple of days :+1:

**Comment by stubailo** [comment]
BTW @helfer is working on something that might make it really easy to mock a GraphQL server over the next few days. So let's talk about it in our call tomorrow!
