### ISSUE TITLE
Make it easy to use Apollo with Redux directly

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#142]
Continuing from: https://github.com/apollostack/react-apollo/issues/26

**Comment by stubailo** [comment]
@abhiaiyer91 assigned this to you! Let me know if I can help you get set up in any way.

**Comment by stubailo** [comment]
I think it would be prudent, if we document this interface, to make it clear that this is a more internal API, and possibly more likely to change. In the future, I think it would be great to make this stuff a separate NPM module that has internal utilities, and make the client library a nice wrapper around all of the reducers etc.

**Comment by smolinari** [comment]
:+1: ing this, because it might be similar to connecting apollo with Vuex and Vue, so I'd like to keep track of any progress.

https://github.com/vuejs/vuex

Scott
