### ISSUE TITLE
Does the Apollo-Client work on non Apollo GraphQL servers?

### ISSUE THREAD

**Issue by AdamBrodzinski** [apollostack/apollo-client#146]
I've been reading up on Apollo and am very impressed! I already have a GraphQL server running on a non-Node server and was wondering if it's going to be compatible with those? (Obviously some of the features wont work). The long polling and caching are the most interesting for my use case (on RN).

I checked out the [design.md](https://github.com/apollostack/apollo-client/blob/master/design.md) file but couldn't determine a clear answer.

**Comment by helfer** [comment]
Yes, one of our goals with apollo client is to be compatible with any spec compliant GraphQL server. There may be more advanced features we're going to build in the future that require implementing a slightly different spec on the server, but the basic features of Apollo client should always work with any GraphQL server.

**Comment by jbaxleyiii** [comment]
@AdamBrodzinski we are using it with a project that has a non apollo GraphQL and its working great!

**Comment by AdamBrodzinski** [comment]
Thanks for the fast feedback! Closing this out.

**Comment by smolinari** [comment]
@helfer - can you name a couple of examples of those advanced features?

Scott

**Comment by stubailo** [comment]
I think if we build features that depend on client/server cooperation, we'll have standalone specs/plugins for the server to add them, but they could include:

1. Login/auth management
2. Reactivity
3. More efficient transport

You could imagine more, but we're committed to making this client as generic as possible, so that anyone can use it!

**Comment by smolinari** [comment]
How about making a system that is fully and very easily extendable/ plug-in-able and let the rest of the dev community add to it as they wish?

Scott

**Comment by stubailo** [comment]
That's the goal! if there is something you can't plug into, I'd be happy to make it possible!

**Comment by smolinari** [comment]
https://github.com/apollostack/apollo-client/issues/143

:smile: 

Scott

**Comment by agasvina** [comment]
@jbaxleyiii is there any tutorial for Apollo client that has a non apollo GraphQL? Thanks before

**Comment by helfer** [comment]
@agasvina There is no such thing as Apollo GraphQL, what we're using is just plain GraphQL. You can therefore build any GraphQL server you like, following pretty much any tutorial out there, and it should work with apollo client. Even if the server is written in Scala, Python or whatever other language has a GraphQL server implementation
