### ISSUE TITLE
Query composition

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#148]
Tied in with https://github.com/apollostack/apollo-client/issues/80

Pinging @abhiaiyer91 who said he had some ideas and talked to @helfer

**Comment by stubailo** [comment]
Never mind - Abhi was talking about resolver composition. False alarm!

**Comment by stubailo** [comment]
To add more detail to this issue, this includes:

1. The ability to declare fragments on individual components
2. The ability to merge those fragments into one big query to reduce the number of roundtrips on first load
3. The ability to have per-fragment variables which are intelligently refetched a-la-Relay

This is important to be able to co-locate your data requirements with the components, without having a performance impact on your app's first load.

**Comment by batjko** [comment]
Would this include some abstraction from the GraphQL String notation? I mean I'm not sure I'd want a full-blown ORM here, and perhaps a simple String is still the most efficient way, but if we're just talking about small fragments, that then need to be composed in some way, I wonder if an Object-based API might be better here?

**Comment by stubailo** [comment]
> Would this include some abstraction from the GraphQL String notation?

I feel like GraphQL query strings are the best part of the whole system, but perhaps it would be a good idea? What would be the benefit of an abstraction other than fragment strings?

**Comment by batjko** [comment]
I'm thinking of scenarios where one would want to dynamically create these fragments from a bunch of options at runtime. Yes, we could just use string interpolation, and perhaps that's best and I'm thinking too traditionally, here.

**Comment by stubailo** [comment]
Oh that's what the skip and include directives are for! I think the best practice is to never use string interpolation on queries, which would be pretty easy to check with a longer.

**Comment by stubailo** [comment]
*linter

**Comment by jbaxleyiii** [comment]
I thinking keeping Apollo 100% graphql spec for query formation (aka just strings) is the best move. It reduces the barrier to entry to the project and we can help mlve the spec forward if / when needed

**Comment by batjko** [comment]
> that's what the skip and include directives are for

Yes, I suppose. That would work for me. However, the approach assumes a lot of knowledge of GraphQL syntax. I know developer friendliness will be tackled later, but providing an API for these things might help those who are new to the GQL spec and just want to make use of Apollo's reactive data etc.
Just a thought.

**Comment by smolinari** [comment]
Although I have little to say here, I would also put forward a :+1: to sticking to the specs.

Scott

**Comment by stubailo** [comment]
Personally I feel like skip and include aren't much harder than string interpolation with an if statement, plus we can more easily do query validation if there isn't interpolation everywhere.

**Comment by batjko** [comment]
@stubailo Yes, fair point.
I really have no preference here, just wondering about best practices. Happy to jump on board.

**Comment by tlvenn** [comment]
Is there any update / timeline / milestone for that feature ? This is one of the strong point of Relay, should Apollo Client be able to provide query composition, I expect it will be a huge help to increase adoption.

**Comment by stubailo** [comment]
@tlvenn Dhaivat is working on it next week!

**Comment by tlvenn** [comment]
That's great news, thanks for the update !

**Comment by Poincare** [comment]
This was merged some time ago with `createFragment`. We can close this issue at this point, probably.
