### ISSUE TITLE
Client design discussion thread

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#15]
I think the idea I'm tending towards is that the core client just has a registered set of queries that the UI is interested in. Any query aggregation from the UI would be built on top of this. Each query is an event emitter, so that every query consumer can get notified about changes in that query. Here's a crappy diagram:

![slack for ios upload](https://cloud.githubusercontent.com/assets/448783/13941807/afe798c8-efa8-11e5-824f-2fba4019aa0e.jpg)

Going to make a better diagram later, heading home now.

**Comment by mquandalle** [comment]
(maybe you would like to try https://www.draw.io, if you don’t know it already :))

**Comment by stubailo** [comment]
@mquandalle @jbaxleyiii question:

Right now, we have a QueryManager that keeps track of a list of queries, associated callbacks, etc. Should this data live in Redux as well? It might be useful to keep track of actions such as "add query to the list", "error on query", etc.

**Comment by jbaxleyiii** [comment]
@stubailo the callbacks would be possible but kinda against the plain state ideals of a redux store. Although you can store rich objects, ideally the store is serializable. Otherwise I'm all for QueryManager keeping things in redux. Keeping track / being able to report on query actions would be great!

**Comment by stubailo** [comment]
@jbaxleyiii I was thinking Redux would just store queries by ID:

```
{
  1: ...query AST here...
}
```

And anyone who wanted to get the query out of the store, or have a callback to its data, would reference it by ID.

So you could say "give me a callback for data on query 1" and the query itself can be serialized, refetched whenever necessary, etc.

**Comment by jbaxleyiii** [comment]
@stubailo that makes sense! Thanks for the clarification!

**Comment by stubailo** [comment]
Given the index.js is merged, I think all of this is now in the code.
