### ISSUE TITLE
Replace SWAPI tests with a simpler mocked API

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#150]
So that they run fast and we are in control of our tests more rather than relying on a very complex codebase.

Ideally, dogfood the GraphQL-Tools mocking functionality.

**Comment by helfer** [comment]
@abhiaiyer91 any progress on this?

**Comment by abhiaiyer91** [comment]
haven't started !

**Comment by stubailo** [comment]
I'd say maybe unassign yourself if you're not actively working on something! that way someone else might pick it up.

**Comment by Poincare** [comment]
@stubailo Does this mean that we want to mock the entire SWAPI schema using GraphQL tools?

**Comment by stubailo** [comment]
Now that I think of it, we could probably just save mocked JSON blobs and use them with a mocked `fetch` or something.
