### ISSUE TITLE
Some GraphQL servers return an empty error array, even though it's not spec compliant

### ISSUE THREAD

**Issue by WilliamHolmes** [apollostack/apollo-client#156]
Our GraphQL schema QueryRoot contains a type Viewer which we use to query most of the data.
Apollo doesn't seem to like this causing the error
`Can't find field viewer on object [object Object]`
I have validated (and verified the response) with this simple query using GraphiQL
**Query**
`{
  viewer {
    me {
      displayName
    }
  }
}`
**Response**
`{
  "data": {
    "viewer": {
      "me": {
        "displayName": "William Holmes"
      }
    }
  },
  "errors": []
}`

REF: apollostack/apollo-client/src/networkInterface.ts#L91

I'm using React Integration with mapQueriesToProps and connect

`export default connect({ mapQueriesToProps })(MyComponent);`

**Comment by stubailo** [comment]
I'll take a look soon, thanks for reporting!

**Comment by WilliamHolmes** [comment]
Thanks @stubailo
Let me know if you need more info.
I don't think I'm doing anything out of the ordinary, I've followed the docs and added the apollo reducer & middleware to the redux store (and I do see it in the redux dev tools)

I really do like the approach you guys are taking with this apollo-client, I'm looking forward to integrated it. :smile:

**Comment by abhiaiyer91** [comment]
Could we get a code sample of the react component too?

**Comment by jbaxleyiii** [comment]
@WilliamHolmes what version of react-apollo are you using, this sounds like it may be an issue with the connect component

**Comment by WilliamHolmes** [comment]
@jbaxleyiii 

"apollo-client": "0.1.6",
"react": "0.14.3",
"react-apollo": "0.1.6",
"redux": "3.0.4",

hmm. I have a feeling your about to tell me to update my react components. :smile:

**Comment by jbaxleyiii** [comment]
@WilliamHolmes maybe! It depends on how you are accessing the data from apollo-react (if that is what is causing the error)

v0.1.*
```
{
  loading: bool,
  result: {
    viewer: {}
  },
}
```

v0.2.*
```
{
  loading: bool,
  viewer: {}
}
````

**Comment by stubailo** [comment]
@WilliamHolmes any updates? really curious to hear what is going on.

**Comment by WilliamHolmes** [comment]
@stubailo I was out for a few day, will try to update and test again.
@jbaxleyiii Right now I'm just logging out this.props and checking the console, so this shouldn't be an issue.
@abhiaiyer91 I'll trim back my React Comp and upload today for review. Thanks.

**Comment by WilliamHolmes** [comment]
@stubailo I've tried to reduce the code down to the basic modules (still having the same issue)
[My Git Repo](https://github.com/WilliamHolmes/Apollo_Client_Test)
You will need to edit /src/index.js to point to your own GraphQL server.

**Comment by abhiaiyer91** [comment]
Where's your schema and resolvers?

**Comment by WilliamHolmes** [comment]
@abhiaiyer91 I can't include our schema, but you can change the query in [App.js](https://github.com/WilliamHolmes/Apollo_Client_Test/blob/master/src/App.js) to suit whatever schema your GraphQL server is using.

I've already verified locally that the Posted query and server response is what is expected.

**Comment by WilliamHolmes** [comment]
So it turns out if the response has an error attribute in the root, even if the array is empty we see get this issue.
If there is no error attribute in the root everything seems to be working.

I believe an error attribute with an empty array is a supported GraphQL response.

**Comment by WilliamHolmes** [comment]
It's the `errors:[]` attribute.
{"data":{"node":{"updated":"2016-04-26T09:18:09.023+0000"}},"**errors**":[]}

If it's not present (in the root) then everything works as expected, otherwise when its present we see this issue.

I believe the errors attribute (even if it's an empty array) is a valid GraphQL response.

**Comment by stubailo** [comment]
Ooooooooooh! Thank you for identifying this. Seems related to #51 

@WilliamHolmes what GraphQL server are you using?

It's a bummer but GraphQL doesn't really have enough guidelines for errors to treat them in a sane way....

**Comment by WilliamHolmes** [comment]
@stubailo It's [graphql-java](https://github.com/andimarek/graphql-java)

**Comment by stubailo** [comment]
@WilliamHolmes on a scale of 1 to 10, how sure are you that the empty error array is the underlying problem? As in, should I rename this issue, or open a new one?

**Comment by WilliamHolmes** [comment]
I'll commit at 10.
I've tested this with (not working) and without (working) the **errors** attribute.
I did not, however, test it with something other than an array, but I'm going to assume that would never happen. :smile:

**Comment by stubailo** [comment]
@WilliamHolmes thanks for the confidence! Should be a trivial fix.

**Comment by helfer** [comment]
@WilliamHolmes I think you should file an issue on graphql-java. The [GraphQL spec](https://facebook.github.io/graphql/#sec-Errors) says:

> The errors entry in the response is a non‐empty list of errors, where each error is a map.

> If no errors were encountered during the requested operation, the errors entry should not be present in the result.

**Comment by stubailo** [comment]
#lawyered

**Comment by WilliamHolmes** [comment]
@helfer @stubailo 
1. Excellent News. I'll get on to the GraphQL server guys.
2. Thanks so much for investigating this.
Unless you want to add some robustness, I'm happy for you to close this issue.

**Comment by mquandalle** [comment]
Maybe this client could provide a more comprehensible error message?

**Comment by stubailo** [comment]
Yeah this is definitely still a "bug" in my mind! But now we have a specific cause isolated.

**Comment by stubailo** [comment]
Fixing some of the internal error messages would be nice though so that these are easier to identify...
