### ISSUE TITLE
Plans for Blaze/Tracker integration.

### ISSUE THREAD

**Issue by praneybehl** [apollostack/apollo-client#159]
Hi,

As suggested in the Meteor night I'd like to suggest integration for Blaze/Tracker. I also hope I am not the only one go want Blaze integration Apollo.

I would like to help as much as I could but unfortunately, my JS skills are a bit limited.

Praney

**Comment by stubailo** [comment]
I think we would need someone who plans to use it in production to lead development. If we find that person I would be happy to help!

**Comment by praneybehl** [comment]
Thanks @stubailo , 
It seems like Blaze is not going to be anytime sooner and eventually going to just fade away with time, maybe it's time to migrate to another framework, even though I am familiar with React and quite like it, I can not use it in my current app due to limitations caused due to the Virtual DOM so probably going to try Angular2. I've always tried to stay away from Angular, but it's time to face my demons.

If I am not wrong ApolloStack already has an integration with Angular 2 isn't it?

**Comment by stubailo** [comment]
Yes it does! I'm curious what limitations of virtual Dom you ran into?

**Comment by praneybehl** [comment]
My app use Greensock's js animation library very intensely to create and manage animations and that involves a lot of DOM manipulation which React doesn't quite agree with. So I gave it a spin but lots of errors and debuging was required. That was my main purpose to stick with Blaze in the first place. I have really enjoyed using and working with Blaze and it's a shame to see it go but hey, as they say, every good thing must come to an end.

I just started with a course at Pluralsight last night "Angular 2: Getting Started" and very surprising really loving the way Angular2 is designed. Hopefully everything will work and I'll soon start the transition to Angular2.

Cheers!

**Comment by stubailo** [comment]
Sounds great! Would be awesome to get some feedback about the angular 2 integration. Closing this for now.

**Comment by smolinari** [comment]
@praneybehl - Have you seen or tried out Vue.js? http://vuejs.org/

They are working on 2.0 right now and it is supposed to be even more performant. 

Scott

**Comment by praneybehl** [comment]
@stubailo thanks mate, will sure do.

@smolinari Thanks for the suggestion, yes I have played around with Vue.js in the past, but to be frank its a bit tricky when using open-source software especially when using a smaller/low traction one, as their future is uncertain. Unless you have a skill and time to be able to pick them up if they are for some reason abandoned, IMHO there is not much sense investing your time in them. 

At this point of time in the land of front-end frameworks there are 2 top contenders which are here to stay - Angular.js (Backed by Google) and React.js(Backed by Facebook). There are both used, developed and supported by 2 of the world's biggest corporations so you can't really go wrong. Why do you think Meteor decided to make them first class citizens and abandon their own Blaze. On top of all the tool that is available for these two is amazing. Let alone finding developers for these frameworks are a lot easier than Blaze, or Vue or Riot and some xyz...

This is just what I feel about the current JavaScript World fatigue.
I am sorry if it sounds like a rant, not my intention but I am done trying new software now, as mentioned above really enjoying learning Angular2 and nearly done with the course will then check out Meteor integration docs and give it a spin.

I wish you well with Vue.js 
cheers :)

**Comment by smolinari** [comment]
Vue actually has more traction than Aurelia. Vue is also backed indirectly by Alibaba through Weex (a mobile development framework based on Vue and soon to be made public) and Evan You, the creator of Vue, has said he intends to create a company around Vue. Not sure if that will satisfy your need for guaranteed support though. 

And to be honest, today React or Angular can be backed by Facebook or Google, and tomorrow they might drop it for some other newfound way to do things. They have the resources to make those decisions, unfortunately. Still, the chances of that happening are just as small (or large) as support for Vue getting dropped. That is because Vue has a fairly large and growing community and a lot of fans, including me. :smile: 

Scott

**Comment by praneybehl** [comment]
I guess its an open ended discussion and will never end, we'll lead nowhere with it so good luck with Vue.js cheers!

**Comment by smolinari** [comment]
Nope, no open ended discussion. Since it is clear you are not interested in Vue, that is the end of the discussion. :smile:

Scott

**Comment by smolinari** [comment]
@praneybehl - This still might be of interest to you. 

http://jsfiddle.net/azimuth/tofnsu5e/4/

Scott
