### ISSUE TITLE
Make it possible to import small modules of the library independently

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#166]
If we want to ship extra modules, like query diffing, that aren't always included, there are only two ways I know to make that work with today's bundlers:

1. Ship every part as a separate NPM package: `import diffQueries from 'apollo-diff-queries';`
2. Ship multiple files in the NPM package: `import diffQueries from 'apollo-client/diff-queries';`

I currently prefer the second because it will make testing and version management much easier, plus it doesn't require people to install a bunch of packages. But to do it we have to move the files before publish to put them in the right place (they have to be in the root of the published package I think).

I'm happy to implement this so that we can start cracking on some of the stuff in: https://github.com/apollostack/apollo-client/issues/157#issuecomment-216401284

Looking for feedback from @jbaxleyiii, the tooling and publishing mastermind.

**Comment by jbaxleyiii** [comment]
I can put together an easy way to do this on publish! And get filesizes of each independent add-on for fun

**Comment by stubailo** [comment]
whooooooa!

Sounds good to me :]

Projected timeline?

**Comment by jbaxleyiii** [comment]
I can get adding files from /src to the root tonight! The rest this week?

**Comment by stubailo** [comment]
Sounds great!

I'll just add stuff in `src` then and assume it will be importable eventually.

**Comment by stubailo** [comment]
I think this is done since `import gql from 'apollo-client/gql'` works great!
