### ISSUE TITLE
Inconsistent state in mapMutationsToProps

### ISSUE THREAD

**Issue by deoqc** [apollostack/apollo-client#170]
I am using redux-form and have 2 forms (lets say FormA and FormB, 'living' in `state.form.FormA` and `state.form.FormB`). 

The problem is that `FormB` is not always showing in the state when using `mapMutationsToProps`, but it is correct in `mapStateToProps` or in the store (as shown by devtools).

---

To be more precise, my code is something like this:
```Javascript
const mapMutationsToProps = ({ state }) => ({
  onMutation: () => ({
    mutation: `
      mutation myAwesomeMutation (
        $formKeys: String!
      ) {
        awesomeMutation( 
          formKeys: $formKeys
        ) {
          passThroughtInput
        }
      }
    `,
    variables: {
      formKeys: JSON.stringify(Object.keys(state.form)),
    },
  })
});
```
and the mutation only returns the same input (`passThroughtInput === formKeys`)

To check, I also have the following:
```Javascript
const mapStateToProps = (state) => ({
  formKeys: JSON.stringify(Object.keys(state.form)),
});
```

The callback to the `onMutation` prints the results on console, and the `formKeys` is in a `Text` tag on screen, and also using devtools (so I compare the 3).

As said before, mapStateToProps and store devtools are correct. Mutation is missing (at least most of the time) the state.FormB key (but showing state.FormA).

If you guys don't have any clues, I can try to do a reproducible repo.

**Comment by stubailo** [comment]
Moved to https://github.com/apollostack/react-apollo/issues/41
