### ISSUE TITLE
Unable to query into non-Apollo GraphQL server from Apollo-client

### ISSUE THREAD

**Issue by agasvina** [apollostack/apollo-client#177]
I tried to make a simple request by following the documentation using Apollo Client into non-Apollo GraphQL server as below:
```
import ApolloClient, { createNetworkInterface } from 'apollo-client';

// Register gql globally
import { registerGqlTag } from 'apollo-client/gql';
registerGqlTag();

const networkInterface = createNetworkInterface(' http://localhost:8080/graphql', {
  headers: {
  'Content-type': "application/json"
  }
});

var client = new ApolloClient({
  networkInterface
});

client.query({
  query: gql`
    query getTodo($todoId: Int!) {
      node(id: $todoId) {
        ... on Todo {
          id
          text
        }
      }
    }
  `,
  variables: {
    todoId: "todo:100000",
  },
  forceFetch: false,
}).then((graphQLResult) => {
  var errors  = graphQLResult.errors;
  var data = graphQLResult.data;

  if (data) {
    console.log('got data', data);
  }

  if (errors) {
    console.log('got some GraphQL execution errors', errors);
  }
}).catch((error) => {
  console.log('there was an error sending the query', error);
});
```
However I keep getting an error while running the code: 
```there was an error sending the query [ReferenceError: fetch is not defined]```

I try to search the issue related to that, however the documentation doesn't really helpful.

Thanks before.

**Comment by jbaxleyiii** [comment]
@agasvina are you running this query in a browser on using node? If a browser, which one are you using?

`fetch` is a way to make remote calls in browser and is supported in most major vendors. To run it in node, you need to include `node-fetch` and attach `fetch` to node's global object `global.fetch = fetch`.

I agree we could make the docs clearer on this part. I'll work on that

**Comment by agasvina** [comment]
@jbaxleyiii  it works!
Thanks for the swift reply.
I'll close the issue.

**Comment by hems** [comment]
oh glad i found this!

**Comment by stubailo** [comment]
Mind sending a PR to the setup docs to mention that a `fetch` polyfill is necessary on Node?
