### ISSUE TITLE
forceFetch not working

### ISSUE THREAD

**Issue by deoqc** [apollostack/apollo-client#182]
I need a view to always get fresh data. But using `forceFetch` only fires `QUERY_RESULT` (which I think is for fetching data on server), and all the following times fires `QUERY_RESULT_CLIENT`(for getting the result in client store, as I think).

Therefore my view is not correctly updated when the data changes.

**update:** I'm using `react-apollo` for `connect`ing but thought it may be an issue in `apollo-client`

**Comment by stubailo** [comment]
That definitely should work!

**Comment by deoqc** [comment]
I updated to `apollo-client@0.3.4` and `react-apollo@0.3.3` and now it's working.

**Comment by stubailo** [comment]
Glad to hear it :]
