### ISSUE TITLE
Cannot find module `apollo-client/gql`

### ISSUE THREAD

**Issue by goje87** [apollostack/apollo-client#186]
I have below script that was running until now.

    //script.js
    var apollo = require('apollo-client');
    var gql = require('apollo-client/gql');
    ...

`$ node script.js` was working fine till now.

All I did was updated `apollo-client` from `^0.1.6` to `^0.3.3`. Post that I get below error whenever I run above command.

    Error: Cannot find module 'apollo-client/gql' from '/path/to/script'

I then rolled back `apollo-client` to `^0.1.6`. But, the error seems to continue. What could I be doing wrong?

**Comment by wangyueming** [comment]
I changed the line to require('apollo-client/npm/gql'), and it worked. I don't know why.

**Comment by stubailo** [comment]
Hey, really sorry - I published the last version of the package incorrectly. Should be good now and you can remove the `npm` from the path in `0.3.4`.

**Comment by stubailo** [comment]
Basically, we have a script that copies the modules to the right place before publishing, and I forgot to call it, which broke the file paths...

**Comment by goje87** [comment]
Thanks @stubailo... `0.3.4` works like charm!!

But, it's strange that even when I rolled back to `0.1.6` it didn't work...

**Comment by stubailo** [comment]
0.1.6 didn't have gql at all, so that's not strange :) check the changelog for a history of when stuff was added and changed.

**Comment by goje87** [comment]
My bad!! I forgot that I did `npm install` of 0.3.2 without `--save`. Looking at `package.json` I thought I was just hopping between 0.1.6 n 0.3.3... Sorry about the confusion!
