### ISSUE TITLE
Redux and GraphQL?

### ISSUE THREAD

**Issue by czbaker** [apollostack/apollo-client#187]
So...I'm really new to GraphQL and I'm still trying to figure out a lot of things.

Say I have a Redux state variable that's contained in 'state.general.currentISBN', and it contains a string that I want to use as a parameter for a GraphQL query in a React component.

How do I handle the entry in `mapQueriesToProps` and "build" the query with the Redux state?

I'm sort of lost, and the docs don't seem to mention it very well.   Any help would be greatly appreciated.

**Comment by stubailo** [comment]
We talked about this in Slack, but you should be able to use `state` in `mapQueriesToProps`:

```js
function mapQueriesToProps({ ownProps, state }) {
  return {
    category: {
      query: gql`
        query getCategory($categoryId: Int!) {
          category(id: $categoryId) {
            name
            color
          }
        }
      `,
      variables: {
        categoryId: state.selectedCategoryId,
      },
      forceFetch: false,
      returnPartialData: true,
    },
  };
};
```

Where `state.selectedCategoryId` is coming from Redux.

**Comment by czbaker** [comment]
Yeah, I posted this issue before hopping on there, and now I realize what was wrong.  Thank you again for being so helpful on Slack.  I also feel stupid for not realizing that I hadn't `connect()`ed my Redux state to the component in question, so `{ state }` didn't exist.
