### ISSUE TITLE
Suggest using variables instead of inline enum arguments

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#202]
Much easier than implementing #183, and using variables isn't that hard.

**Comment by ramsaylanier** [comment]
+1 this would be huge for me.

**Comment by stubailo** [comment]
What do you mean? Variables are already supported, this issue was just about printing a nicer warning when enuks are used inline.

**Comment by ramsaylanier** [comment]
Whoops - I think I commented on the wrong issue. The perils of githubbing on a phone.

**Comment by stubailo** [comment]
@ramsaylanier hope you find the right thread :]
