### ISSUE TITLE
Make master a protected branch

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#206]
So that we can't accidentally push there

**Comment by jbaxleyiii** [comment]
Done!

**Comment by stubailo** [comment]
Amazing!

**Comment by MasterJames** [comment]
It's wise to make it clear what branch should be forked for PRs somewhere README? submission guide with signature required forms or what have you. Otherwise you constantly have to remind people "can you please target the development branch". I notice a please sign form bot so maybe a bot to notify people if they send a PR to master what to do would save time?

**Comment by stubailo** [comment]
@MasterJames nono, I think we're talking about something different. People can still open PRs against the default branch. This is just so that repo contributors can't directly commit to master without opening a PR.

**Comment by smolinari** [comment]
Are you following a [gitflow workflow](http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/)? It doesn't look like you are (as there is no develop branch) I think that is what @MasterJames is talking about. If you were using gitflow, you'd need to tell people in the contribution docs to branch off of the develop branch for new features or bug fixes and to PR on the develop branch only too. 

Scott

**Comment by stubailo** [comment]
Yeah, I don't think we need a devel branch - we should just release features as soon as they are developed I think.

**Comment by smolinari** [comment]
Yup. That is fine for smallish kind of projects. However, managing the repo and releases can get unwieldy as the project gets bigger (should it get bigger). I bet you already knew that though. :smile: 

Scott

**Comment by stubailo** [comment]
Yeah, I think my goal is to never let this project get big. If we need more stuff in Apollo Client, we should add plugin functionality, start a new repo/package and put it there instead. Maybe that's not feasible, but it sounds like a better solution than having a complex process with special branch names, commit tags, release process, etc.

Anyway, we'll cross that bridge when we get there!
