### ISSUE TITLE
Rename Apollo Redux actions to be namespaced

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#210]
Right now our actions are called stuff like `QUERY_RESULT`, etc. That might result in a collision with actions someone might already have in their app. We might want to namespace our actions with a prefix that contains the name `APOLLO`, which will make collisions basically impossible.

**Comment by stubailo** [comment]
We might want to loop this in with a different breaking change since it doesn't seem to be worth a minor version bump on its own.

**Comment by johnthepink** [comment]
I totally agree. We should namespace.

**Comment by abhiaiyer91** [comment]
`APOLLO_*` sounds good?

**Comment by stubailo** [comment]
Guess we're going with `APOLLO_`!

**Comment by abhiaiyer91** [comment]
ALRIGHT, assign to me? I got you

**Comment by MasterJames** [comment]
Is a global APOLLO with things like APOLLO.* worth consideration? 
I thought if you import apollo it's done this way for you.
Sorry and disregard if junior question.

**Comment by abhiaiyer91** [comment]
These action types aren't really for consumers. They're part of the internal api for the client.

**Comment by stubailo** [comment]
@MasterJames this is about namespacing Redux action types, which are just strings, and don't have a standard namespacing schemes.

**Comment by stubailo** [comment]
@abhiaiyer91 do you think we should consider this a breaking change? We didn't really document the action names before, so maybe it isn't? Hard to say.

**Comment by abhiaiyer91** [comment]
Its not breaking to any users. Unless people are relying on these action types in their apps? @jbaxleyiii do you guys?

**Comment by stubailo** [comment]
Yeah if they don't then it's probably fine

**Comment by jbaxleyiii** [comment]
@stubailo @abhiaiyer91 we don't!

**Comment by stubailo** [comment]
Alright abhi go for it!

**Comment by MasterJames** [comment]
Food for thought but probably not related enough to reconsider dotting at least.
https://github.com/reactjs/redux/issues/786
Call me old fashioned but I would just use a dictionary in an apollo global namespace for action strings if not the vales themselves directly. Maybe if it was a subscription the server could provide the variation desired and discussed in the thread. Object merge overwriting raw js is also is a kind of hotcode logic I've been exploring lately but I guess it's not directly related here either.
Thanks for listening between the lines and thinking beyond the limits of convention.

**Comment by abhiaiyer91** [comment]
Done!

**Comment by stubailo** [comment]
Thanks @abhiaiyer91! Great work.
