### ISSUE TITLE
Investigate compat with old Android browsers

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#212]
Reported here: https://forums.meteor.com/t/apollo-not-working-in-most-android-devices-browser/23050

**Comment by timbotnik** [comment]
This is probably b/c support for native fetch is not added in Android browser until v5.  Note this is also an issue in current Safari & iOS Safari.  Perhaps we should make [this part of the docs](http://docs.apollostack.com/apollo-client/core.html#fetch-polyfill) slightly more prominent, or include a `fetch` polyfill by default.

**Comment by helfer** [comment]
@timbotnik @stubailo has this been resolved?

**Comment by stubailo** [comment]
My understanding is we now include a fetch poky fill by default? I don't know how to verify that this is fixed.

**Comment by timbotnik** [comment]
@stubailo  I believe https://github.com/apollostack/apollo-client/blob/master/package.json#L63 means we are including fetch polyfill by default.  Should be easily testable by using a vanilla apollo-client web app the (previously) unsupported browsers.

**Comment by johnthepink** [comment]
@stubailo @timbotnik Just tested using the [project](https://github.com/abhiaiyer91/meteor-apollo-counter) from the forum post on Android 4.1.1 and 4.4.4. Looks like `whatwg-fetch` is there, and seems to be working fine!

## 4.1.1

![xjzhpr3n4i](https://cloud.githubusercontent.com/assets/816517/17916125/531206f6-697e-11e6-9fde-c4173f4e0f94.gif)

## 4.4.4

![fg2yxehepa](https://cloud.githubusercontent.com/assets/816517/17916129/634e56aa-697e-11e6-8058-746645ab34a2.gif)

**Comment by helfer** [comment]
Closing for now since this seems to work. If anyone has an issue, please feel free to reopen.
