### ISSUE TITLE
Decide on a more elegant solution to make `gql` work with npm link

### ISSUE THREAD

**Issue by abhiaiyer91** [apollostack/apollo-client#223]
To fix the current `npm-link` issue, where the module `apollo-client/gql` cannot be found, we will place `gql.js` in the root of the repo and redirect it to `lib/src/`gql.js`.

After a deep discussion about separate modules or not, we decided to go ahead with the current strategy while we think of something better to do. 

This is that issue.

**Comment by dahjelle** [comment]
I also ran into the same issue when importing from `writeToStore` and `readFromStore` in relation to #180. Hopefully not nearly as important long-term as `gql`, but I thought it worth mentioning anyway.

**Comment by abhiaiyer91** [comment]
@stubailo when do you think we can get the hacky version in. Again if you just wanna write down what you want down, im sure we can do it

**Comment by abhiaiyer91** [comment]
PR [#243](https://github.com/apollostack/apollo-client/pull/243) will place gql in root. Circle back later for elegant fix
