### ISSUE TITLE
Add lint rule to disallow unused arguments

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#229]
Just like we disallow unused variables.

**Comment by WilliamHolmes** [comment]
Sometimes it's good to leave unused arguments in the function signature to help with API docs.
You could add an exception to the lint rule for unused variables ending with __
ie. `someFunction(var1, var2__)`

**Comment by stubailo** [comment]
> Sometimes it's good to leave unused arguments in the function signature to help with API docs.

Can you give an example of what you're talking about?
