### ISSUE TITLE
Make query augmentation pluggable

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#230]
We've started implementing `__typename`, but one should be able to plug in any fields they need.

Matches this diagram: http://docs.apollostack.com/apollo-client/how-it-works.html#minimize

**Comment by Poincare** [comment]
Fixed?

**Comment by stubailo** [comment]
I need to ship a release with this, then we need to add to the docs

**Comment by stubailo** [comment]
OK shipped in 0.3.11.
