### ISSUE TITLE
Polling queries stop if you call refetch() on them

### ISSUE THREAD

**Issue by ciwolsey** [apollostack/apollo-client#239]
I noticed that if I set a pollInterval on a query, but also try to refresh it manually by calling refetch(), the polling is stopped.

**Comment by stubailo** [comment]
Thanks for reporting an issue! If you want to help us fix the bug, the next step would be to submit a PR with a failing test for the issue. It seems like it should go into the tests for `QueryManager`.

**Comment by javascriptlove** [comment]
Is this going to be in next version (0.3.14)?

**Comment by stubailo** [comment]
Yes!

**Comment by stubailo** [comment]
This should be fixed now.
