### ISSUE TITLE
Remove token management middleware?

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#247]
I'm not sure that having a token store built into Apollo Client is useful. I'm referring to this class: https://github.com/apollostack/apollo-client/blob/e8f22bd4b085637360eccb4745951987b11f0d2f/src/middleware.ts#L12

Just a sanity check here:

1. In Meteor, you would get the token from Meteor directly
2. When using cookies, you just store it in the browser
3. Even when using custom tokens, you would want to cache them in local storage

Is the built in token storage thing that ships as part of the network interface useful? 

Are you using it @jbaxleyiii @johnthepink?

**Comment by johnthepink** [comment]
@stubailo you're right. It's not really that useful. It made sense with the initial way we intended to do our implementation. But I'm great with removing it now.

**Comment by stubailo** [comment]
Sounds good - should be an easy issue to pick up for anyone interested!

**Comment by abhiaiyer91** [comment]
[PR #254](https://github.com/apollostack/apollo-client/pull/254_

**Comment by Poincare** [comment]
I think it is safe to close since the changes have been merged.
