### ISSUE TITLE
Pluralize a query

### ISSUE THREAD

**Issue by deoqc** [apollostack/apollo-client#249]
I have a entry point `node($id: ID!)`. But I wanted to query multiple single nodes with a array of id's.

Is there a way to do it without having to define another entry point `nodes`, I believe similar to `@relay(plural: true)` Relay directive (but not sure, never used).

**Comment by stubailo** [comment]
Hmm, we don't have anything like that at the moment - are you sure that's what the Relay directive does?

It seems it would be much better to just define another entry point, rather than faking it on the client.

**Comment by deoqc** [comment]
Just found [this](http://facebook.github.io/relay/graphql/objectidentification.htm#sec-Fields) that made me thought it had to be implemented on server anyways, but I think it's similar to what I said (see [here](https://github.com/facebook/relay/issues/107#issuecomment-132290280)).

I'm going to work around this and don't have any strong opinion, so its ok to close the issue for me.

**Comment by stubailo** [comment]
For the record, Apollo client doesn't make any such assumptions about root fields!
