### ISSUE TITLE
Optimistically batch requests

### ISSUE THREAD

**Issue by jbaxleyiii** [apollostack/apollo-client#25]
In many applications, there are a number of ways that data is requested. Lets take a moderately complex react app as the example. In this case, the app has SSR (server side rendering), a single UI tree, a centralized application state (using redux), and has the need to prefetch application data that isn't UI dependent.

**Using a direct 1:1 query/operation:request**
* On the server, this app currently renders on the `page` level component that the router specifies. This is common in react-router apps that allow for a `static fetchData` which returns a promise. This means our page level component would have to handle all data for all of its children, making it inefficient on the client and not super DRY. Subcomponents with data needs will be rendered without data on the server. If all background processes are run on the server (sometimes true, sometimes not) more requests could happen
* On the client the app will render based on how the UI library handles priority. So top -> bottom or bottom -> top. Either way, each component that specifies its data will make a request. During the tree render, a state based fetch is triggered that is separate from the UI.

Even from this case, we are either making multiple requests to get all the data, or missing data that a single action (like rendering a synchronous UI) will need.

**Using a batched system**
* On the server, as the tree is being rendered, we know its a synchronous action so we hold off on the request until we have all of the operations. Then we combine them and make the request.
* On the client, typically this will act the same as the server on the initial render. On subsequent UI changes, we should batch non blocking queries
* During the render, state based fetches could insert their query into the queue and be combined with the single / reduced requests. 

**Things to solve / allow for:**
- [ ] blocking queries: if a component needs data to decide which child to render, it must be able to fetch then make the subsequent call
- [ ] multiple execution points: e.g. UI rendering and application state / data fetching
- [ ] merging of variables / separation of data: using `$id` in multiple arguments and multiple `variables: { id: "foo"}` `variables: { id: "foobar"}`

**Other considerations:**
- [ ] in an http2 world, this may not even be the ideal request pattern?
- [ ] is it more performant on the GQL side to batch requests or have a lot of small operations?

**Comment by stubailo** [comment]
I think as much as possible I want to maintain the store API of "just throw a ton of queries at it, and it works" so batching by time automatically would be great rather than having to distinguish between data fetching, UI components, etc.

**Comment by stubailo** [comment]
Since this feature targets more complex apps, I think it's prudent to get the basics correct first. I'm marking this as low priority.

**Comment by stubailo** [comment]
This is done BTW!
