### ISSUE TITLE
Factor out query normalization and denormalization functionality

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#255]
This will let people build their own smart GraphQL clients, or use this stuff without Redux.

**Comment by stubailo** [comment]
See conversation with @kennetpostigo here: https://apollostack.slack.com/archives/apollo-client-core/p1464297850000536

Also, this would probably be helpful for #244 

Ideally these would be importable from this package without using the rest of the code, or in a separate package entirely.

**Comment by helfer** [comment]
I'm thinking a separate package would be better, so versions don't have to be updated in lock-step.

**Comment by smolinari** [comment]
Thanks guys! I am almost certain this remodelling is a good step for Apollo to work best with other state managers, for instance, [Vuex](https://github.com/vuejs/vuex), which is Vue.js' own state manager. As I see it, and correct me if I am wrong, but the redux part of Appollo and Vuex do basically the same thing (only different). So, to get Vuex working with Apollo, we'd need different entry points as Evan pointed out (I believe) with `queryWatch` in another discussion about getting Apollo working with Vuex. 

Scott

**Comment by stubailo** [comment]
No I think your understanding is good! We have a top-level issue for this: https://github.com/apollostack/apollo-client/issues/256

**Comment by stubailo** [comment]
So far the best we have here is: https://github.com/apollostack/graphql-anywhere

We still need to work on getting Apollo to work with VueX, but I don't think that will be related, since it will probably be more of a plug-in into Apollo.
