### ISSUE TITLE
send operationName with graphql request

### ISSUE THREAD

**Issue by helfer** [apollostack/apollo-client#259]
This is useful for logging.

**Comment by helfer** [comment]
@Poincare I'm assigning this to you. It should be relatively easy to do. Just get the operation name from the AST and send it along with the query the way GraphiQL does by default. Not very high priority though.

**Comment by Poincare** [comment]
Will do.

**Comment by Poincare** [comment]
Fixed by PR #282 - closing.

**Comment by extempl** [comment]
Is it possible to put `operationName` to GET parameter of the actual URI used for request?
It would be even easier to be able to seacrch&filter in the log or just visually determine request between tens of the same URI. 
May be optional for dev state only if may influence something like performance or cache.
