### ISSUE TITLE
Print a warning for unnamed queries

### ISSUE THREAD

**Issue by helfer** [apollostack/apollo-client#260]
Related to #259. I think we should strongly encourage using named vs. unnamed queries.

**Comment by stubailo** [comment]
I disagree that this should print a warning, since the overwhelming majority of current graphql servers don't use the operation name for anything at all. Perhaps we can have an Apollo server Network interface or something which prints this warning instead?

**Comment by stubailo** [comment]
Also, this could be part of https://github.com/apollostack/eslint-plugin-graphql or similar.

**Comment by helfer** [comment]
Ok, agreed, closing for now.
