### ISSUE TITLE
Remove fetch dependency

### ISSUE THREAD

**Issue by helfer** [apollostack/apollo-client#269]
This would make things like whatwg-fetch (#267) unnecessary. It's only a minor change in the network interface, so it should be easy to do.

Anyone want to take this?

**Comment by stubailo** [comment]
Yeah this is compounded by the fact that we only use like 1% of the features of fetch.

**Comment by jbaxleyiii** [comment]
@stubailo @helfer any direction on doing this isomorphically? I'd be happy to rework it but not sure of a solid universal way?

**Comment by stubailo** [comment]
I know of one that's pretty solid and relatively minimalist... https://github.com/meteor/meteor/tree/devel/packages/http

**Comment by batjko** [comment]
Guys, I'm unable to use any fetch polyfills anymore, when using apollo-client on node.
I have tried node-fetch, whatwg-fetch and isomorphic-fetch, but I keep getting "fetch is not defined errors".

It used to work a little while back (maybe two months?), but today I am trying to use Apollo-client in a new node app and just can't get my query to work anymore.

e.g.:
```js
import ApolloClient, { createNetworkInterface } from 'apollo-client'
import gql from 'apollo-client/gql'

// doesn't support import syntax
const fetch = require('node-fetch')

client.query(...
```

Anything else I should be aware of?

**Comment by helfer** [comment]
@batjko Would you be interested in rewriting the meteor package that sashko linked to into a npm package? I think that would do the trick, and we could provide assistance where needed.

**Comment by batjko** [comment]
@helfer It looks like the HTTP package is just wrapping the npm "request" package under the hood, which, although it's not pretty, could be used instead?.

I wonder if [axios](https://www.npmjs.com/package/axios) or the like wouldn't be better recommendations though? Supporting promises instead of callbacks, even for multiple concurrent requests.

**Comment by stubailo** [comment]
@batjko we can't use request in the browser though. I was specifically suggesting http as a nice code base that works exactly the same way on client and server, and is super well tested.

**Comment by stubailo** [comment]
Axiom looks pretty cool - how big is it? Ideally we don't want to increase the size of this library too much.

**Comment by batjko** [comment]
The downloaded npm package racks up about 270kb. Written in typescript though, if that helps? ;)

**Comment by hwillson** [comment]
@batjko The [minified axios dist](https://github.com/mzabriskie/axios/blob/master/dist/axios.min.js) is much less, coming in at around 10k.

**Comment by batjko** [comment]
True. Depends on how you guys import the thing.

**Comment by stubailo** [comment]
10k still seems overwhelmingly large just to make an http request with a promise. All of Apollo client is like 25k or something.

**Comment by batjko** [comment]
Ah, makes sense then.
I don't think I can do the conversion of that HTTP package though, I don't know the first thing about how npm or meteor packages are built.
I should really read into that sometime.

**Comment by kamilkisiela** [comment]
What do you guys think?

https://github.com/kamilkisiela/httpcall

Basically it the same implementation as in https://github.com/meteor/meteor/tree/devel/packages/http

**Comment by batjko** [comment]
@kamilkisiela Yea tests are missing. If a big project like Apollo were to depend on this, it better be plastered with code coverage.

**Comment by stubailo** [comment]
Wow awesome @kamilkisiela! I was going to put it together but you beat me to it :)

**Comment by kamilkisiela** [comment]
@stubailo I have one question.

While I was creating [this](https://github.com/kamilkisiela/httpcall/blob/master/src/url.ts#L10-L14) I saw that there is a `escape` variable [inside of it](https://github.com/meteor/meteor/blob/devel/packages/url/url_common.js#L3-L5).

From where it come from?

**Comment by hwillson** [comment]
@kamilkisiela It's actually the JS standard library [`escape`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape) function (now deprecated). `String.replace`  can accept a function as its second parameter, that can be called to create the new substring.

**Comment by kamilkisiela** [comment]
@hwillson Didn't know, thanks!

I added few tests and created a build process with continuous integration. If someone wants to help with moving tests from meteor package it would be amazing! :)

@stubailo Do you guys want to have it under apollostack or meteor organisation or something?

**Comment by helfer** [comment]
@kamilkisiela Under apollostack would be good.

**Comment by kamilkisiela** [comment]
@helfer You can create the repository for it and I will do transfer.

**Comment by helfer** [comment]
@kamilkisiela I've created a repo called **http**, you have write access (as soon as you accept the team invitation), so you can push your initial commits to it without making a PR.

**Comment by kamilkisiela** [comment]
@helfer Done :+1:

**Comment by abhiaiyer91** [comment]
Alright so is this still an issue?

**Comment by stubailo** [comment]
Yeah, definitely!

**Comment by helfer** [comment]
I don't think it's necessary to track this here, as it's on our medium-term roadmap now.

**Comment by pleunv** [comment]
Perhaps relevant? https://github.com/developit/unfetch

**Comment by calebmer** [comment]
@pleunv we thought about it, but it is still too early: https://github.com/apollographql/apollo-client/pull/1320. Mainly `unfetch` doesn’t have CORS or cookie support which are two very important HTTP network features.

In the future we are interested in moving towards a world where the user defines their own GraphQL execution function. It’s only a few lines in the user’s code for a lot of benefits. We currently have abstractions around middleware that we just wouldn’t need if the user was in control of query execution. At that point you can decide whether or not you want to use `unfetch` 😊
