### ISSUE TITLE
Add __typename fields to queries automatically

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#27]
This can be done in a lot of different places. I think actually it might make sense to do it close to where the query is created, for example in `watchQuery` in QueryManager.

I mentioned earlier doing it in the network interface, but it kind of makes sense for that thing to just handle query fetching. It's a natural place to do it in Relay, but that's mostly because the network layer is basically the only documented integration point in Relay.

This should be configurable - if you have a Relay spec-compliant server, it will complain when you ask for `id` on an object that doesn't have that field. But if you have a server that returns `null` on non-existent IDs, we can just put it in everywhere. Luckily, this is not a problem with `__typename` because it's guaranteed to exist everywhere by the GraphQL spec itself.

**Comment by stubailo** [comment]
Assigning to @martijnwalraven to get feedback because he is looking at #26

**Comment by stubailo** [comment]
Changed this issue to just `__typename`, we can cross the `id` bridge when we get there.

**Comment by stubailo** [comment]
Assigned @Poincare, it's his first day as an intern on the Apollo team!

**Comment by abhiaiyer91** [comment]
welcome @Poincare Lets make some moves
