### ISSUE TITLE
Response "errors" field is not always an array

### ISSUE THREAD

**Issue by timbotnik** [apollostack/apollo-client#271]
This makes it *slightly* harder to check for errors.  I see this one when I shut down the GraphQL server while a request is in-flight.

![screen shot 2016-06-06 at 1 09 40 pm](https://cloud.githubusercontent.com/assets/1831709/15812015/2aa549f8-2bf3-11e6-964d-e5afdd017a51.png)

**Comment by helfer** [comment]
@timbotnik you're not supposed to shut down the GraphQL server while requests are in-flight 😛 

On the other hand, I think you're right that it would be nice to return this error in an array even though it's not an error from the server.

**Comment by stubailo** [comment]
Shouldn't this be returned as a network error rather than a server error? Those are currently returned in different places, so this smells like a bug. On the other hand it would probably be a good idea to unify how errors are handled regardless of where they come from.

**Comment by stubailo** [comment]
I think #352 will address this.

**Comment by Poincare** [comment]
This should now be fixed w/ the 0.4.x release?

**Comment by stubailo** [comment]
Agreed - the `errors` field on the response doesn't exist anymore, and now we get errors in the form of a `catch`/`error` with an `ApolloError` object.

**Comment by timbotnik** [comment]
@stubailo do you know when this will be avail `react-apollo` land?

**Comment by stubailo** [comment]
Should be now! Since react-apollo doesn't do anything special with errors, it just passes them through AFAIK. does it not work?
