### ISSUE TITLE
Changing variables in watchQuery after polling started

### ISSUE THREAD

**Issue by timsuchanek** [apollostack/apollo-client#272]
Hi,
so I'm creating an observable with the `client.watchQuery` method and watch on it.
It works fine.
But let's say variables in my query changed.

How to properly handle that?
Do I really have to kill the old observable and create a new one which includes the new query?

In other words: How to change variables of a polling `ObservableQuery` in runtime?

Idea: Pass in an optional callback that returns the current variables.

I ask, because doing that kill/respawn approach would require a lot of refactoring in my code.

Thanks!

**Comment by stubailo** [comment]
@poincare I think mutating the variables is not the right approach long term, even though it might work now. I think we should encourage people to make those immutable, and perhaps provide a method to update the query options.

**Comment by Poincare** [comment]
Makes sense. I guess I will leave this issue open and we'll fix it soon.

**Comment by timsuchanek** [comment]
Hey guys, thanks for the fast answers.
@Poincare your solution works like a charm.
So do you want some unit tests or better later when there is a better api for this use case?

**Comment by stubailo** [comment]
You can help us design the API! What should it look like?

**Comment by timsuchanek** [comment]
Ha I'm pleasured to tell you my opinion for the API.

Ok, this is my use case:
I get params from `react-router` into my React component and pass them into an action, which is a `redux-thunk`, that then creates the observable and its subscription.

(Btw I'm aware of `react-apollo`, but I had some problems with error handling with it, so I decided for a pure `redux/apollo-client` implementation, as I just could move forward faster with this approach.)

So the first naive Idea I had, was to pass the apollo client a callback, that looks into the redux store and gets what it needs. Problem is: The url params of `react-router` are not available in the redux store.
They only get passed in into the component directly.
So we need a way that includes the component.
So the way I suggest is, that we add an explicit call on the observable, that updates the observable and if the user wants, directly performs a query afterwards.

Something like `observable.updateVariables({vars})` would be really handy in this scenario.
Would do you think about it?

**Comment by stubailo** [comment]
Just trying to understand better - why not stop the previous observable and start a new one with new variables?

**Comment by Akryum** [comment]
Isn't this less efficient in terms of performance/memory?

**Comment by stubailo** [comment]
Not really - the overhead of creating an observable object is basically 0, everything else is handled by the cache almost exactly the same way.

**Comment by stubailo** [comment]
Or yeah, I guess there are also some extra things stored in Redux when you start/stop a query. So it could be less efficient, but we haven't run into that as a source of problems in our production apps. It's mostly React renders that are very costly.

**Comment by stubailo** [comment]
Done! #635
