### ISSUE TITLE
Turn off Caching

### ISSUE THREAD

**Issue by romellogood** [apollostack/apollo-client#276]
Is there a way for caching to be turned off? There isn't any documentation on options I can pass to turn this off so that every request is sent and things aren't cached.

**Comment by helfer** [comment]
@romellogood You can pass the option `forceFetch: true` to `query` or `watchQuery`. If you're using react-apollo, you can pass the same option to `mapQueriesToProps` and `mapMutationsToProps`. Does that solve your problem?

**Comment by romellogood** [comment]
Yes it worked. Thank you.
