### ISSUE TITLE
Query merging fails when merging the same query with different variables

### ISSUE THREAD

**Issue by timbotnik** [apollostack/apollo-client#296]
Just trying out the new batching mode, ran into this issue since we are running the same query multiple times with different vars.  Failing test on the way.

![screen shot 2016-06-22 at 2 14 35 pm](https://cloud.githubusercontent.com/assets/1831709/16254473/950fdae6-3883-11e6-8661-1638f1870cd8.png)

**Comment by stubailo** [comment]
Should be fixed in `0.3.18`!

**Comment by timbotnik** [comment]
Tested, WFM, thanks!

**Comment by stubailo** [comment]
@timbotnik I'm about to remove the need for `addQueryMerging`: #303
