### ISSUE TITLE
Update to include typescript 1.8 features

### ISSUE THREAD

**Issue by jbaxleyiii** [apollostack/apollo-client#30]
'll do the update and list out the new features that are meaningful here. :+1: 

*Note*
We have been using 1.8, but typescript just updated their site and have a good breakdown of 1.8 features. A few of them will be helpful here so I'll document them as tooling enhancements and open a corresponding PR with the adjustments

**Comment by mquandalle** [comment]
Aren’t we using typescript 1.8.9 already? https://github.com/apollostack/apollo-client/blob/048ac76b7c9f7399db3e788cb8ceca6091d01e91/package.json#L47

**Comment by mquandalle** [comment]
Oh, did you mean update to TS1.8 new language features?

**Comment by jbaxleyiii** [comment]
@mquandalle yep! Wherever they can be applied!

**Comment by mquandalle** [comment]
Maybe one occurrence of that is in the GraphQL typescript interface, I think the following interfaces could be modified as follows:

```diff
    interface IntValue {
-       kind: string;
+       kind: "IntValue";
        loc?: Location;
        value: string;
    }

    interface FloatValue {
-       kind: string;
+       kind: "FloatValue";
        loc?: Location;
        value: string;
    }
```

**Comment by stubailo** [comment]
ooh, that's neat. we should send a PR or something? or do these definitions want to be compatible with multiple versions of the language?

**Comment by jbaxleyiii** [comment]
closing because it looks like we are already using everything useful
