### ISSUE TITLE
Note that Relay doesn't support certain things on root queries

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#304]
Which is a big reason people use `viewer`. For example, see:

https://apollostack.slack.com/archives/general/p1466637279001259

**Comment by tlvenn** [comment]
Current Relay limitation on root fields are well explained there: https://github.com/facebook/relay/issues/112#issuecomment-195456911

It does not look like FB has any interest in solving this for now and it's definitely a pretty big plus that apollo client does not enforce any restrictions on root fields.

**Comment by stubailo** [comment]
Something to think about for a comparison chart!

**Comment by ramsaylanier** [comment]
FWIW this is one of the main reasons I switched from Relay to Apollo. 

So thanks. 

👍
