### ISSUE TITLE
Custom NetworkInterface query argument

### ISSUE THREAD

**Issue by arbesfeld** [apollostack/apollo-client#306]
The `Request` interface: https://github.com/apollostack/apollo-client/blob/master/src/networkInterface.ts#L19

Doesn't seem to match the interface in the documentation: http://docs.apollostack.com/apollo-client/network.html#GraphQLRequest

For implementing a custom network interface, it would be convenient if the spec matched the spec in the docs and passed the `query` as a string.

**Comment by Poincare** [comment]
I think this is no longer a bug in ApolloClient since we decided to expose the `printAST` method rather than stick to the currently documented approach. Guess the bug is now within the documentation.

**Comment by Poincare** [comment]
With the above issue in apollostack/docs, I think it is now safe to close this issue on apollo-client.
