### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#31]
Currently, we don't support variables. This is extra useful in mutations. so for now I'll implement simple mutations without variables and then add variable support for both queries and mutations afterwards.

**Comment by jbaxleyiii** [comment]
@stubailo with this change, we will be able to start testing this in our application stack as it reaches the current functionality we are using with Lokka :fire:

**Comment by stubailo** [comment]
Yep! In fact, more, because Lokka doesn't support variables in mutations. (I guess it does if you use `query` lol)
