### ISSUE TITLE
0.4.0 release with breaking changes

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#324]
- [x] Remove `apollo-client/gql` shim in favor of `graphql-tag` package
- [ ] Remove special publish script in favor of normal npm publish
- [ ] Remove any legacy exports and functions that we can find

- [ ] Consider changing argument format to `write*ToStore`, `read*FromStore` and `diff*AgainstStore` to avoid repeating those in every file that uses them, by factoring out an object that contains all of the common properties.

**Comment by stubailo** [comment]
CC @rricard here's where I was keeping track of breaking changes for `0.4.0`.

**Comment by Poincare** [comment]
@stubailo can we close this?
