### ISSUE TITLE
Polling (and force fetch in general) while the client is disconnected empties the store after erroring

### ISSUE THREAD

**Issue by rricard** [apollostack/apollo-client#334]
## Expected

If the polling fails because of a connection issue, still show errors in the console and everything, but don't change the contents of the store!

## Obtained

If the polling fails because of a connection issue, errors arise in the console and empties the store where the query is.

Is this really the behavior we want ?

## Fix proposition

Polling shouldn't just trigger a `forceFetch` but a `forceFetch` able to, when an error arises, don't change the apollo store state.

**Comment by stubailo** [comment]
Good point! Will look into this. Error handling in general is something we are taking a look at soon.

**Comment by rricard** [comment]
Yes, ok, I would be for, by default, not delete the contents of the store then. (I thought the behavior was wanted if graphql errors arised)

**Comment by rricard** [comment]
I can look into that if you want as well, I will need a fix pretty ASAP and I see you guys already have a bunch of projects going on! 😉

**Comment by stubailo** [comment]
We were going to take a look at error handling late this week or early next week, but I'd be happy to look at a design for a fix, or a PR!

**Comment by rricard** [comment]
Let me just finish first with #335, I'll see after that!

**Comment by rricard** [comment]
I need to retake a look. Maybe a recent change may have fixed that.

**Comment by rricard** [comment]
@Poincare: my bad the issue is on apollostack/react-apollo: when an error is associated to the component, the component doesn't receive the data anymore.

**Comment by rricard** [comment]
cf https://github.com/apollostack/react-apollo/pull/98
