### ISSUE TITLE
`watchQuery`/`query` wrappers modify options in-place

### ISSUE THREAD

**Issue by sgoll** [apollostack/apollo-client#339]
The `watchQuery`/`query` wrappers of ApolloClient modify the passed-in options in-place to honor the global `shouldForceFetch` setting: https://github.com/apollostack/apollo-client/blob/master/src/index.ts#L119

This has the unexpected side-effect of forcing re-evaluation of queries in react-apollo as the options now don't match that of the original query.

See the original issue at apollostack/react-apollo#90 for detailed discussion.

**Comment by stubailo** [comment]
Fixed in release `0.3.25`!
