### ISSUE TITLE
Avoid view integrations tracking loading state manually

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#342]
Right now, it seems like both `react-apollo` and `angular2-apollo` are tracking loading state by doing manual bookkeeping. But this doesn't seem optimal, because:

1. Apollo Client already keeps track of loading state internally
2. Some options to `watchQuery`, for example `returnPartialData`, might return data while `loading` is still `true`, confusing the view integrations

I think we should have a way to get the loading state from apollo directly, so that other libraries don't have to guess what it is.

@jbaxleyiii @kamilkisiela do you have some ideas for how it should be best returned? Some ideas:

1. Apollo Client returns a queryId, and has a `getLoadingState` method
2. The observable returned by `watchQuery` has a `getLoadingState` method
3. The result from the observable, which is currently a `GraphQLResult` with `data` and `errors`, can get a new property, `loading`

I think (3) is the best, would doing that be enough to remove the need to keep track of loading state in `react-apollo` and `angular2-apollo`?

**Comment by kamilkisiela** [comment]
@stubailo Totally agree that `loading` state should be delivered to UI integrations directly from `ApolloClient`.

**3rd option** seems to be the best one. 

> would doing that be enough to remove the need to keep track of loading state in `react-apollo` and `angular2-apollo`

Yes, it would :+1:

**Comment by davidwoody** [comment]
@stubailo It seems like https://github.com/apollostack/apollo-client/pull/385 has added the `queryId` to the result of calling `watchQuery`, so the `queryId` can now be used to read directly from the state of `apollo.queries`.

**Comment by stubailo** [comment]
Oh, awesome! I didn't even notice. I should publish a new version with all of these changes.

**Comment by davidwoody** [comment]
@stubailo haha yeah same, I was about to open up a PR for that tweak, but noticed the new changes in master beat me to it! I added a note to the changelog - https://github.com/apollostack/apollo-client/pull/405

**Comment by kamilkisiela** [comment]
@stubailo Do we stay with `queryId` and `apollo.queries` or there's going to be that 3rd option implemented?

> The result from the observable, which is currently a `GraphQLResult` with `data` and `errors`, can get a new property, `loading`

apollostack/angular2-apollo#43

**Comment by jbaxleyiii** [comment]
@stubailo @kamilkisiela I would love for this to be done!

**Comment by Poincare** [comment]
This should be fixed through #467 and then we can work on implementing the required changes within the view layers
