### ISSUE TITLE
Websocket network interface

### ISSUE THREAD

**Issue by jbaxleyiii** [apollostack/apollo-client#35]
Do we want to ship this as part of core or as a separate module?

A sample use case is in a Meteor app where extra variables / authentication happens via a Meteor method on the server.

@johnthepink and I will be building this interface next week and would love to know if we want it in core or as `import { createWSNetworkInterface } from 'apollo-client-websocket'` or the meteor sugared `import { DDPNetworkInterface } from 'apollo-client-ddp'`

**Comment by stubailo** [comment]
Can you give me an example of how you would use this?

**Comment by stubailo** [comment]
Also, is this websocket, or DDP?
