### ISSUE TITLE
addQueryMerging not defined in exports

### ISSUE THREAD

**Issue by hammadj** [apollostack/apollo-client#363]
Tried to setup a custom network interface with query merging, and in the docs here: http://docs.apollostack.com/apollo-client/network.html#addQueryMerging

it says to import the ‘addQueryMerging’ function from apollo-client, however, its not declared in the exports of apollo-client

**Comment by linonetwo** [comment]
So where is addQueryMerging at this time?

Since I'm using a custom networkInterface, I can't use createBatchingNetworkInterface directly.

**Comment by helfer** [comment]
@linonetwo it's [here](https://github.com/apollostack/query-merging), but I haven't had time to finish the package, and it isn't high on my list of priorities. If you're interested in helping out to get the package ready, I can give you all the necessary pointers and help you fix issues that you may run into. Let me know!

**Comment by linonetwo** [comment]
@helfer I'm glad to contribute, I can write TypeScript too, let me know what I can do!

**Comment by linonetwo** [comment]
@helfer I'm currently working on things about Wrapping REST into GraphQL, so there are custom interfaces. Data flow looks like this:
![qq 20161106105340](https://cloud.githubusercontent.com/assets/3746270/20035049/60d80756-a40f-11e6-8cfd-845800539a8d.png)

Now 「1.9 fetch result cached in the Model 」 is a trouble too. I haven't done that, so every query fetches REST API. Thus query lag even I use query merging.  
But I think the solution is similar to query merging: have an interval, query merging will merge query in this interval, model caching will cache data for this interval.
