### ISSUE TITLE
Apollo-Client with isomorphic React+Redux throwing error: localStorage is undefined

### ISSUE THREAD

**Issue by siegesmund** [apollostack/apollo-client#367]
I've refactored an existing app that uses Apollo to render the initial page load on the server. In doing this, Apollo appears to run queries during the initial, server-side render when localStorage is not available.

I'm wondering if there's an established pattern to deal with this?

**Comment by stubailo** [comment]
Do you want it to run queries when you're rendering on the server? Or do you want to render without data?

**Comment by siegesmund** [comment]
I suppose I'd like to do both, but I'll settle for rendering without data at the moment.

**Comment by stubailo** [comment]
Apollo Client itself doesn't use `localStorage` at all. So it sounds like you might be using a network interface middleware to attach a login token to your request? If so, you should add some logic in there that detects if you are on the server, and doesn't try to get a token from `localStorage` in that case.

**Comment by stubailo** [comment]
Closing because this doesn't seem related to apollo client core.
