### ISSUE TITLE
Wrapping a REST API in GraphQL

### ISSUE THREAD

**Issue by dalgard** [apollostack/apollo-client#379]
The article [Wrapping a REST API in GraphQL](http://graphql.org/blog/rest-api-graphql-wrapper/) describes how to use a client-side schema to resolve queries against a REST endpoint.

The schema is inserted as a **network layer** in Relay – can something similar be achieved with Apollo Client?

**Comment by dalgard** [comment]
Seems easier than I expected: [Custom network interface](http://docs.apollostack.com/apollo-client/network.html#custom-network-interface)

**Comment by stubailo** [comment]
Yep, that's it! Very similar to the Relay approach.

**Comment by linonetwo** [comment]
Great, I'm currently seeking for this. @dalgard Have you tried it yet?

**Comment by stubailo** [comment]
By the way, if someone wants to write a post about this it would be awesome!

**Comment by dalgard** [comment]
@linonetwo Not yet. Don't know whether I'm going to need it within the next couple of months. Still interested, though!

**Comment by linonetwo** [comment]
OK I'm trying it...

what can be inferred from apollo's docs is just:
```javascript
import { addQueryMerging } from 'apollo-client';

class REST2GraphQLInterface {

  query({ query, variables, debugName }) {
    return Promise.resolve({ data: {}, errors: [{ code: 0, msg: 'errorMsg' }] });
  }
}

export default addQueryMerging(REST2GraphQLInterface);
```

I need to refer to relay's doc for further implementation examples...

**Comment by linonetwo** [comment]
So I don't need a 「graphql」 package, instead a 「graphql-tool」 at the client side?

**Comment by linonetwo** [comment]
Well, I think writing REST2GraphQL on the client side is much similar to what we usually wrote on the server side.

The only difference is that we use the connector to get data from database usually, now we use the connector to get data from REST endpoint.

I'm not sure whether I'm on the right path or not.

**Comment by stubailo** [comment]
@linonetwo you're definitely on the right path. What you are basically doing is writing a "GraphQL server", but on the client, so any of the GraphQL server docs will apply.

You don't need `apollo-server` or `express-graphql` for this - those packages are for attaching GraphQL to a real web server, which you don't have or need on the client. You just need to get a `GraphQLSchema` instance and call it yourself via the `graphql` function from the `graphql` package.

**Comment by linonetwo** [comment]
Thanks for guiding.

Another question: on the server side I can just pass any error message to a logger. But on the client side "server" I need a way to pass some of the error messages to UI, which will go through React's props. 

So should I add an "ErrorMessage" type to the schema, and if some Promise on the connector rejects, I get those error message into ErrorMessage type's resolver?
I don't have ideas about how to handle errors from other types' resolvers and get them into ErrorMessage's resolver, can you give me a clue?

**Comment by linonetwo** [comment]
I think I can cache data inside connector.
if `/api/account/whoami` returns
```json
{
  "code": 0,
  "data": {
    "companyId": 1,
    "companyName": "Company1",
    "departmentId": 1,
    "departmentName": "工程部",
    "id": 7,
    "name": "用户3",
    "role": "Customer",
    "username": "Customer3"
  }
}
```
and I only need `departmentName` and `companyName` for this time, I can cache the whole json inside connector, and set an expire time or so. When next query about `role` goto connector will hit this cache .

But it looks redundantly with apollo-client 's client side cache. I'm feeling confusing.

**Comment by linonetwo** [comment]
I can write a blog after this...

I'm currently using「graphql」package to parse executeableSchema like this:
```javascript
const executableSchema = makeExecutableSchema({
  typeDefs: schema,
  resolvers,
});

class REST2GraphQLInterface {
  query({ query, variables }) {
    return graphql(
      executableSchema,
      query,
      undefined, // should be rootValue here, I don'k know what its used for
      { 
        Config: new Config({ connector: serverConnector }),
        User: new User({ connector: serverConnector }),
      },
      variables
    );
  }
}

export default addQueryMerging(REST2GraphQLInterface);
```

I don't know whether it will be working, I'm still writing resolvers.

**Comment by stubailo** [comment]
What is `schema`? perhaps it's not the right kind of object?

**Comment by stubailo** [comment]
Also, you don't need to write resolvers like `({ field }) => field` - that's the default behavior. So you only need explicit resolvers for the case where you need to do some transformation on the data.

**Comment by linonetwo** [comment]
OK, My only reference is GitHunt... Learnt from it :

```
type Entry {
  repository: Repository!
  postedBy: User!
  createdAt: Float! # Actually a date
  score: Int!
  comments: [Comment]! # Should this be paginated?
  commentCount: Int!
  id: Int!
  vote: Vote!
}
`];

export const resolvers = {
  Entry: {
    repository({ repository_name }, _, context) {
      return context.Repositories.getByFullName(repository_name);
    },
    postedBy({ posted_by }, _, context) {
      return context.Users.getByLogin(posted_by);
    },
    comments({ repository_name }, _, context) {
      return context.Comments.getCommentsByRepoName(repository_name);
    },
    createdAt: property('created_at'),
    commentCount({ repository_name }, _, context) {
      return context.Comments.getCommentCount(repository_name) || constant(0);
    },
    vote({ repository_name }, _, context) {
      if (!context.user) return { vote_value: 0 };
      return context.Entries.haveVotedForEntry(repository_name, context.user.login);
    },
  },
```
that
every field we are using should a resolver function, or we can't get data for it.

Are there any edge case learning material?

**Comment by stubailo** [comment]
Note that `id` doesn't have a resolver. `createdAt` has one because we are renaming the field from `created_at`.

We're probably going to write a complete GraphQL server guide in the future, but it's not our top priority right now.

**Comment by linonetwo** [comment]
I found that there were lots of posts on the Medium written by your team, which are extremely useful for beginners.Thank you guys!

But were they be linked or merged to docs, I won't spending so much time learning and experimenting it...

Now building a wrapping for RESTful endpoint is a very easy job, I'm almost done.
I'll write a post soon.

**Comment by linonetwo** [comment]
I have my try to make it [my experiment repo](https://github.com/linonetwo/GraphQLexperiment)

though my writing of resolver is kind of verbose...

**Comment by linonetwo** [comment]
@stubailo You mentioned that I can call executableSchema via the graphql( ) function from the graphql package, I'm doing it like this:
```javascript
// http://dev.apollodata.com/core/network.html#NetworkInterface
class REST2GraphQLInterface {
  query({ query, variables }) {
    console.log(executableSchema); // exists
    console.log(query); // exists
    console.log(variables); // I'm not using it currently
    return graphql(
      executableSchema,
      query,
      undefined,
      {
        Config: new Config({ connector: serverConnector }),
        User: new User({ connector: serverConnector }),
        PowerEntity: new PowerEntity({ connector: serverConnector }),
        FortuneCookie: new FortuneCookie(),
      },
      variables
    );
  }
}
```

But query it will throw out `{ errors: [ [TypeError: source.body.split is not a function] ] }` just like [this graphql-js issue descripes](https://github.com/graphql/graphql-js/issues/274)

Relay have a [different NetworkInterface](https://facebook.github.io/relay/docs/guides-network-layer.html#custom-network-layers) from Apollo, It has [sendMutation(mutationRequest), sendQueries(queryRequests), supports(...options)](https://facebook.github.io/relay/docs/interfaces-relay-network-layer.html#overview) , while Apollo use single [query(request: GraphQLRequest): Promise<GraphQLResult>](http://dev.apollodata.com/core/network.html#NetworkInterface). So I can't use package [relay-local-schema](https://github.com/relay-tools/relay-local-schema) as [Facebook mentioned](http://graphql.org/blog/rest-api-graphql-wrapper/#using-a-client-side-schema-with-relay) directly too.

**Comment by linonetwo** [comment]
Ok, I made it on the react-native side, in production!

I will link my blog post here later.

So, @dalgard I think this issue can be closed now. Apollo is proved to be capable of wrapping REST end point : D

**Comment by Urigo** [comment]
@linonetwo I would love to see an English version of that post!
If you need help with that I would love too

**Comment by linonetwo** [comment]
@Urigo Ok, I'm working on that, please wait for a while.

**Comment by linonetwo** [comment]
@Urigo http://onetwo.ren/wrapping-restful-in-graphql/

**Comment by lucasconstantino** [comment]
I've being working on a project with apollo-client/server both on the browser wrapping a rest api. I works smoothly, with File upload support, Apollo client dev tools working properly, etc, etc. I'm working on a post in portuguese, but I guess I can make a copy in english and put in on Medium or similar. Does anyone have a better or more contextualized place to publish it, in case it fits?

**Comment by Urigo** [comment]
@lucasconstantino Medium sounds great.
If you want we can review it and in the case will fit and a lot of people will be interested, publish it also under our Apollo publication

**Comment by lucasconstantino** [comment]
Here it goes: https://medium.com/@constantinoyo/graphql-today-using-apollo-for-applications-that-still-depend-on-rest-apis-839895ce20d0

**Comment by SeanBannister** [comment]
For anyone else stumbling across this you might like to check out https://github.com/mstn/apollo-local-network-interface

**Comment by jozanza** [comment]
Looks like the approach with Apollo 2.0 is different with the "link" approach replacing network interfaces. Here's how I personally got my plain old `GraphQLSchema` instance working:

```js
import { Observable, ApolloLink, execute, makePromise } from 'apollo-link'
import { InMemoryCache, IntrospectionFragmentMatcher } from 'apollo-cache-inmemory'
import { ApolloClient } from 'apollo-client'
import { graphql, print } from 'graphql'
import schema from './schema' // should be an instance of GraphQLSchema

const link = new ApolloLink(
  operation =>
    new Observable(observer => {
      const { query, variables, operationName } = operation
      graphql(schema, print(query), {}, {}, variables, operationName)
        .then(result => {
          observer.next(result)
          observer.complete(result)
        })
        .catch(e => observer.error(e))
    }),
)
const cache = new InMemoryCache()
//  Note: if your schema contains interfaces / union types, ApolloClient can't infer possibleTypes out-of-the-box
//  You'll have to let it know manually via a fragmentMatcher. For example:
//  const cache = new InMemoryCache({
//    fragmentMatcher: new IntrospectionFragmentMatcher({
//      introspectionQueryResultData: {
//        __schema: {
//          types: [{
//            kind: 'INTERFACE',
//            name: 'Either',
//            possibleTypes: [
//               { name: 'Left' },
//               { name: 'Right' },
//            ]
//          }] 
//        }
//      },
//    }),
//  })
const client = new ApolloClient({ link, cache })
```

**Comment by Vanuan** [comment]
Here's an example for Apollo client 2.0:

https://stackoverflow.com/a/48082522/99024
