### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by Poincare** [apollostack/apollo-client#390]
We can use this issue to keep track of ideas to improve performance within Apollo Client. Here are a few initial ideas which I'll modify as I learn more about existing applications running on Apollo Client:

* Polling intervals should be decreased in a background tab
* Look into shouldComponentUpdate to prevent useless re-renders
* Smarter handling of the loading state to prevent excessive re-renders (might be app-specific?)

**Comment by stubailo** [comment]
> Look into shouldComponentUpdate to prevent useless re-renders

I think this comes down to just avoiding firing the observer when the query result hasn't changed. People shouldn't need to use shouldcomponentupdate.

**Comment by Poincare** [comment]
This stuff has been completed and merged (#403 and #402) so I'll go ahead and close this

**Comment by amannn** [comment]
I've just did a quick test how long a query takes to be fulfilled. When there's a GraphQL server running and I make a request to it from the same server (like it would happen during a server side render) I get a response time of around 90 ms.

The query I used was pretty simple:

```
query Home($country: CountryCode!) {
  storeInfo(country: $country) {
    products, stores
  }
}
```

Is that a response time that looks ok to you? What response times do you get for your requests?

I was wondering if it makes sense to somehow short circuit server side graphql requests to the graphql middleware as that's running on the same server in my app. Not sure if that's a good idea though.

I'm using apollo-client 0.4.12, apollo-server 0.2.5, graphql 0.6.2, graphql-tag 0.1.11 and graphql-tools 0.6.4 and the app is running on my MacBook Pro Retina.

**Comment by stubailo** [comment]
I don't think doing GraphQL requests to your own server is necessary. Why not just call your model/database code directly?

**Comment by helfer** [comment]
@amannn I think it doesn't really make sense to do benchmark testing that involves server and client. Each of them should be benchmarked individually (for example with a mock network interface) to remove as many variables as possible. Performance testing with server and client together only makes sense once you know what kind of setup you want.

PS: I think 90ms is quite long, but it's hard to know what you're measuring here with that many variables.

**Comment by amannn** [comment]
Thanks for your quick responses!

For the general explanation, my server both takes care of server side rendering, as well as providing a graphql endpoint. What I forgot to mention is that my graphql resolver immediately resolves with `Promise.resolve` – so it doesn't talk to any REST APIs or databases etc. (at least for testing right now).

@helfer I'm not sure if we're on the same page here. The client I'm talking about is apollo-client that runs server side during a server side render. So there's no network latency between a browser and a server involved. It's basically the server talking to itself over HTTP, which I suppose should have a negligible performance impact (I hope).
@stubailo Those requests are coming from the UI code during the server side render. I can't have any direct calls to databases etc. in there, as that code also runs in the browser.

**Comment by stubailo** [comment]
Oh, OK, I get it!

90ms is interesting, it would be really cool to try to profile it and break down what is taking up that time.

I think we should open a separate issue, though.

**Comment by amannn** [comment]
Actually I think it's probably not worth opening a separate issue, as I think this is solved.

I just tried to do some profiling. I set up a very basic node script that just performs a single query:

```
require('isomorphic-fetch');
const ApolloClient = require('apollo-client').default;
const createNetworkInterface = require('apollo-client').createNetworkInterface;
const gql = require('graphql-tag');

const graphqlURL = 'http://localhost:8080/graphql';
const networkInterface = createNetworkInterface(graphqlURL);
const client = new ApolloClient({networkInterface});

console.time('fetch');
client.query({
  query: gql`
    query Home($country: CountryCode!) {
      storeInfo(country: $country) {
        products, stores
      }
    }
  `,
  variables: {country: 'UK'}
}).then(() => {
  console.timeEnd('fetch');
});
```

This is now quite a bit faster and resolves after around 45ms on my machine. I think the initial 90ms I measured were related to surrounding things in my app (or who knows what else). Btw. I also tried `process.hrtime` for measuring, which produces very similar results.

A simple `fetch` call for the same query (without parsing the result) resolves after roughly 20ms:
```
fetch(graphqlURL, {
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json'
  },
  method: 'POST',
  body: JSON.stringify({
    query: `
    query Home($country: CountryCode!) {
      storeInfo(country: $country) {
        products, stores
      }
    }
    `,
    variables: {country: 'UK'},
    operationName: 'Home'
  })
}).then(res => {
  console.timeEnd('fetch');
});
```

I've used the [isomorphic-fetch polyfill](https://github.com/matthew-andrews/isomorphic-fetch) in both test cases. As far as I know apollo-client also uses fetch under the hood, so if you subtract that you'll end up at around 25ms processing time after getting the result from fetch. Btw. parsing the JSON response takes around 1ms from what I've seen.

I think that's pretty ok, what do you think? Sorry for the false report initially!

**Comment by colllin** [comment]
Did you ever handle your first bullet point in original issue?

> - Polling intervals should be decreased in a background tab

It seems like a reasonable default to pause polling when the tab is in the background.  Would this be as simple as using `requestAnimationFrame` instead of `setTimeout` or `setInterval`?

Or should we just expect to handle this ourselves using `startPolling()` and `stopPolling()`?
