### ISSUE TITLE
Don't fire the observer if the result of a query hasn't changed

### ISSUE THREAD

**Issue by Poincare** [apollostack/apollo-client#400]
If we have a `watchQuery` observer and we receive a result from the server that is identical to the last result we handed to the observer, we should not call the observer at all. This will prevent solutions like using `shouldComponentUpdate` and will reduce useless re-renders on the page.

**Comment by nevir** [comment]
I'm unsure if I'm running into the same thing, or a slight variation of it:

I have a `watchQuery` (with `noFetch: true`); the observer's `next` fires _2 or 3 times_  each time the store is changed, even if some other portion of the store (not owned by apollo) was modified

**Comment by Poincare** [comment]
Hm. That should not happen if the part of the store associated with the store was left untouched. Could you file an issue that would allow us to reproduce the problem? (a unit test would also be great!)

**Comment by Poincare** [comment]
Since #402 was merged, this issue can now be closed.

**Comment by stubailo** [comment]
And deployed!

**Comment by stubailo** [comment]
@nevir can you check if `0.4.2` fixes your issue with multiple firing?

**Comment by nevir** [comment]
@stubailo can confirm - all better as of `0.4.2`

**Comment by stubailo** [comment]
Sweet! It really helped in our app as well.
