### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#41]
In the current code, the store will grow without bound as more and more queries are fetched. We should implement a strategy for clearing out data we are no longer using.

This can be as simple as re-running all of the active queries and putting the results into a new empty store, then throwing away the old one.

**Comment by mquandalle** [comment]
Could ES6 `WeakMaps` be of any use here?

**Comment by stubailo** [comment]
That's an interesting idea! On the other hand, I think it would be beneficial to be able to inspect via Redux which items are being garbage collected. If items start unexpectedly disappearing from the store, that might be very confusing. I wonder if we can somehow get both.

**Comment by stubailo** [comment]
Relay got this far without having garbage collection at all, so I think this is a pretty low priority right now.

**Comment by helfer** [comment]
I'm closing this since I think we don't need an issue to keep track of this. a) we're not likely to forget this, and b) project notes would be a better place.
