### ISSUE TITLE
A few changes in store format

### ISSUE THREAD

**Issue by Poincare** [apollostack/apollo-client#410]
After discussing potential solutions to #344 with @stubailo, we realized that there is a need for some changes to the store format that allows us to distinguish between generated ids, application-provided ids (i.e. returned by `dataIdFromObject`) and normal scalars. This issue describes a proposed change to the store format that will allow us to make these distinctions.

## Why?

Suppose these two queries are fired one after another through `watchQuery`:

```
query {
   author {
     firstName
     lastName
   }
}
```

```
query {
   author {
     firstName
     __typename
    id
   }
}
```
But, only the second query is assigned an `id` through `dataIdFromObject`. This means that the first query's `author` will have a generated id whereas the second query's `author` will have a real id. Currently, this means that the first query's observable will break because it won't be able to find `lastName` within the store. 

This means we have to be able to merge the objects from the two queries. To do this, we need to be able to distinguish between generated, real ids and just normal scalars. If we were to just prepend something like a "$" to a generated id, this would leave us unable to distinguish between an id and a value that just happens to have a "$" at the start of it.

## Solution

In the store, we escape ids by placing them within an object with the key "id" and use another key called "generated" that is a boolean value which will tell us whether or not the id was generated by Apollo.

For example, this is what the store would currently look like after incorporating the results from the first query above:

```
{
  "RootQuery": {
     "author": "RootQuery.author"
   },
   "RootQuery.author": {
     "firstName": "John",
     "lastName": "Smith"
   }
} 
```

After this proposed change, the store would look like this:

```
{
  "RootQuery": {
     "author": {
       "type": "id",
       "id": "RootQuery.author",
       "generated": true,
     },
  },
  "RootQuery.author": {
    "firstName": "John",
    "lastName": "Smith",
  }
}
```

In addition to escaping ids in this way, we have to also escape JSON objects so that a malicious user can't somehow insert an id-like object into the cache. For example, say we had the following query:

```
query {
  author {
    info
  }
}
```

where `info` returns a JSON blob. Once this query's results have been processed, the store should look like this:

```
{
  "RootQuery": {
    "author": {
      "id": "RootQuery.author",
      "generated": true, 
    }
  },
  "RootQuery.author": {
     "info": { 
       "type": "json",
       "json": {
          //a bunch of JSON
       }
     }
   }
}
```

Notice that we use the `type` key on the object in order to determine what kind of object we are dealing with (i.e. `id` or `json`). We can later add the ability to have custom types, e.g. a `date` type with user-specified serialization and deserialization functions.

**Comment by stubailo** [comment]
Looks good to me 👍

**Comment by Poincare** [comment]
Done with #389
