### ISSUE TITLE
Don't apply queryTransforms to the first level

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#413]
If we have an `addTypename` transform, we want this:

```graphql
{
  myRootField {
    stuff
  }
}
```

To become this:

```graphql
{
  myRootField {
    __typename
    stuff
  }
}
```

And not this:

```graphql
{
  __typename
  myRootField {
    __typename
    stuff
  }
}
```

So we don't want to add fields to the root mutation or root query selection set on operation definitions.

**Comment by Poincare** [comment]
Done with #463
