### ISSUE TITLE
Catching errors

### ISSUE THREAD

**Issue by tomitrescak** [apollostack/apollo-client#420]
Hi, previously the errors in query made it to the view component so I could add a bit of functionality to view the error stack.

Now in query manager you reject the erroneous query and view component is never rendered:

```
.catch(function (error) {
                    _this.store.dispatch({
                        type: 'APOLLO_QUERY_ERROR',
                        error: error,
                        queryId: queryId,
                        requestId: requestId,
                    });
                    _this.removeFetchQueryPromise(requestId);
                    reject(new errors_1.ApolloError({
                        networkError: error,
                    }));
                });
```

I am using react to render my components with `mapQueriesToProps`.
How can I catch errors coming from the Apollo while using react-apollo?

Thanks

**Comment by tomitrescak** [comment]
Never mind. It was only Redux acting up.

**Comment by stubailo** [comment]
There's some really hard to track down bug here that might be relevant: https://github.com/apollostack/react-apollo/issues/57
