### ISSUE TITLE
Idea: flatten arrays of fragments when querying

### ISSUE THREAD

**Issue by nevir** [apollostack/apollo-client#421]
Because `createFragment` returns an array of fragments, you've got to be a bit careful when passing around its result - particularly when you're composing several fragments together:

```js
const fragmentOne = createFragment(gql`
  fragment fragmentOne on Thing { 
      foo 
    }
`);
const fragmentTwo = createFragment(gql`
  fragment fragmentTwo on Thing { 
      ...fragmentOne
      bar
    }
`, fragmentOne); // It'd be nice to also support `[FragmentOne, ...]`
const fragmentThree = createFragment(gql`
  fragment fragmentThree on OtherThing { 
      foo
    }
`);

apollo.query(gql`{
  thing { 
    ...fragmentOne 
    other { 
      ...fragmentTwo
    }
  }
}`, [...fragmentOne, ...fragmentTwo]); // This expansion was surprising!
```

---

For this sort of situation, it'd be helpful if `createFragment` and `query` flattened out any nested arrays of `FragmentDefinition`s they got

**Comment by stubailo** [comment]
I thought it already did this, or at least that was definitely the intention. Could you PR a failing test case for this? Then @Poincare should look at it.

**Comment by nevir** [comment]
Yup!  Probably won't get around to that for a few days though

**Comment by stubailo** [comment]
OK we will hopefully get to it before then.

**Comment by Poincare** [comment]
Maybe I am misunderstanding the issue at hand but from the test added in #425, it seems that `createFragment` currently returns a flat array of `FragmentDefinition` instances. Could you check it out @nevir ?

**Comment by stubailo** [comment]
@Poincare wait.. I just realized your test tests something totally different. Can you write a test where you pass an array of fragments into `query`?

**Comment by nevir** [comment]
Ah, yeah, sorry, the case is more like this:

```
it('should always return a flat array of fragment defs', () => {
  const fragmentDoc1 = gql`
    fragment authorDetails on Author {
      firstName
      lastName
      ...otherAuthorDetails
    }`;
  const fragmentDoc2 = gql`
    fragment otherAuthorDetails on Author {
      address
    }`;
  const fragmentDoc3 = gql`
    fragment evenMoreAuthorDetails on Auth {
      rating
    }`;
  const fragments2 = createFragment(fragmentDoc2);
  const fragments3 = createFragment(fragmentDoc3);
  const fragments1 = createFragment(fragmentDoc1, [fragments2, fragments3]);
  assert.equal(fragments2.length, 1);
  assert.equal(fragments3.length, 1);
  assert.equal(fragments1.length, 3);
});
```

**Comment by Poincare** [comment]
Ah, got it. I had misunderstood the issue. I'll fix the test and add the array flattening.

**Comment by stubailo** [comment]
@Poincare I think you should be able to create a fragment that has a dependency on multiple other fragments - how would you do that without this nested array approach?

I would definitely expect @nevir's approach to work.

Also, can't we just add one more level of possible nesting? I don't think it has to be arbitrary, just one more level.

**Comment by Poincare** [comment]
@stubailo 

So, we could do dependencies on other fragments by doing this:

```
fragments = createFragment(fragmentDoc1);
fragments = createFragment(fragmentDoc2, fragments)
fragments = createFragment(fragmentDoc3, fragments)
```

This declares a dependency between `fragmentDoc1`, `fragmentDoc2`, `fragmentDoc3`. @nevir's approach could work as well and I think doubly nested arrays should work as long as no one tries to use something like `[fragment1, [fragment2, fragment3]` to create a dependency structure. 

I think the key distinction is that the approach without any nesting,  it is clear `createFragment` returns a list of fragments you pass around. With nesting, we make it seem as if `createFragment` is returning a single fragment which you can then put together with other fragments. 

I'm fine with both approaches. We should probably do whichever is easier to use at the view layer level.

**Comment by stubailo** [comment]
@Poincare I'd really like to do the nested array approach - that seems the most natural to me, rather than having to call createFragment multiple times.

**Comment by Poincare** [comment]
See #437 for fix

**Comment by nevir** [comment]
Sweet, thanks for the quick turnaround!

**Comment by dminkovsky** [comment]
Is this still implemented somehow in v3? Not finding this functionality anywhere, including the babel transforms etc.
