### ISSUE TITLE
Wrong paths in definition file causing errors

### ISSUE THREAD

**Issue by drejohnson** [apollostack/apollo-client#429]
Wrong paths in definition file: node_modules/apollo-client/index.d.ts
```
import { QueryManager } from '../src/QueryManager';
import { ObservableQuery } from '../src/ObservableQuery';
```

Should be:
```
import { QueryManager } from './QueryManager';
import { ObservableQuery } from './ObservableQuery';
```
```
ERROR in [default] /home/dre/workspaces/angularjs/universal-starter-app/node_modules/apollo-client/index.d.ts:49:26 
Cannot find name 'WatchQueryOptions'.

ERROR in [default] /home/dre/workspaces/angularjs/universal-starter-app/node_modules/apollo-client/index.d.ts:49:48 
Cannot find name 'ObservableQuery'.

ERROR in [default] /home/dre/workspaces/angularjs/universal-starter-app/node_modules/apollo-client/index.d.ts:50:21 
Cannot find name 'WatchQueryOptions'.

ERROR in [default] /home/dre/workspaces/angularjs/universal-starter-app/node_modules/apollo-client/middleware.d.ts:4:13 
Cannot find name 'RequestInit'.

ERROR in [default] /home/dre/workspaces/angularjs/universal-starter-app/node_modules/apollo-client/networkInterface.d.ts:25:11 
Cannot find name 'RequestInit'.

ERROR in [default] /home/dre/workspaces/angularjs/universal-starter-app/node_modules/apollo-client/networkInterface.d.ts:31:13 
Cannot find name 'RequestInit'.

ERROR in [default] /home/dre/workspaces/angularjs/universal-starter-app/node_modules/apollo-client/networkInterface.d.ts:35:67 
Cannot find name 'RequestInit'.
```

**Comment by kamilkisiela** [comment]
Should be fixed by #428

**Comment by drejohnson** [comment]
Nice! What about the ```Cannot find name 'RequestInit'```?

**Comment by kamilkisiela** [comment]
You should install typings for fetch pollyfil that you're using. See chapter [_"Fetch Polyfill"_](http://docs.apollostack.com/apollo-client/core.html#fetch-polyfill) from docs.

It doesn't really matter if you're using `whatwg-fetch` package and typings for `isomorphic-fetch` package, you can install typings globally for one of these node modules.

I did it in Angular2 version of GitHunt, [see the typings](https://github.com/apollostack/GitHunt-angular2/blob/master/typings.json#L4).

You can always take a look at GitHunt to see how we're using ApolloClient in an example app (both versions): 
- [Angular2](https://github.com/apollostack/GitHunt-angular2)
- [React](https://github.com/apollostack/GitHunt)

**Comment by drejohnson** [comment]
Got it thanks!
