### ISSUE TITLE
Apollo-client for Elm?

### ISSUE THREAD

**Issue by yanisurbis** [apollostack/apollo-client#432]
Did you think about that? =)

**Comment by stubailo** [comment]
Never used Elm - can you use NPM packages?

**Comment by yanisurbis** [comment]
No, we haven't, we have elm packages. But several days ago was the announcement of react-elm-components (https://github.com/evancz/react-elm-components) which I missed, so... we can use Appolo now. Thanks for your response.

**Comment by stubailo** [comment]
Great! Let me know if I can help in any way.

**Comment by Gregoirevda** [comment]
This package is meant to integrate Elm in a React App to try it out. 
There is an Elm  [utility package](http://package.elm-lang.org/packages/jahewson/elm-graphql-module/1.0.0/GraphQL) for graphQL queries/mutations.
