### ISSUE TITLE
Set up CI test coverage report

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#44]
I think there are services that can take our test coverage report and make it look nice so that we can just click to see a page where we can think about what tests might be good to add. Would be good to get source maps in there as well.

**Comment by jbaxleyiii** [comment]
I haven't used it before but https://codeclimate.com/oss looks pretty great

**Comment by stubailo** [comment]
Wow, that was easy! Thanks for the suggestion. Check out the page here:

https://codeclimate.com/github/apollostack/apollo-client/coverage

**Comment by stubailo** [comment]
Hmm, I think I partied too early - I can't find any way to actually see the annotations there... when you look at the coverage file locally you can look at the code and stuff:

```
# in the repo, after running tests locally with npm test:
open coverage/lcov-report/index.html
```

Looks like this:

<img width="699" alt="screenshot 2016-03-27 17 48 57" src="https://cloud.githubusercontent.com/assets/448783/14068834/3a727676-f444-11e5-8b1b-1bfa44239637.png">

Would be really neat to be able to browse a report like that online... although having the stats listed on the repo is a good start.

**Comment by jbaxleyiii** [comment]
@stubailo another service to the rescue! Also free for open source and used with react :+1: 

https://coveralls.io/
[React Coverage](https://coveralls.io/github/facebook/react)

**Comment by stubailo** [comment]
MORE SERVICES PLEASE

OK let's try that one, they probably know what they are doing!

**Comment by stubailo** [comment]
OK, almost there - I think I do actually need to set up source maps to be able to see a report: https://coveralls.io/builds/5564180/source?filename=lib%2Fsrc%2Fstore.js

**Comment by stubailo** [comment]
Done! And it shows the original code not the compiled version! https://coveralls.io/builds/5564257/source?filename=src%2Fparser.ts

Except now the test fails sporadically since the service isn't reliable, which is ironic I guess?

Seems like a lot of people are getting a similar error - "Couldn't find a repository matching this job." - very sporadically. Let's see if it becomes a problem!
