### ISSUE TITLE
Mutation's invalidateQueries option

### ISSUE THREAD

**Issue by Slava** [apollostack/apollo-client#448]
Right now, a mutation allows you to specify how to update the results of certain queries by supplying a reducer function.

But if it is too complicated, or you just don't care enough to do it, the right way would be to refetch the whole query from scratch. Right now, there is no easy way to do that, but implementing it should be relatively easy:

```js
client.mutate({
  query: gql`...`,
  variables: {/* ... */},
  updateQueries: {/* ... */},
  invalidateQueries: {
    nameOfSomeQuery: true,
  }
});
```

**Comment by Poincare** [comment]
Merged with #482
