### ISSUE TITLE
A proposal for Computed Views

### ISSUE THREAD

**Issue by Slava** [apollostack/apollo-client#455]
There is a need for a higher-level abstraction to work with graphql queries, accumulating some state, and binding to a UI component.

The use-cases that we think it will solve are: pagination, infinite scrolling, anything else?

What a "Computed View" represents:
- rendering a single component, composed of result of multiple queries over time
- some state that is accumulated
- an initial query that defines the shape of the state
- a way to trigger additional queries (like "fetch more" or "load a different page")
- a computed view must have a "reducer" function that takes the old state and updates it with the newer query result

Implementation details:
- has a name
- Computed View has a separate cache-key category in the internal store
- the state of the view is normalized into redux store (?)

## Mutations

As of today, mutations have a way to update a result of a query. Since the computed view is composed of multiple (possibly different) queries, we should provide a way for mutations to update the computed views separately from queries.

```js
client.mutate({
  mutation: gql`...`,
  variables: {/*...*/},
  updateQueries: {/* ... */},
  updateComputedViews: {
    feedPaginated: (previousState, { mutationResult, computedView }) => {
       // ... update the state and return a new state here ...
    },
  },
});
```

## Cache Invalidation

Somehow there probably should be a way to force refetch (start from scratch) for the entire computedView and its queries.

## An example

In this example, there is a feed that keeps fetching a page by page result. The state always keeps track of the last fetched page. There is only one query that keeps populating the state `loadPage` that needs a variable.

```js
const pagination = client.createComputedView('feedPaginated', {
  initState: { currentPage: 0, feedItems: [] },
  queries: {
    loadPage: {
      query: gql`
        query fetchPage($pageIndex: Int!) {
          feedItems(page: $pageIndex) {
            id
            content
            title
            media {
              url
              id
            }
          }
        }
      `,
      variables: {
        /* no variables here, but extra variables can be passed later */
      },
    }
  },
  updateFromQuery: (prevState, { queryName, queryResult, variables }) {
    return {
      currentPage: variables.pageIndex,
      feedItems: [...prevState.feedItems, ...queryResult.fetchPage.feedItems],
    };
  }
});

// initial page load
pagination.fetch('loadPage', { variables: { pageIndex: 1 } });

// ...
// later to load next page
// ...
pagination.fetch('loadPage', {
  variables: {
    pageIndex: pagination.state.currentPage + 1
  }
});
```

**Comment by rricard** [comment]
I feel like splitting the state is not necessarily a great idea considering that the Redux store is usually a good single source of truth. What I like about apollo is this central store and I feel like this would break that by adding another state layer. However I'm not a core dev and maybe you have other goals than I have, rendering this proposal more necessary...

Note that at some point, in my pagination proposal, I want to expose a merging mechanism to the user in the following form: `(currentList, newElements) => nextList`. The only thing I didn't quite figured out yet is how to handle serialization of functions in general to store the function associated to the query into the apollo store (and obviously, I need to wait for #374, #453 & #454 to get merged first)

**Comment by dbx834** [comment]
Hi, I just stumbled across this post. What is your view on this - [Apollo-Paginate Example](http://sandbox.xn--kla-1oa.com/data-emulation/paginate) @rricard and @Slava?

**Comment by Slava** [comment]
@dbx834 looks like the example that you linked uses Redux to store the intermediate state. In practice, this proposal offers to do the same, just with a little bit less boilerplate and an "opinionated and official way" to do pagination. I think other than that, this proposal is thinking in the same line with your example?

@rricard I will need to re-read your proposal for `fetchMore`, so far I don't understand much from just reading the diff. Do you not store any additional state? It sounds like by introducing "silent arguments" you introduce more complexity to the cache layer, since not it will be more complicated to keep it consistent. This proposal adds another layer of state, which also adds complexity, but I believe it is still more isolated.

**Comment by rricard** [comment]
@dbx834 - My goal is to get an infinite pagination system (this one is cool but it actually creates a new hierarchy in the store, therefore, not allowing infinite pagination easily in situations such as react-apollo)

**Comment by Slava** [comment]
@rricard 

After thinking more about this feature and possible other solutions for pagination, I think this proposal is describing something that is adding complexity and is not solving the problem in hands (pagination) well.

Multiple questions arose when I was working on an implementation for this proposal:
- are the queries issued by a computed view observed or not?
- how is the queries cache coordinated with the computed views cache?
- do computed view results reuse the cached objects from the query results cache?

@stubailo and I were talking more about it off GitHub and decided that we will go developing the `fetchMore` feature more, nailing down the details of API and the implementation. Since we want to ship pagination soon, we would appreciate if we could get your input on the feature off GitHub. Either on Slack or on a call, for efficiency. We would write down all decisions and reasoning and publish to an issue on GitHub.

**Comment by rricard** [comment]
@Slava, that works for me. I agree we need to be precise with the API. While implementing the smaller PRs though, I had some ideas to make that better though. Can't wait to talk to you guys about it.
