### ISSUE TITLE
[0.4.8] Cannot read property 'forEach' of undefined at Object.createFragmentMap when doing updateQueries

### ISSUE THREAD

**Issue by HriBB** [apollostack/apollo-client#470]
I get APOLLO_MUTATION_ERROR when I do `updateQueries` after a successful server mutation.

```
stack:"TypeError: Cannot read property 'forEach' of undefined at Object.createFragmentMap (http://localhost:3000/static/bundle.js:57893:15)
at Object.mutationResultQueryResultReducer [as QUERY_RESULT] (http://localhost:3000/static/bundle.js:65351:36)
at http://localhost:3000/static/bundle.js:62322:103
at Array.forEach (native)
at Object.data (http://localhost:3000/static/bundle.js:62312:46)
at apolloReducer (http://localhost:3000/static/bundle.js:62220:28)
at combination (http://localhost:3000/static/bundle.js:40468:30)
at computeNextEntry (http://localhost:3000/static/bundle.js:97720:22)
at recomputeStates (http://localhost:3000/static/bundle.js:97774:18)
at http://localhost:3000/static/bundle.js:98019:23"
message:"Cannot read property 'forEach' of undefined"
```

This is my mutation

```
function mapMutationsToProps({ ownProps, state }) {
  return {
    editBrand: (id, title, description) => ({
      mutation: gql`
        mutation editBrand($id: Int!, $title: String!, $description: String) {
          editBrand(id: $id, title: $title, description: $description) {
            id title description
          }
        }
      `,
      variables: { id, title, description },
      updateQueries: {
        brand: (prev, { mutationResult }) => {
          console.log('==> updateQueries brand', prev, mutationResult);
          const ret = Object.assign({}, prev, {
            brand: mutationResult.data.editBrand
          })
          //debugger
          console.log('==> updateQueries return', ret);
          return ret
        },
      },
    }),
  }
}
```

`fragments` variable is undefined in `createFragmentMap` [here](https://github.com/apollostack/apollo-client/blob/master/src/queries/getFromAST.ts#L116)

Any ideas???

**Comment by HriBB** [comment]
The problem goes away if I add `fragments: []` to `mapQueriesToProps`

```
function mapQueriesToProps({ ownProps, state }) {
  const { brand: { edit } } = state
  if (!edit) return
  return {
    brand: {
      query: gql`
        query brand($id: Int!) {
          brand(id: $id) {
            id title description
          }
        }
      `,
      variables: { id: edit.id },
      fragments: [], // <== here
    }
  }
}
```

I will leave this open until we can confirm whether this is a bug or not.

**Comment by stubailo** [comment]
Thanks for the report! We will look into it ASAP. Thanks for giving `updateQueries` a try!

**Comment by HriBB** [comment]
@stubailo I got it working now, but I had to add `fragments: []` to all my `mapQueriesToProps` queries.

Just for the reference, if anyone is interested in `updateQueries`, this is my final implementation


```
onSubmit = (fields) => {
  const { edit, close, mutations } = this.props
  const brand = Object.assign(edit, fields)
  console.log('==> edit brand', brand)
  return mutations
    .editBrand(brand.id, brand.title, brand.description)
    .then(({ data: { editBrand }, errors }) => {
      if (errors) {
        console.log('==> errors', errors)
        throw new SubmissionError({ _error: errors })
      }
      if (editBrand) {
        console.log('==> success', editBrand)
        setTimeout(close, 250)
        return editBrand
      }
    })
}

function mapQueriesToProps({ ownProps, state }) {
  const { brand: { edit } } = state
  if (!edit) return
  return {
    brand: {
      query: gql`
        query brand($id: Int!) {
          brand(id: $id) {
            id title description
          }
        }
      `,
      variables: { id: edit.id },
      fragments: [],
    }
  }
}

function mapMutationsToProps({ ownProps, state }) {
  return {
    editBrand: (id, title, description) => ({
      mutation: gql`
        mutation editBrand($id: Int!, $title: String!, $description: String) {
          editBrand(id: $id, title: $title, description: $description) {
            id title description
          }
        }
      `,
      variables: { id, title, description },
      updateQueries: {
        brand: (prev, { mutationResult }) => {
          return Object.assign({}, prev, {
            brand: mutationResult.data.editBrand
          })
        },
        brands: (prev, { mutationResult }) => {
          const editBrand = mutationResult.data.editBrand
          return Object.assign({}, prev, {
            brands: prev.brands.map(brand => {
              if (brand.id === editBrand.id) {
                return Object.assign({}, brand, editBrand)
              }
              return brand
            })
          })
        },
      },
    }),
  }
}
```

Perfect! I love it! Good job apollo team!

**Comment by stubailo** [comment]
Hey, @HriBB heads up, you might be able to use this feature instead: http://docs.apollostack.com/apollo-client/mutations.html#new-object-or-updated-fields

Since all you're doing is updating fields on a brand object, and that has an `id` on it, you can probably skip writing the updateQueries stuff entirely!

**Comment by HriBB** [comment]
@stubailo yes, I've read about it and tried it out really quickly, but I'm not sure how to write `dataIdFromObject` function. Are there any examples?

**Comment by HriBB** [comment]
Using such a function ...
```
const dataIdFromObject = obj => {
  return `${obj.id}`
}
```

... does not work well in my case.

![apollo](https://cloud.githubusercontent.com/assets/4412324/17160343/98e012ee-53a4-11e6-8a03-6e147a1191b9.png)

Data is overwritten and merged ... I don't get it :) Do I need a unique ID for every object in the GraphQL?

**Comment by stubailo** [comment]
Just use the typename in there as well. check out the githunt example - you can automatically add typenames to your query, and then use them in your ID!

**Comment by HriBB** [comment]
It works! I don't need `updateQueries` anymore. This is so awesome! I'm always happy when I remove alot of code and everything still works :)

Just for reference, check out [GitHunt](https://github.com/apollostack/GitHunt/blob/master/ui/index.js) example for `dataIdFromObject` implementation. Be sure to add `queryTransformer: addTypename` to ApolloClient to be able to access `result.__typename`.

Thanks @stubailo

**Comment by stubailo** [comment]
So we attempted to document this here: http://docs.apollostack.com/apollo-client/mutations.html#new-object-or-updated-fields

Can you help us improve this information so that it would be easier for others to find it in the future?

**Comment by HriBB** [comment]
I'm more of a source code kinda guy, so I would provide a simple example (taken from GitHunt)
```
import ApolloClient, { createNetworkInterface, addTypename } from 'apollo-client';

const client = new ApolloClient({
  networkInterface: createNetworkInterface('/graphql', {
    credentials: 'same-origin',
  }),
  queryTransformer: addTypename,
  dataIdFromObject: (result) => {
    if (result.id && result.__typename) {
      return result.__typename + result.id;
    }
    return null;
  },
  shouldBatch: true,
});
```

I would point out that string returned by `dataIdFromObject` needs to be globally unique. With `__typename` this should be much more obvious. I would simplify the part where you explain that if you have `dataIdFromObject` defined, you don't need to `updateQueries` when you simply update fields. 

The docs are really not that bad. We just need a few more examples here and there, and maybe some explanations in simple words.

Let me know if I can help further ;)
