### ISSUE TITLE
Exceptions within updateQueries reducer are swallowed silently

### ISSUE THREAD

**Issue by stretchkennedy** [apollostack/apollo-client#479]
At https://github.com/apollostack/apollo-client/blob/master/src/QueryManager.ts#L261 all errors are caught and turned into `APOLLO_MUTATION_ERROR` actions, which aren't logged by the crashReporter or by anything else, but are passed through to the wrapped component. This includes errors from `collectResultBehaviorsFromUpdateQueries` and thus from `updateQueries`, making it hard to tell when a reducer is broken.

I was going to create a pull request, but I'm not sure where or how these errors should be logged.

**Comment by stubailo** [comment]
Merged a PR to log them using `console.error`. If we come up with a better way, I'd be happy to do it as well.
