### ISSUE TITLE
Maximum cache size 

### ISSUE THREAD

**Issue by daimeng** [apollostack/apollo-client#481]
Quick question, how is cache eviction handled? I'm unable to find any information on it.

**Comment by helfer** [comment]
Apollo Client currently doesn't do automatic cache eviction (and neither does Relay, for that matter).

So far it hasn't been an issue for anyone, so we're treating this as a low-priority feature, to be implemented at some point in the future

If you have a specific use-case that needs a cache eviction strategy, we'd love to know more about it.

**Comment by Poincare** [comment]
If you want to empty the cache entirely (e.g. on logout), you can use `resetStore`.

**Comment by daimeng** [comment]
Thanks, this is not a pressing concern, I don't have any concrete issues yet. Mostly just curious. I eventually will have a lot of data points being pulled in for graphs. So if I understand the caching correctly, there is some caching by entire query string and caching by parsing/interpreting the query. I was worried primarily about the former.


I wanted the reporting data to be cached and stay around for only a short while (in case user clicks back and forth). Is there a way to reset say all caching on a query named 'getReportingA' and leave other caches alone?


Another question while we're on the topic. I'm curious about your guys' thoughts on the general approaches to caching. From what I understand Falcor is a write-behind cache by default. Libraries like Apollo or Relay are write-through. What was the main reason for going with the second strategy? I have a feeling it is partially due to the easy abstraction graphql provides (it's a query language like SQL, but I prefer not writing direct SQL), but issues like optimistic update seem more complicated than rollback on error.

**Comment by Poincare** [comment]
There isn't really a simple way to "time out" data in the cache right now due to the fact that you could just refetch the data whenever you need it again and Apollo Client will ignore whatever is in the cache. 

We use a write-through cache simply because it is pretty natural for the GraphQL usecase. At the end of the day, there is a tradeoff; if we elected to make optimistic updates simpler, we would probably end up having more difficulty implementing stuff like offline or degraded connectivity support.

**Comment by probablyup** [comment]
An LRU implementation seems like a natural choice for the gql cache. Is there a good place to request that as a feature?

I definitely agree with the write-through philosophy for optimistic updates, but I'm sure there are ways to limit overall storage in a reasonable way.
