### ISSUE TITLE
Unexpected error in watch query, when another query updates a subset of the selection

### ISSUE THREAD

**Issue by igrayson** [apollostack/apollo-client#487]
1. When running watchQuery on this query...
   ```
  query watchDeeply {
    mainTodoList {
      id
      title
      contributor {
        id
        firstName
      }
    }
  }
```

2. ... the entity initially doesn't exist, so watchDeeply gets callback:
> next({ "myTodoList": null })

3. Something persists mainTodoList in the data source.

4. Another query loads *some* of now-existent mainTodoList:
  ```
  query loadPartial {
    mainTodoList {
      id
      title
    }
  }
```

5. Meanwhile, `watchDeeply` receives:

   > error( ApolloError {message:'Can't find field contributor on object {"id":"someId","__typename":"TodoList","title":"foo title"}\nPerhaps you want to use the `returnPartialData` option?'} )

**Comment by stubailo** [comment]
What would you expect to happen in this situation? I guess we could simply not return any data, or you could use `returnPartialData` to just get whatever exists. Thoughts?

**Comment by Poincare** [comment]
I think `returnPartialData` is the right solution here. The query _should_ error if it can't find a particular field unless you tell Apollo Client that you're okay with not getting the full query results.

**Comment by igrayson** [comment]
> What would you expect to happen in this situation? I guess we could simply not return any data, or you could use returnPartialData to just get whatever exists. Thoughts?

You guessed it. If I specify `returnPartialData`, it should (and does) return partial data. No problem there.

The problem is that I don't _want_ partial data (and I did not set that flag). In this case, I expect to receive no callback when some other query populates some -- but not enough to be valid without `returnPartialData` -- fields.

**Comment by helfer** [comment]
Closing this in favor of #818 which is just another version of the same issue.
