### ISSUE TITLE
Proposal: Mutation/FetchMore-like query reducer after receiving results of a query

### ISSUE THREAD

**Issue by rricard** [apollostack/apollo-client#495]
In the recently introduced Mutation and pagination mechanisms, we have the possibility to apply a "reducer" on the query results. This allows for instance to merge mutation results inside of the store or concat and sort two lists (pagination).

However, there is currently no way of applying a function on the results when the query is created (for example for sorting). Yes, this could be achieved in a react component for example but I think that being able to transform query results after retrieval could be useful.

**Comment by rricard** [comment]
This mechanism could for example let the user control the update from a previous query state and also control how a refetch is done.

**Comment by stubailo** [comment]
Can you give me an example of when this would be useful? Is it only for sorting? I'd like to think about a few more use cases before settling on a design.

**Comment by rricard** [comment]
For now, I only see sorting (what actually I would need it for) but I'll try to thing about other use cases. If we do that, I agree, it has to be useful but I'm sure there are some other cases where it could make sense too.

**Comment by Slava** [comment]
tracking this in #506

**Comment by Slava** [comment]
We  merged #506.

**Comment by rricard** [comment]
@Slava thanks!
