### ISSUE TITLE
Support batching with new Apollo Server

### ISSUE THREAD

**Issue by helfer** [apollostack/apollo-client#505]
Instead of mangling the queries, clients which connect to Apollo server v0.2.1 and above should be able to make use of the clean batching interface that it provides. This will require adding an option to the batching network interface.

**Comment by stubailo** [comment]
Also something to think about: https://github.com/graphql/express-graphql/pull/100

**Comment by Poincare** [comment]
@helfer 

Do we want to identify whether the server supports batching via a header or just leave it as a user-specified option?

**Comment by helfer** [comment]
@Poincare I think we can make it a user-defined option for the time being. Adding custom headers is a bit more work, and I think it only makes sense once this feature (and others) have settled a bit.

**Comment by Poincare** [comment]
Sounds good. I can work on this.

**Comment by stubailo** [comment]
Yeah I don't think we want to get into client/server feature negotiation just yet...
