### ISSUE TITLE
About caching header

### ISSUE THREAD

**Issue by katopz** [apollostack/apollo-client#526]
Hi guys.

I try search through code about `etag` and `last-modified` but can't find any related.
IMHO Apollo take care of client and server so both headers are a "must have" to reduce latency.
So the question is can I expect this features or I've to implement it myself?

Thanks

**Comment by Poincare** [comment]
You can handle ETags and Last Modified pretty easily through middleware/afterware at the moment.

**Comment by katopz** [comment]
Cool thanks @Poincare I'll do it myself then. This should be fun. :)

**Comment by stubailo** [comment]
If you come up with a cool implementation, it would be cool to learn more about it!

**Comment by katopz** [comment]
@stubailo Sure thing, I'm half way done here on client side as middle/afterware, just need some decision on server side ATM https://github.com/apollostack/apollo-server/issues/96
