### ISSUE TITLE
CORS localhost loading props but calling ip not working

### ISSUE THREAD

**Issue by cristiandley** [apollostack/apollo-client#529]
Before upgrading Apollo/Meteor i could access my app from localhost:3000 or from other computer using my IP or from my computer using my own private IP. Now i can see the React dom but is not loading any data.

```
Failed to load resource: the server responded with a status of 405 (Method Not Allowed)
```

```
Fetch API cannot load http://localhost:3000/graphql. Response to preflight request doesn't pass access 

control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 

'http://my_beutiful_ip:3000' is therefore not allowed access. The response had HTTP status code 405. 

If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource 

with CORS disabled.
```

i can access my_ip:3000/graphql

is there any new configuration im missing ?

Thanks !

**Comment by stubailo** [comment]
Have you tried to CORS options as specified here? http://docs.apollostack.com/apollo-client/index.html#corsSupport

Otherwise, it might be that your server doesn't accept CORS requests. How have you hooked up GraphQL to your web server?

**Comment by cristiandley** [comment]
@stubailo  i tried this:

```
import { createApolloServer } from 'meteor/apollo';
//import cors from 'cors';

import schema from '../imports/api/schema';
import resolvers from '../imports/api/resolvers';


createApolloServer({
  graphiql: true,
  pretty: true,
  schema,
  resolvers,
});

//graphQLServer.use('*', cors());
```

what im trying to do is to get is `graphQLServer`... that is in the `createApolloServer`, but i couldn't import it.

**Comment by stubailo** [comment]
Hmm, I think this definitely should be in `meteor-integration`. I don't think it has anything to do with apollo client.

One option is to simply not use the `meteor/apollo` package, and just attach the `graphQLServer` to Meteor directly, as @jangerhofer mentioned on the other thread.

**Comment by tgoldenberg** [comment]
@stubailo The *CORS* support link is broken. Any help with this? I am using all npm packages in a Meteor app but getting the same error. Server is running fine at *localhost:8080/graphql*

**Comment by savovs** [comment]
Having the same problem, would love for the docs to have an example of how to enable cors.

**Comment by Rogant** [comment]
I have the same bug with Express and React
