### ISSUE TITLE
From one query result, updating other (watch) queries.

### ISSUE THREAD

**Issue by igrayson** [apollostack/apollo-client#530]
Hi guys. A few weeks ago, I had a discussion in slack `#general` about the best approach for this use case:

We have several watchQueries observing large lists of entities. When we receive a push notification that a new entity has been created, we want to fetch that new entity and update (append to) those watchQueries, without refetching their entire collections.

As of a few weeks ago, the best solution appeared to be to model that single-entity fetch as a mutation, and use `updateQueries` to iterate through and append to live, applicable watchQueries. It was also mentioned that `fetchMore` might solve this more nicely. Looking at the initial implementation of `fetchMore` (specifically, `updateQuery`), it looks like I’d have to keep a registry of active watchQueries myself, so as to call `updateQuery` on each of them?

Is there something else tracking a better story for this use-case?

**Comment by Poincare** [comment]
Generally, you should have a single (large) query you'd have to update with the new entity and the other smaller queries would get the update due to the reactive store if they are subsets of the larger query.

There are some cases where this won't happen automatically. For example, if you have a query that fetches all todo items, another that fetches only todo items of a certain type and you fire off a query that gets a new todo item of the special type, you'll have to `fetchMore` on both of the queries since it isn't possible to automatically add the queries to both lists in a non-application-specific way.

If this is not possible, you could do what you just described. Would have any ideas as to how we could potentially improve this particular usecase?

**Comment by igrayson** [comment]
We have a `Todo` entity with a `state` attribute (a lengthy enum). Our apollo server exposes a `todos(stateGroup)` resolver, and several components of our app listen (`watchQuery`) to different `Todo` state groups, which overlap but are not strict super/subsets.

Some of these components are actual React components (typically list views), and some are background 'services' which need to act on CRUDs of `Todos` of a particular `stateGroup`.

Once we add push-notifications to this, some interesting complexities come up:

1. We want to insert novel `Todos` into the appropriate watchQueries that are already running, preferably without triggering a complete refetch of those queries. This probably means we have to re-implement some of the server-side resolver logic of `state -> stateGroup`, but this isn't terribly ugly. (same applies for deletions)

2. When we update a `Todo`, we want to re-evaluate _which_ queries it should subscribe to. This actually already seems to be a problem today: if one component performs a `todos('created')` query for a certain result set, and another component performs a `todo('123')` query (or mutation) which updates the local copy of `Todo` 123 to a state that is no longer `'created'`, the `todos('created')` query still includes that `Todo`. 

  This obviously can also happen if `todos('filter1')` yields a collection, and later `todos('filter2')` retrieves another collection which overlaps (and therefore _updates_) some of the entities in the first collection, possibly making them ineligible for `filter1` (but doesn't remove them from the query result).

  We overcome this today by doing "post-filtering" of apollo query results. Effectively, we endeavor to maintain our apollo query collections as _supersets_ of their original query parameters, and let the components consuming results do last-minute re-filtering.

3. Some of our queries might specify different selection sets. In order properly employ `updateQueries`, we have to have the right (or at least a superset?) of the selection set for that specific query. Not a big deal.

We're up-and-running with the `updateQueries` approach. Our push-notification listener performs a mutation, with a somewhat complex `updateQueries` block. We also track (i.e., keep a `Set()` of) all watchQueries that yield a `Todos` collection.

**Comment by helfer** [comment]
@igrayson in 0.5 you should be able to use the `reducer` option to watchQuery for this.
