### ISSUE TITLE
Unmet peer Depency

### ISSUE THREAD

**Issue by SerkanDayicik** [apollostack/apollo-client#533]
install following Docs http://docs.apollostack.com/apollo-client/angular2.html

if installed npm install angular2-apollo --save npm say cannot install apollo-client

after npm install apollo-client --save can install apollo-client but you run build app says  node_modules/apollo-client/QueryManager.d.ts(6,60): error TS2307: Cannot find module 'graphql'.

After this error i'm install Graphql on npm install graphql --save Error still same 
node_modules/apollo-client/QueryManager.d.ts(6,60): error TS2307: Cannot find module 'graphql'.

**Comment by kamilkisiela** [comment]
Typings for `graphql` are missing so try to run:

```
typings i -S graphql
```

**Comment by SerkanDayicik** [comment]
Thanks @kamilkisiela 
Problem solved but new error  Same folder QueryManager.d.ts

pollingTimers: {
        [queryId: string]: NodeJS.Timer | any;
    };

apollo-client/QueryManager.d.ts(16,28): error TS2503: Cannot find namespace 'NodeJS'

**Comment by kamilkisiela** [comment]
@SerkanDayicik Yes :) In one of the recent releases of `apollo-client` there was a change that requires to install typings for `nodejs`.

```
typings i -SG env~node
```

You can always take a look at the example projects that use `apollo-client`.

- [GitHunt | Angular2](https://github.com/apollostack/GitHunt-angular2)
- [GitHunt | React](https://github.com/apollostack/GitHunt)

**Comment by SerkanDayicik** [comment]
@kamilkisiela  Problem solved i try angular.rc.5 on apollo client but no luck Typings error coming all time maybe try starter project and update angular latest version thank you

**Comment by kamilkisiela** [comment]
@SerkanDayicik You can checkout my starter kit for `angular2-apollo`.

https://github.com/kamilkisiela/angular2-apollo-starter

**Comment by kamilkisiela** [comment]
But yes, RC5 breaks everything :) I'm going to work on it soon.
