### ISSUE TITLE
MockNetworkInterface returns same result even on different variables

### ISSUE THREAD

**Issue by kamilkisiela** [apollostack/apollo-client#535]
I'm trying to create a test for the new feature in `angula2-apollo` but I have a problem with current implementation of networkInterface's mock.

[The test](https://github.com/apollostack/angular2-apollo/blob/variable-observable/tests/angular2Apollo.ts#L95-L120)

It suppose to return `data2` on the first call and `data3` on the next one but I get `data2` every time.

I checked and it calls [`networkInterface.query`](https://github.com/apollostack/angular2-apollo/blob/variable-observable/tests/_mocks.ts#L62) only once.

Did some research and it seems like `ApolloClient.watchQuery` behaves the same way, so there's no issue with our Angular2 implementation.

Also, I've done some testing with real GraphQL endpoint and it works fine.

@Poincare Some ideas?

**Comment by kamilkisiela** [comment]
Something with caching, it works with `forceFetch`.

**Comment by stubailo** [comment]
The links in the original issue don't work anymore, so going to close this until it comes up again. Sorry about the late response.

**Comment by adambisek** [comment]
I've been struggling on this MockNetworkInterface and had to write my own MockNetworkInterface.
If anyone interested, here's the link: https://github.com/siteone/apollo-mocknetworkinterface
