### ISSUE TITLE
any idea for angular2 rc5 New module system ?

### ISSUE THREAD

**Issue by SerkanDayicik** [apollostack/apollo-client#541]
@NgModule({
  imports: [
    BrowserModule,
    routing
  ],
  declarations: [
    AppComponent,
    AnasayfaComponent,
    HakkimizdaComponent,
    HizmetlerimizComponent,
    FirmasorguComponent,
    AdsorguComponent,
    NumaradanisimComponent,
    TcknilesorguComponent,
    IletisimComponent,
    TarifelerComponent,
    TFirmaComponent,
    TisimComponent,
    TnumaraComponent,
    TtcknComponent
  ],
   providers: [
    appRoutingProviders
  ],
  bootstrap: [ AppComponent ]
})

**this new module how to can import client ?**

`const client = new ApolloClient({
  networkInterface: createNetworkInterface('http://localhost:8080')
});

bootstrap(<MyAppClass>, [
  APOLLO_PROVIDERS,
  defaultApolloClient(client)
  ]);`

**Comment by SerkanDayicik** [comment]
i solved this way

`import { NgModule } from '@angular/core';
import { BrowserModule }  from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { routing, appRoutingProviders } from './app.routes';


import { AnasayfaComponent } from './sayfalar/anasayfa/anasayfa.component';
import { HakkimizdaComponent } from './sayfalar/hakkimizda/hakkimizda.component';
import { HizmetlerimizComponent } from './sayfalar/hizmetlerimiz/hizmetlerimiz.component';
import { FirmasorguComponent } from './sayfalar/hizmetlerimiz/firmasorgulama/firmasorgulama.component';
import { AdsorguComponent } from './sayfalar/hizmetlerimiz/isimdennumara/isimdennumara.component';
import { NumaradanisimComponent } from './sayfalar/hizmetlerimiz/numaradanisim/numaradanisim.component';
import { TcknilesorguComponent } from './sayfalar/hizmetlerimiz/tcknilesorgu/tcknilesorgu.component';
import { IletisimComponent } from './sayfalar/iletisim/iletisim.component';
import { TarifelerComponent } from './sayfalar/tarifeler/tarifeler.component';
import { TFirmaComponent } from './sayfalar/tarifeler/firmasorgulama/tfirma.component';
import { TisimComponent } from './sayfalar/tarifeler/isimdenumara/tisim.component';
import { TnumaraComponent } from './sayfalar/tarifeler/numaradanisim/tnumaradan.component';
import { TtcknComponent } from './sayfalar/tarifeler/tcknilenumara/ttckn.component';

import { defaultApolloClient, APOLLO_PROVIDERS } from 'angular2-apollo';

import ApolloClient, { createNetworkInterface } from 'apollo-client';

const client = new ApolloClient({
  networkInterface: createNetworkInterface('http://localhost:8080')
});


@NgModule({
  imports: [
    BrowserModule,
    routing
  ],
  declarations: [
    AppComponent,
    AnasayfaComponent,
    HakkimizdaComponent,
    HizmetlerimizComponent,
    FirmasorguComponent,
    AdsorguComponent,
    NumaradanisimComponent,
    TcknilesorguComponent,
    IletisimComponent,
    TarifelerComponent,
    TFirmaComponent,
    TisimComponent,
    TnumaraComponent,
    TtcknComponent
  ],
   providers: [
    appRoutingProviders,
    APOLLO_PROVIDERS
  ],
  bootstrap: [ AppComponent, [defaultApolloClient(client)] ]
})

export class AppModule { }
`

**Comment by kamilkisiela** [comment]
@SerkanDayicik This would be available in the next release

https://github.com/apollostack/angular2-apollo/blob/master/CHANGELOG.md#vnext
