### ISSUE TITLE
Can't find a field on result object in fetchMore

### ISSUE THREAD

**Issue by gauravtiwari** [apollostack/apollo-client#544]
Folks, so I have this setup to fetch and paginate a collection of posts,
#### Posts Query:

``` js
const PostsQuery = gql` query getPosts($page: Int!) {
  total_pages,
  posts(page: $page) {
    id,
    title,
    body,
    excerpt,
    url,
    comments_count,
    user {
      id,
      name,
      email,
    }
  }
}`;

```
#### Initialise Query with variables

``` js
const PostsWithData = graphql(PostsQuery, {
  options: () => ({
    variables: {
      page: 1,
    },
  }),
})(PostsIndexComponent);
```
#### Mutate variables and fetch page 2

``` js
this.props.data.fetchMore({
        variables: { page: this.props.data.variables.page + 1 },
        updateQuery: (previousResult, { fetchMoreResult }) => {
          const newPosts = fetchMoreResult.data.posts;
          return {
            posts: [...previousResult.posts, ...newPosts],
          };
        },
      });
```

Initial render fetches and displays results fine, but when I do `fetchMore` with new page, this is the response received from server, 

![screen shot 2016-08-15 at 12 59 13](https://cloud.githubusercontent.com/assets/771039/17663917/37b8281e-62e8-11e6-9821-940a9ac8293d.png)

which looks correct, but on the client it throws following error,

![screen shot 2016-08-15 at 13 00 48](https://cloud.githubusercontent.com/assets/771039/17663934/53296cfc-62e8-11e6-89b1-c275ecc79be4.png)

From initial look it seems the reducer only sets the `posts` field data and query
![screen shot 2016-08-15 at 13 06 42](https://cloud.githubusercontent.com/assets/771039/17664064/3683c2e0-62e9-11e6-881b-e0ebed954ffc.png)

![screen shot 2016-08-15 at 13 08 23](https://cloud.githubusercontent.com/assets/771039/17664083/7040f1d8-62e9-11e6-9bef-0b5dfb23d1fa.png)

Any ideas?

**Comment by Slava** [comment]
Your reducer function should return a new document that has exact same shape as the original query result. In your code, you only return the `posts` field. Arguably, this should be fixed on the Apollo Client side by throwing a better error message, and put more emphasize on "reducer functions" in documentation.

**Comment by gauravtiwari** [comment]
@Slava You are right! That makes sense, but as your said this could be confusing, I think especially for someone who don't know much redux or just starting with Apollo. 

In the initial render/fetch there is no concept of reducer, it is introduced later in `fetchMore`. Is it not possible to use the same query to generate reducer unless a new query is provided in the `fetchMore` method, meaning it always expects the data in same shape as of `query`?

**Comment by Slava** [comment]
@gauravtiwari I think it is not as difficult as you might think. You can always reuse the structure of the `previousResult` that has the right shape, and then append the result of the `fetchMore` into the right place using things like [`update`](https://facebook.github.io/react/docs/update.html)

**Comment by gauravtiwari** [comment]
@Slava Absolutely! I agree, it's not that difficult and it will work, but considering the semantics of GraphQL, which works with a query, this flow is kind of odd. Please, forgive me if I am missing something bigger here. 

If we look at the following example with `react-apollo`, initially, we initialise the graphql with a query and a bunch of required variables,

```js
const PostsWithData = graphql(PostsQuery, {
  options: () => ({
    variables: {
      page: 1,
    },
  }),
})(PostsIndexComponent);
```
Which looks fine and it makes sense, but if we look at this one, 

```js
this.props.data.fetchMore({
        variables: { page: this.props.data.variables.page + 1 },
        updateQuery: (previousResult, { fetchMoreResult }) => {
          const newPosts = fetchMoreResult.data.posts;
          return {
            total_pages: previousResult.total_pages,
            posts: [...previousResult.posts, ...newPosts],
          };
        },
      });
```
up until variables it makes sense, because we are mutating that object, but after that it doesn't. The reason is we are not mutating query (perhaps `updateQuery` is not right function name) here, we are just saying give me the next set of posts and since everything is same the client should update the previous query with new variables and update the store with new results. I see, Relay works like this. 

The above approach is same as how we do things with Redux or even in simple react components, where we `concatenate` or `shift` `unshift` data. I think in future when the client will support things like fetching and caching with `documentID` and other fancy stuff this might need changing, because then it will become more complicated. 

Perhaps, a bit more sophisticated data fetching and merging is required here.

**Comment by calebmer** [comment]
I’m going to close this as this was an intentional design decision. At this point it’s well documented enough that we feel comfortable that these errors won’t be happening often. If you want to add a warning if we detect some missing fields that would be great :+1:
