### ISSUE TITLE
Null or undefined fragments throw a weird error

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#546]
Posted originally by @deoqc at https://github.com/apollostack/react-apollo/issues/143

> I tried to use fragments but got error `undefined is not an object (evaluating 'definition.kind')` in line 46 of `getFromAST.js`.

We should identify invalid fragments earlier and throw a better error.

**Comment by helfer** [comment]
We no longer deal with fragments directly, so I don't think this should be apollo-client's job any more.
