### ISSUE TITLE
Allow adding extra fields to the request body via middleware

### ISSUE THREAD

**Issue by bryanchriswhite** [apollostack/apollo-client#547]
As a part of my project's authentication I need to be able to add a `__nonce` property to the request body.

My initial approach looked something like this:

```javascript
  const apolloNetworkInterface = createNetworkInterface('http://localhost:1234/graphql');
  apolloNetworkInterface.use([{
    applyMiddleware(req, next) {
      req.request.__nonce = uuid.v4();
      // ...
      next();
    }
  }]);
```

However, this modification to the `req.request` object isn't persisted in the network request:
<img width="518" alt="screen shot 2016-08-16 at 10 30 42 am" src="https://cloud.githubusercontent.com/assets/600733/17692891/8b20f238-639c-11e6-9147-860d200ae346.png">

It looks like the reason for this is because before the request is actually sent out, it is processed by the `printRequest` function [here](https://github.com/apollostack/apollo-client/blob/master/src/networkInterface.ts#L165); the definition of which is [here](https://github.com/apollostack/apollo-client/blob/master/src/networkInterface.ts#L86). 

I'm not sure what the purpose of this function is except, possibly to produce the outcome that is actually the cause of my issue. So my main question, is: **Is this expected behavior?**

I'll be submitting a PR to "fix" this issue as it's the only way to currently work around my issue but I would like some feedback on what the purpose of `printRequest` is.

**Comment by bryanchriswhite** [comment]
Further, it looks like `printRequest` was added at 2a36e65, before which the request was just sent as is. This leads me to believe that there was a reason but it's still not clear to me.

**Comment by bryanchriswhite** [comment]
Update: I've since noticed the subtle `print(query)` and the corresponding type differences between the `Response` and `PrintedResponse` properties which may account for the existence of the `printResponse` method.

**Comment by bryanchriswhite** [comment]
As noted by the reference comments, I have the fix for this issue but am still working on adding tests for it.

**Comment by stubailo** [comment]
We have `printRequest` because the network interface actually gets the query AST, rather than the query string. It would be great to pass through any additional properties.

However, I think the best option is to use an HTTP header for this, instead of an extra field on the body.

**Comment by bryanchriswhite** [comment]
@stubailo I agree in principle that it would be best to stick to headers for this specific use case; however, our existing authentication mechanism as well as other use cases either can't or won't.

Regardless, thanks for the support 👍
