### ISSUE TITLE
Force fetch does not change loading state

### ISSUE THREAD

**Issue by tgdn** [apollostack/apollo-client#549]
Using apollo-client 0.4.11 and react apollo 0.4.5. I've got a basic component and a basic query

```

const Billing = props => {
    const {data} = props

    console.log(data.loading);
    return <div />
}

const GET_BILLING = gql`
query billing {
    me {
        customer {
            cards {
                id
                last4
                expMonth
                expYear
                brand
                createdAt
            }
            charges {
                id
                amount
                description
                paid
                createdAt
            }
        }
    }
}`

export default graphql(GET_BILLING, {
    options: (ownProps) => {
        return {
            forceFetch: true,
            returnPartialData: false
        }
    }
})(Billing)
```

However, `data.loading` is `true` only on the first roundtrip. Because I'm using react-router, whenever the view is unmounted and mounted again, when the query is sent again (after the first roundtrip), `data.loading` stays false and does not change back to true while the request is being sent.

`data.loading` is obviously connected to a loading indicator, but if it stays false when it is actually waiting for the server to respond then the view will just re-render like that without loading indicator which is not that great.

**Comment by stubailo** [comment]
I think this is more likely to be an issue with [react-apollo](https://github.com/apollostack/react-apollo) - could you post there please?

**Comment by webular** [comment]
@stubailo yep more info here:
https://github.com/apollostack/react-apollo/issues/228
