### ISSUE TITLE
batched queries do not handle errors correctly

### ISSUE THREAD

**Issue by jmiazga** [apollostack/apollo-client#551]
I have setup my backend to return an error for 2 separate queries. I made subsequent queries with the apollo client, and they were successfully batched together.  Both queries return and error, but each promise was resolved successfully.

If I turn off batching, two separate calls are made to the backend and each promise was rejected as expected.

Let me know if you need anymore information.

**Comment by stubailo** [comment]
@Poincare any thoughts? Perhaps in this case the best solution is to use #531 (transport batching, rather than query merging)

@jmiazga what GraphQL server are you using?

**Comment by Poincare** [comment]
I don't think there's a good solution to doing error handling (esp. network error handling) for query merging. The right way to do this is probably through #531 once it is merged (probably by the middle of next week).

The successfully resolved promises does seem like a bug, however. @jmiazga if you could add a test to `QueryManager` that reproduces that issue, that would be incredibly helpful!

**Comment by jmiazga** [comment]
@stubailo we are using graphql-java

@Poincare ill try to add one shortly
