### ISSUE TITLE
How to access redux store from middleware

### ISSUE THREAD

**Issue by blackxored** [apollostack/apollo-client#566]
How to access the redux store from middleware, since I'm storing the token required for authentication there?

**Comment by stubailo** [comment]
I think the best option is to reference the store directly, and call [getState()](http://redux.js.org/docs/api/Store.html#getState) on it.

Since the middleware isn't part of the UI component, you don't need to use something like `Provider` or dependency injection to do this.

**Comment by morgante** [comment]
@stubailo How would you suggest doing so?

The issue is that referencing the store directly from the middleware creates a cyclical dependency of store->middleware->client->store.

**Comment by matt-way** [comment]
@morgante Did you end up figuring out a nice way to do it? The only way I could achieve this was with a singleton store which I was trying to avoid.

**Comment by stubailo** [comment]
Couldn't you do something like this:

```js
function initClientAndStore() {
  const store = createStore(...);
  const networkInterface = createNetworkInterface(...);
  const client = new ApolloClient({ networkInterface });

  networkInterface.use([{
    applyMiddleware(req, next) { ... } 
  }]);
}
```

**Comment by matt-way** [comment]
@stubailo Thanks, exactly what I ended up doing. Just wasn't obvious that the `networkInterface` could have `use()` called after instantiating the client.

**Comment by peisenmann** [comment]
@matt-way @stubailo  Thanks. I was stuck on the whole cyclic dependency thing, too

**Comment by lifeiscontent** [comment]
@peisenmann @matt-way @stubailo how would you pass the apollo client into the store? I'm confused.

**Comment by avalla** [comment]
if anyone else had an issue using the network interface returned by addGraphQLSubscriptions, be sure to don't use it, use the original networkInterface returned by createNetworkInterface
