### ISSUE TITLE
resetStore method disappeared

### ISSUE THREAD

**Issue by Poincare** [apollostack/apollo-client#567]
There used to be a `resetStore` method inside the `ApolloClient` but that seems to have disappeared altogether due to some merge.

Should be an easy fix: the `resetStore` method inside `ApolloClient` should just call the `resetStore` method inside `this.queryManager`. Probably a test to go along with it.

**Comment by helfer** [comment]
Whoever does this should also figure out when it disappeared because that will help us prevent similar "accidents" in the future. Also curious to know why this wasn't caught by a test.

**Comment by stubailo** [comment]
I would guess we have a test for the `QueryManager` version but not the `ApolloClient` version.

**Comment by johnthepink** [comment]
Was it definitely called `resetStore`? I just did a search back through every commit, and the only `resetStore` I could find is on `QueryManager`:

```
git grep resetStore $(git rev-list --all)
```

grepping for `reset` returned a lot more results, but I didn't see anything interesting.

Maybe a rebase/force push somewhere is to blame?

**Comment by jbaxleyiii** [comment]
@johnthepink agreed, even the PR which added it is just on the manager https://github.com/apollostack/apollo-client/pull/314/files#diff-748b449db1e130c8d777fa1ffa1e0725R462

**Comment by gauravtiwari** [comment]
Did same thing a few days ago @johnthepink and looks like this never existed at the client level.

**Comment by Poincare** [comment]
I must have blotted it out with one of the rebases on that PR or forgotten to expose it at the client level. Thanks for fixing this though!

**Comment by stubailo** [comment]
@Poincare can you look at the PR?
