### ISSUE TITLE
after remount poll intervel is not working 

### ISSUE THREAD

**Issue by gmchaturvedi1** [apollostack/apollo-client#578]
i am setting pollintervel in  query but when i visited some other coment and mutate something and after return to the pollintervel componenet  then pollintervel is not working. 

kindly help me out on this. 

Regards
GM Chaturvedi

**Comment by jbaxleyiii** [comment]
@gmchaturvedi1 this should be fixed via https://github.com/apollostack/apollo-client/pull/568

can you update to apollo-client 0.4.13 and see if this still exists?

**Comment by gmchaturvedi1** [comment]
thanks now its working
