### ISSUE TITLE
Write simple arrays to store

### ISSUE THREAD

**Issue by johnthepink** [apollostack/apollo-client#58]
Currently there is an issue with writing simple arrays to the store. Arrays of objects work fine (`[{}, {},]`), but arrays of strings do not (`['one', 'two',]`). It throws this error:

```
TypeError: Cannot read property 'selections' of null
```

I played around in the tests, and it seems there is no issue reading an array of strings from the store once it is in there.

This seems like something it should support, and I'm going to work on a solution. Let me know if it's not. Thanks!

**Comment by stubailo** [comment]
Yeah that makes sense! Just an oversight. Probably step 1 is to write a failing test for this case.

**Comment by johnthepink** [comment]
@stubailo already on it :)

**Comment by stubailo** [comment]
This might mean we don't read those out of the store properly either, since the tests usually do both.

**Comment by stubailo** [comment]
If you're going to work on it, please assign the issue to yourself!

**Comment by johnthepink** [comment]
@stubailo It doesn't look like I have permission to do that, but feel free to assign me

**Comment by stubailo** [comment]
Just added you, and I made @jbaxleyiii an admin so that he can add additional collaborators if necessary!

**Comment by johnthepink** [comment]
Thanks!

**Comment by jbaxleyiii** [comment]
@johnthepink this is fixed yes?

**Comment by johnthepink** [comment]
@jbaxleyiii yessir. Closed via #66
