### ISSUE TITLE
Skip cache feature?

### ISSUE THREAD

**Issue by sandervanhooft** [apollostack/apollo-client#587]
Is there a way to skip the caching mechanism of the Apollo Client?

I presume the `forceFetch` option would still cache the query.

It may be an edge case, but I'm implementing a JWT login currently, would be best to not save the user password in cache IMHO.

**Comment by stubailo** [comment]
> would be best to not save the user password in cache IMHO.

The password is already in the client-side network logs, etc. So I don't really see how it's bad to save it in the cache.

But one thing you could do is call the network interface directly:

```js
client.networkInterface.query(...).then(...);
```

Then it doesn't pass through the cache at all. Does that work for you?

**Comment by sandervanhooft** [comment]
@stubailo It works, thank you!

> The password is already in the client-side network logs, etc
Security-wise, you're probably right - and that was the main reason to ask. However, as I store the token outside the Apollo state tree, there's no added value for keeping it in cache. That would mean I'll need to ForceFetch it on each token refresh.

Again, thanks for your solution, I'll close this issue.
