### ISSUE TITLE
updateQueries but like resolvers

### ISSUE THREAD

**Issue by hlehmann** [apollostack/apollo-client#596]
What do you think about mutation option `updateData` using the same shape than resolvers:

```
type Todo {
  id: ID
  message: String
  listId: ID
  list: TodoList
}

type TodoList {
  id: ID
  name: String
  todos: [Todo]
}

type Query {
  todos: [Todo]
  list: TodoList
}
```

``` typescript
@graphql(gql`
mutate addTodo($input: TodoInput!) {
  addTodo(input: $input) {
    id
    message
  }
`}, {
  options: () => ({
    updateData: {
      Query: {
        todos(state, {data}) {
          let todo = data.addTodo;
          state.push(todo);
          return state;
        }
      },
      TodoList: {
        todos(state, {root, data}) {
          let todo = data.addTodo;
          if (root.id === todo.listId) {
            state.push(todo)
          }
          return state;
        }
      }
    }
  })
}
```

In that way it's not necessary to refer to all query names but simply focus on the data and the schema

**Comment by helfer** [comment]
@hlehmann great idea, we're going to do something similar, but co-locate it with queries rather than mutations!

**Comment by stubailo** [comment]
This is a really cool idea, we should draw from it!

**Comment by hlehmann** [comment]
Cool to see an interest on this!

**Comment by hlehmann** [comment]
This version should be the easiest way to implement it but we could also make it in the apollo-client config or in the pub-sub system.

**Comment by helfer** [comment]
We've implemented something similar for queries now, and we're also working on refining the format for cache updates. I'm closing this so we can have all conversations in a more recent issue.
