### ISSUE TITLE
Issue with using fragment multiple times with query batching

### ISSUE THREAD

**Issue by dahjelle** [apollostack/apollo-client#598]
Hi! I was experimenting with turning query batching on, but ran into an issue getting:

```
TypeError: Cannot read property '___authorStuff___requestIndex_0___fieldIndex_4' of undefined
```

I have one query that use a fragment in two different locations. It appears that the `fieldIndex` values are being computed differently between the request and what the response-processing (in `unpackDataForRequest`?) is expecting. (While this isn't my actual query, I think (hope) it's a reduced example.)

# Query

```
query authorStuff {
  author {
    ...authorInfo
  }
  secondAuthor {
    ...authorInfo
  }
}
fragment authorInfo on RootQuery {
  firstName
  lastName
}
```

# “Batched” Query

```
query authorStuff {
  ___authorStuff___requestIndex_0___fieldIndex_0: author {
    ...___authorStuff___requestIndex_0___authorInfo
  }
  ___authorStuff___requestIndex_0___fieldIndex_1: secondAuthor {
    ...___authorStuff___requestIndex_0___authorInfo
  }
}

fragment ___authorStuff___requestIndex_0___authorInfo on RootQuery {
  ___authorStuff___requestIndex_0___fieldIndex_2: firstName
  ___authorStuff___requestIndex_0___fieldIndex_3: lastName
}
```

# Response

```
{
  data: {
    ___authorStuff___requestIndex_0___fieldIndex_0: {
      ___authorStuff___requestIndex_0___fieldIndex_2: 'John',
      ___authorStuff___requestIndex_0___fieldIndex_3: 'Smith',
    },
    ___authorStuff___requestIndex_0___fieldIndex_1: {
      ___authorStuff___requestIndex_0___fieldIndex_2: 'Joe',
      ___authorStuff___requestIndex_0___fieldIndex_3: 'Smith',
    },
  },
}
```

# Error

But I get an error that says:

```
TypeError: Cannot read property '___authorStuff___requestIndex_0___fieldIndex_4' of undefined
```

---

Is there something obvious I'm missing? Should I put the above into the `queryMerging.ts` tests and then see how we might fix it? I've experimented with some fixes, but I'm not sure I grok `unpackDataForRequest` enough yet to get a proper fix.

Or is there another approach I should be using?

**Comment by helfer** [comment]
Thanks for reporting this @dahjelle! It looks like you're doing everything right and this is clearly a bug in the query merging logic. There's some gnarly logic in there that we'll have to untangle, but for now the most useful thing would be if you could make a PR with a failing test case by using a query that's similar to yours. I suspect the issue arises when you have two fragments in two different root fields (just like in your query).

**Comment by dahjelle** [comment]
@helfer Added in #599. Let me know if it needs tweaking in any way to be useful.

>There's some gnarly logic in there that we'll have to untangle…

I took a couple stabs at it, but not much luck so far. :-)

**Comment by dahjelle** [comment]
Is the transport-level batching possible a solution for this, if that code is released in the near term? (I am using apollo-server, so the server supports it.)

**Comment by helfer** [comment]
@dahjelle Yeah, that would definitely solve the problem. We merged the transport batching PR, so the next version of Apollo Client will support it.

**Comment by dahjelle** [comment]
@helfer I tried the transport-level batching, but ran into some other issues—it appeared to not work when there was only a single query sent in a request instead of many? I will try nail down the details & create a separate issue for that later today & report back. :-)

**Comment by dahjelle** [comment]
@helfer Last comment on the transport-batching digression, but it appears that apollostack/apollo-server#123 fixes the transport-batching issue I had. :-)

**Comment by helfer** [comment]
Ok, so you were using hapi?

**Comment by dahjelle** [comment]
Correct.

**Comment by jamesreggio** [comment]
I'm not using HAPI and am encountering the same problem.

In case anybody else encounters this issue: the workaround for me has been to turn off `shouldBatch` in my `ApolloClient` instance.

Furthermore, [this line](https://github.com/apollostack/apollo-client/blob/da81f28fc01e02c40e9440b2a2863030fabf9a0f/src/batching/queryMerging.ts#L169) in `queryBatching.ts` is causing premature errors, because `data` will sometimes be `undefined`. (The `isNull` function returns `false` in that case, leading to an invalid object lookup in the latter arm of the ternary.) When I change the condition to `data == null`, the next set of issues I bump up against are those described by the original poster.

**Comment by helfer** [comment]
@jamesreggio if you're using apollo server, you could try turning on transport batching.

We might fix this when we refactor query merging, but it might take a while.

**Comment by jamesreggio** [comment]
Got it. We're not using Apollo Server, so I guess we'll just turn off all batching for a while.

**Comment by helfer** [comment]
Factored out query merging, track this issue on https://github.com/apollostack/query-merging/issues/1
