### ISSUE TITLE
Default network interface doesn't serialize values in a way compatible with graphql-dotnet

### ISSUE THREAD

**Issue by schlaup** [apollostack/apollo-client#600]
See GraphQLHub:

[GraphQL Tour: Variables](https://medium.com/the-graphqlhub/graphql-tour-variables-58c6abd10f56)

> How do we set the values for variables? The GraphQL spec doesn’t impose any constraints, similar to how it does not specify the mechanics of GraphQL requests in general. The GraphQL-JS ecosystem generally uses a separate JSON blob

Issuing the following query:

```
    const query = gql`
      query authorDetails ($id: String) {
        author(id: $id) {
          name
          books {
            id
            title
          }
        }
      }
    `;

    client.query({ query, variables: { id: 1 } })
```

The query should be:

`{"query":"query authorDetails($id: String) {\n  author(id: $id) {\n    name\n    books {\n      id\n      title\n    }\n  }\n}\n","variables":"{\n  \"id\": 1\n}","operationName":"authorDetails"}`

but it is:

`{"query":"query authorDetails($id: String) {\n  author(id: $id) {\n    name\n    books {\n      id\n      title\n    }\n  }\n}\n","variables":{"id":1},"operationName":"authorDetails"}`

The value of "variables" is not in quotes as it should be. It is JSON and not a JSON blob.

Therefore the GraphQL server that I am using does not find the variables when executing the query.

**Comment by helfer** [comment]
@schlaup What server are you using? The ones I know support both.

**Comment by schlaup** [comment]
GraphQL for .NET:

https://github.com/graphql-dotnet/graphql-dotnet

**Comment by stubailo** [comment]
It's unfortunate that there currently isn't a spec for how GraphQL stuff should be sent over HTTP.

**Comment by helfer** [comment]
@schlaup Maybe you could make a PR to graphql-dotnet that adds support for this? It would be a non-breaking change for that project, whereas in graphql-client we would have to make a breaking change.

**Comment by schlaup** [comment]
Ok, I can "fix" it in graphql-dotnet.

Wouldn't it be useful to add an option or hook to Apollo Client?

If there is no spec how the query should be send over HTTP and there are two "standards" right now, it would be helpful that we could influence how the data is transmitted.

Does Relay encode the variables as JSON or as a JSON blob? I believe Facebook uses JSON blobs, right?

**Comment by stubailo** [comment]
@schlaup you can easily override the `query` method on the network interface to send the request however you like: http://docs.apollostack.com/apollo-client/network.html

**Comment by schlaup** [comment]
@stubailo I looked at the networkInterface.ts code and it seems it would be easier if I could exchange the printRequest() method.

printRequest() is not part of the class - so it is not possible to inherit from HTTPFetchNetworkInterface and overwrite printRequest(). I would have to overwrite fetchFromRemoteEndpoint() and reimplement everything just to call my own printRequest() method.

Wouldn't it be better if we had an options.printRequest for the normal NetworkInterface that we could pass to createNetworkInterface()?.

For example:

```
export interface NetworkInterfaceOptions {
  uri: string;
  opts?: RequestInit;
  transportBatching?: boolean;
  printRequest?: (request: Request) => PrintedRequest;
}
```

**Comment by stubailo** [comment]
Sure, it would be great to have that option! Mind submitting a PR to add it?

**Comment by stubailo** [comment]
graphql.org now suggests serializing values in the way that Apollo Client does it by default, and GraphiQL has been changed as well. So I would suggest modifying the way the server handles it.

**Comment by mikeisman** [comment]
If anyone comes across this issue before their server can be updated, check out this issue which has a simple solution using middleware: https://github.com/apollostack/apollo-client/issues/881

**Comment by yechezkelbr** [comment]
Hi,
This is what I did to solve this issue in graphql-dotnet
change the default serialization converter for GraphQLQuery class

`   
public class GraphQLQueryConverter : JsonConverter
    {
        public override bool CanConvert(System.Type objectType)
        {
            throw new NotImplementedException();
        }

        public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer)
        {
            object instance = objectType.GetConstructor(System.Type.EmptyTypes).Invoke(null);
            PropertyInfo[] props = objectType.GetProperties();

            JObject jo = JObject.Load(reader);

            foreach (JProperty jp in jo.Properties())
            {
                string name = Regex.Replace(jp.Name, "[^A-Za-z0-9]+", "");

                PropertyInfo prop = props.FirstOrDefault(pi =>
                    pi.CanWrite && string.Equals(pi.Name, name, StringComparison.OrdinalIgnoreCase));

                if (prop != null)
                    prop.SetValue(instance, jp.Value.ToString());
                //prop.SetValue(instance, jp.Value.ToObject(prop.PropertyType, serializer));
            }

            return instance;
        }

        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            throw new NotImplementedException();
        }
    }

    [JsonConverter(typeof(GraphQLQueryConverter))]
    public class GraphQLQuery
    {
        public string OperationName { get; set; }
        public string NamedQuery { get; set; }
        public string Query { get; set; }
        public string Variables { get; set; }
    }
`
