### ISSUE TITLE
Error compiling with strictNullChecks

### ISSUE THREAD

**Issue by jtmthf** [apollostack/apollo-client#608]
I've been writing an application in TypeScript using apollo-client with strictNullChecks enabled. When compiling, this error appears
```
ERROR in [default] /Users/jackmoore/Projects/Web/apollo-react-typescript-example/node_modules/apollo-client/data/store.d.ts:9:4 
Property '__typename' of type 'string | undefined' is not assignable to string index type 'StoreValue'.
```

I came across two solutions to this problem.

1. Disabling strictNullChecks in my project caused the error to disappear. A quick and dirty fix, but not ideal as I enjoy using that feature in my application code.
2. Editing line 61 of `src/data/store.ts` from 
```typescript
export type StoreValue = number | string | string[] | IdValue | JsonValue
```
to
```typescript
export type StoreValue = number | string | string[] | IdValue | JsonValue | undefined
```
essentially only adding undefined to the domain of StoreValue.

This change seems to have no impact on existing code. As a heavy TypeScript user, I was thrilled to see apollo-client written in TypeScript, but it's challenging when I cannot use the compiler features I wish to use. What would you think of incorporating this? If okay, I can create a PR.

**Comment by stubailo** [comment]
Yes please send a PR!

**Comment by stubailo** [comment]
Going to assume this is fixed!
