### ISSUE TITLE
Make addTypename a default transform

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#616]
Having the `__typename` on the client is really useful, and every spec-compliant GraphQL server is supposed to support this feature. I think we should turn on this transformation by default.

This might even let us build in features that rely on the `__typename` being present.

**Comment by stubailo** [comment]
Related: https://github.com/apollostack/react-docs/issues/47

**Comment by swernerx** [comment]
There is just one big issue with this. When we serialize the data coming with typenames by default, mutate it via some client action e.g. using redux-form, then send it back, we still have the typenames inside the data. As our queries do not contain typenames, this fails. What is the suggest approach for fixing this? Disabling "addTypename" or adding typenames to each query?

**Comment by helfer** [comment]
@swernerx if you don't use fragments, you can disable addTypename, but the easiest and most certain fix is probably to add __typename manually for the time being.
