### ISSUE TITLE
Move to RxJS-style observable instead of TC39

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#622]
Might be a better target: https://twitter.com/jhusain/status/770970825667203076

**Comment by kamilkisiela** [comment]
Might be helpful [`apollo-client-rxjs`](https://www.npmjs.com/package/apollo-client-rxjs)

**Comment by stubailo** [comment]
Is there a really minimal version of RxJS observables we can use?

**Comment by kamilkisiela** [comment]
I don't think so. It could be reduced with tree shaking but as far as I know there's no standalone package with only `rxjs/Observable`.

**Comment by stubailo** [comment]
Maybe we can copy-paste it or something - I _really_ don't want to introduce a dependency on RxJS...

**Comment by kamilkisiela** [comment]
As you can see [here](https://github.com/kamilkisiela/apollo-client-rxjs/blob/master/src/RxObservableQuery.ts#L11) we could create our own `Observable` and that's it. But the real problem is that operators are being added to `Observable` using `prototypes`. Take a look at [`map()`](https://github.com/ReactiveX/rxjs/blob/master/src/add/operator/map.ts#L5).

**Comment by kamilkisiela** [comment]
I'm thinking that providing another, standalone package that depends on `rxjs` and extends `ApolloClient` is more convenient. 

Let's say TC39 accepts the same strategy for Observables as RxJS uses now, then ApolloClient could be easily switched into that.

**Comment by stubailo** [comment]
I think we're actively being harmed by using the TC39 proposal since it's bad, so I'm looking for an intermediate solution.

**Comment by kamilkisiela** [comment]
I will think about a solution later, will ping you if anything comes to my mind

**Comment by helfer** [comment]
For now we'll have something observable-like in the core of Apollo Client without subscribing to either full spec.
