### ISSUE TITLE
Add query options to APOLLO_QUERY_INIT action

### ISSUE THREAD

**Issue by raymondsze** [apollostack/apollo-client#623]
I used redux-saga to take these action to perform side effect
APOLLO_QUERY_INIT --> dispatch SHOW_LOADING
APOLLO_MUTATION_INIT --> dispatch SHOW_LOADING

APOLLO_QUERY_RESULT --> dispatch HIDE_LOADING
APOLLO_QUERY_RESULT_CLIENT --> dispatch HIDE_LOADING
APOLLO_MUTATION_RESULT --> dispatch HIDE_LOADING

But I don't want to dispatch SHOW_LOADING if the query is polling, but the payload looks same that i cannot detect whether it is polling query.

**Comment by stubailo** [comment]
I'd be happy to accept a PR to add `pollInterval` to the action here: https://github.com/apollostack/apollo-client/blob/c5794cfccc0ad11678c92c4101785a1f92712634/src/QueryManager.ts#L925

Is the loading state Apollo Client provides not sufficient for your needs?

**Comment by stubailo** [comment]
Ping - if you can open a PR I'd be happy to take a look!

**Comment by tmeasday** [comment]
Maybe solved by: https://github.com/apollostack/apollo-client/issues/707 ?

**Comment by helfer** [comment]
Solved by #827
