### ISSUE TITLE
networkInterface return an object rather than string for GraphQLRequest.query

### ISSUE THREAD

**Issue by linonetwo** [apollostack/apollo-client#637]
As https://github.com/apollostack/apollo-client/issues/379 ,

The `query` receive from ApolloClient is mismatching the second argument of graphql( ) , because `query` is now an `Object {kind: "Document", definitions: Array[1]}` . 

But as [document read](http://dev.apollodata.com/core/network.html#GraphQLRequest) `query` is just a string.
I tried to remove `addQueryMerging( )` and
```javascript
queryTransformer: addTypename,
shouldBatch: true,
```
from ```new ApolloClient({ })```
but `query` still being an object.

**Comment by linonetwo** [comment]
https://github.com/apollostack/apollo-client/blob/a92631da86b2ae493625973447a02b1204a3059f/src/networkInterface.ts#L35

```typescript
interface Request {
  debugName?: string;
  query?: Document;  // this mismatch with graphql( ) from graphql package @stubailo
  variables?: Object;
  operationName?: string;
  [additionalKey: string]: any;
}
```

**Comment by linonetwo** [comment]
Well, I think [printRequest](https://github.com/apollostack/apollo-client/blob/a92631da86b2ae493625973447a02b1204a3059f/src/networkInterface.ts#L105) is of good use, but it's not exported properly.

**Comment by jurajkrivda** [comment]
import { print } from 'graphql/language/printer';
print(request.query)
