### ISSUE TITLE
v0.4.15 release ?

### ISSUE THREAD

**Issue by rricard** [apollostack/apollo-client#641]
Hello!

A few patches (See [Changelog](https://github.com/apollostack/apollo-client/blob/master/CHANGELOG.md#vnext)) are waiting to be pushed to npm (some of them I'm interested in, obviously 😉 ). I'd like to know if there is any limiting fact preventing us from publishing v0.4.15 (if you want to ship some important stuff...), so I can help on that effort.

Thank you!

**Comment by stubailo** [comment]
Hey, nothing limiting - we should make sure to publish new versions asap. Going to do one now.

**Comment by rricard** [comment]
Awesome thanks!

**Comment by stubailo** [comment]
Done!
