### ISSUE TITLE
Is possible to dispatch an action without react-redux ?

### ISSUE THREAD

**Issue by cristiandley** [apollostack/apollo-client#642]
Im ussing apollo and redux over meteor with conmbineReducers to set up a local storage.

```javascript
const rootReducer = combineReducers({
  filters,
  apollo: client.reducer()
});
```
 And i want to dispatch an update ```filters```, in the past i used connect so i just need my _action_ to be called by the dispatcher ```dispatch(updateFilters(newFilters))```  

```javascript
export function updateFilters(filters) {
  return {
    type: "CHANGE_FILTERS",
    data: filters
  }
}
```

Now im using ```gql``` and ```graphql``` how can i achieve the same ? (i tried some methods from the ```QueryManager.ts``` but could find the clue to it)

**Comment by stubailo** [comment]
@cristiandley you still need to use `react-redux`. The Apollo `graphql` container only handles GraphQL stuff.

Good news is, you only need one `ApolloProvider`, and that passes down both your Redux store and the Apollo client.

**Comment by cristiandley** [comment]
So, the best way would be using ```_reactInternalInstance._context.client.store.dispatch()``` ?

**Comment by stubailo** [comment]
I'm saying the best way is to use react-redux as normal. So you would use react-Apollo and react-redux on the same component.

**Comment by cristiandley** [comment]
Thanks @stubailo ! i appreciate your help !
