### ISSUE TITLE
Factor out query merging into a separate package

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#646]
Now that we have transport batching built into the network interface, I think it's a good idea to move the query merging into a separate package. It'll be just as easy to use, but people don't need to load all of that code if they aren't using it.

**Comment by helfer** [comment]
I could line this up while fixing #559

**Comment by chaffeqa** [comment]
I think this must be the reason we are banging our head against the wall...

from my understanding, 0.5.0-1 doesnt seem to have any ability to query batch.

Is there an ETA on this?  You guys are doing a super job and i really support the breaking change paradigm btw... so dont let this be a reason to feel like you're failing, you're doing INCREDIBLE stuff for the community!  just was curious if i was missing something ;)

**Comment by helfer** [comment]
@chaffeqa 0.5.0 will have transport batching, but by using a different network interface instead of passing an option to Apollo Client. If you relied on query merging, you'll have to continue using 0.4.22 until we fix up the query merging and release it as a separate package.
