### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by helfer** [apollostack/apollo-client#650]
Right now the readme has very little information. We should add enough text so people don't need to go read the docs to get an initial impression of what Apollo Client is and how it would make their life easier.

**Comment by gajus** [comment]
I find it extremely frustrating that apollo-* README.md does not contain configuration and API documentation. I spend most of the time looking at the source code to understand the API.

**Comment by smolinari** [comment]
I would say, Apollo Client is a bit too involved to be explained in a single MD file. That is why they have their docs, which is linked front and center in the readme. 

http://dev.apollodata.com/react/

Scott

**Comment by gajus** [comment]
@smolinari As a developer, all I need is API and configuration explanation. For anything else, I will figure it out from the source code.

That documentation you referred to is a recipe book. It is not a documentation one could use as a reference. Not to mention that it is not versioned.

**Comment by smolinari** [comment]
I didn't say the docs were good. :smile: 

Scott

**Comment by smolinari** [comment]
BTW, @gajus - did you see this part of the docs? 

http://dev.apollodata.com/core/apollo-client-api.html

@helfer - Shouldn't the link in the docs go to the "Core JS" section? 

Here? http://dev.apollodata.com/core/index.html

That link through me off (too).

Scott

**Comment by helfer** [comment]
@smolinari you're right, the link was wrong. I think @stubailo fixed it in #655, right?

**Comment by helfer** [comment]
@gajus What parts of the API would you want to see explained in the readme? Because I don't think it makes sense to document the full API, that's what we have the [API docs](http://dev.apollodata.com/core/apollo-client-api.html) for.

**Comment by smolinari** [comment]
@helfer - yes. The link goes to the right place now. 

Scott

**Comment by helfer** [comment]
Given the limited interest I'm going to close this. If someone wants to give it a shot, I'm still open to a PR that improves the readme.
