### ISSUE TITLE
Apollo Server doesn't work in Chrome

### ISSUE THREAD

**Issue by saeho** [apollostack/apollo-client#653]
Can't get my simple apollo-client app to work which uses expressjs apollo server. It only fails in Chrome and works properly on Safari.

I suspected it was because of Access-Control-Allow-Origin security built into Chrome but with a production IP it still fails. May I get some help?

Error I get is:

message: "Network error: Unexpected end of input"
networkError: SyntaxError: Unexpected end of input at SyntaxError (native) at eval (webpack:///./~/apollo-client/networkInterface.js?:115:53)

**Comment by stubailo** [comment]
Any reason this issue is opened on Apollo client? Have you looked at the chrome network tab to see what is being returned?

**Comment by saeho** [comment]
This is opened on Apollo Client because the server works without any problems on Safari, Firefox, and React Native.

**Comment by saeho** [comment]
The server only fails when its used from a WebApp on a Chrome web browser.

**Comment by stubailo** [comment]
What do you mean by "server fails"? Do you have a reproduction, or can you paste in the request and response?

**Comment by saeho** [comment]
The server only fails when its used from a WebApp on a Chrome web browser. Network tab says it fails with 400 BAD REQUEST every time **ANY** GraphQL mutation/query is attempted.

Also I can see the request coming into /graphql path in my express server. But it never reaches my resolvers.

This problem can be duplicated by any GraphQL code, it doesn't matter whether or not the graphql query/mutation exists or not. If it doesn't exist, it should at least return a failed message. Everything returns 400 Bad Request.

**Comment by stubailo** [comment]
I'm using chrome (it's my primary browser), and when I clone and run https://github.com/apollostack/GitHunt-React and https://github.com/apollostack/GitHunt-API, everything works.

I think more information is needed to identify the issue. If you could put together a simple app I can run locally to reproduce the issue, it would help a lot.

**Comment by saeho** [comment]
CAn you please send me the versions of Express/BodyParser and all Apollo/GraphQL related packages you are using?

**Comment by stubailo** [comment]
Literally, clone those two repos, npm install from scratch with node 6, and run them. That's what I did.

**Comment by stubailo** [comment]
Here's one strategy to find the issue: Start deleting code from your app, and delete as much code as possible while still demonstrating the error. Then, upload it here and I can try it out and take a look.

**Comment by saeho** [comment]
I think the problem is somewhere in headers.

With this code, I can see my graphql query logged in my server when I'm doing a query from Chrome. WHen I'm doing the same thing on Safari, I do not see my requests. I think the request headers have different content types, thus why it only NOT works on Chrome.

```
app.use('/graphql', apolloExpress((req,res,next) => {
    ...
    ...
    req.on("data",function(chunk){
        console.log(chunk.toString());
    });
    ...
    ...
}));
```

**Comment by stubailo** [comment]
Does GraphiQL work in Chrome for you?

Also, are you using the default network interface? What does your header-setting code look like?

**Comment by saeho** [comment]
GraphiQL works on Chrome. It's only when the WebApp sends the request.

I just checked hte headers and I think I found the reason.

The content-type for the headers sent from Safari is ...
"application/json"

The content-type for hte headers sent from Chrome is ...
"text/plain;charset=UTF-8"

How can I change the headers of the graphql request I send from the App?

**Comment by saeho** [comment]
This is the network interface.

```

const networkInterface = createNetworkInterface({
  uri: 'http://10.0.0.113:4000/graphql',
  opts: {
    credentials: 'same-origin',
    mode: 'no-cors',
  },
});

export default new ApolloClient({networkInterface});

```

**Comment by stubailo** [comment]
Here's where the content type is set: https://github.com/apollostack/apollo-client/blob/8e87af5ebe7e5516249e3ce1b111e3be6a43bfa5/src/networkInterface.ts#L192

Perhaps you could debug in chrome to see what happens when that function is called.

**Comment by saeho** [comment]
It looks like no matter what I do for some reason the content is sent as UTF-8 from Chrome.

**Comment by stubailo** [comment]
Try calling `fetch` directly in the console with the right headers? If that doesn't work, it must be something super weird.

**Comment by saeho** [comment]
Direct fetch() correctly shows up as content-type application/json

**Comment by stubailo** [comment]
Hmm, it's really hard to know what is going on without a reproduction.

**Comment by saeho** [comment]
Just figured it out. Removing "mode: 'no-cors'," from the networkInterface headers solved the issue for me.

However earlier in the day I remember being forced to add no-cors. I don't seem to need it any more. Not sure if it's because I did disable-web-security option on Chrome.

But this shouldn't be a problem in Production right?

**Comment by stubailo** [comment]
I've never heard of this problem before so I wouldn't be able to tell you. I've never had to use the no-cors option so I'm not sure why it would be needed.

If you use fetch outside Apollo client with that option, does that reproduce that issue.

**Comment by saeho** [comment]
I was forced to add no-cors because Apollo Client returned an error and Apollo Client actually suggested that I add "no-cors", it wasn't clear how so I Googled and figured out that I'm supposed to do mode: 'no-cors' from my network interface.

Adding no-cors directly to fetch() doesn't seem to change anything but that was expected because it's not like mode: 'no-cors' is getting added to my header or anything. I think Apollo is doing something special when I set the mode to no-cors from the network options.

**Comment by stubailo** [comment]
I'm 100% sure it doesn't do anything special beyond calling fetch.

**Comment by saeho** [comment]
Yes I know. That's not what I meant though.

"no-cors" is not passed to header. "no-cors" is passed as "mode". So "no-cors" does not get added to the header. It must be doing something to each query because it's an option.

i.e.
```
createNetworkINterface({
    uri: 'whatever',
    opts: {
        mode: 'no-cors',
    }
})

**Comment by stubailo** [comment]
`no-cors` is a `fetch` option: https://developer.mozilla.org/en-US/docs/Web/API/Request/mode

**Comment by pencilcheck** [comment]
In my experience, setup CORS from the server side to respond to preflight is the easiest way to solve this issue.
So no need to add mode: 'no-cors' to apollo or fetch

**Comment by ramirobg94** [comment]
i am also have this problem

`const networkInterface = createNetworkInterface({
  uri: 'http://localhost:4000/graphql',
  opts: {
        mode: 'no-cors'
    }
});`

{"errors":[{"message":"Must provide query string."}]}


`POST /graphql HTTP/1.1
Host: localhost:4000
Connection: keep-alive
Content-Length: 169
Pragma: no-cache
Cache-Control: no-cache
accept: */*
Origin: http://localhost:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
content-type: text/plain;charset=UTF-8
Referer: http://localhost:8080/menu
Accept-Encoding: gzip, deflate, br
Accept-Language: es-ES,es;q=0.8,en;q=0.6`

Thanks

**Comment by ramirobg94** [comment]
@saeho 
I have solved my problem,
I have a react-web-app on a static server and my API is on another server,
I was serving the app with static-server, I switched to normal express server and with cors on both sides everything is okay.

**Comment by 3nd** [comment]
For those who are utilizing systemjs, angular, typescript, apollo and graphql, add the options in the network interface like:

`/* **************************************************
 * **************************************************
 * Instantiate a new Apollo Network Interface Object
 * the opts enables us to pass additional options to fetch
 * credentials: 'same-origin' - To automatically send cookies for the current domain
 * credentials: 'include' - causes fetch to behave like XMLHttpRequest in regards to cookie to preserve the authentication session
 * SEE: http://dev.apollodata.com/core/network.html
 * SEE: https://github.com/github/fetch/blob/7f71c9bdccedaf65cf91b450b74065f8bed26d36/README.md#sending-cookies
*/
const networkInterface = createNetworkInterface({
  uri: endpoint,
  opts: {
    credentials: 'same-origin',
  },
});`

Thanks to all in this post that helped me to solve this.

**Comment by coreyjewett** [comment]
Zombie commenting on this thread for anyone that happens upon this issue as it cost me half a day.

In dev my graphql service (postgraphile) is a separate server on a different port from my client code (gatsby w/apollo-client). Due to poor CORS config (my fault), Chrome suggested I add `mode: 'no-cors'` to fetch. This causes the graphql query to POST as `text/plain`.

To fix: 1) remove `mode: 'no-cors'` from fetchOptions and 2) correct the CORS config on the server.
