### ISSUE TITLE
i want to known how it works in apollo-redux and will i install  apollo-react the same time?

### ISSUE THREAD

**Issue by blizzardzheng** [apollostack/apollo-client#659]
i use react-redux for web app, what confused me most is how to Integrate apollo to react-redux. i find there is two ways .one is  react-apollo,which can link components directly the other is apollo-redux. so what is the difference between them. i find when i use apollo-redux, it generates an apollo store for me, but how can i get data from my 'map state to props' , directly from the apollo store or when it succeed it dispatch another action with data. i review the doc , there is no more data on how to access data in containers with redux and apollo-redux.  i also want to know how it works in apollo-redux, will it normalize the data for me? will it filter the data which has already fetched ? will it analyse the query,and send back to me what i want but not simply do the network request?

**Comment by stubailo** [comment]
What is Apollo-redux? Are you referring to some package, or the redux integration guide?

**Comment by blizzardzheng** [comment]
@stubailo the redux integration guide

**Comment by stubailo** [comment]
Yeah if you integrate with redux you still need react-Apollo. The main benefit is that you can keep track of all data in one place, but Apollo manages it for you.

**Comment by stubailo** [comment]
I added a note here: http://dev.apollodata.com/react/redux.html
