### ISSUE TITLE
Can't find field xxx on result object

### ISSUE THREAD

**Issue by linonetwo** [apollostack/apollo-client#664]
When querying likes:
```graphql
query ModuleListData($token: String!, $districtID: Int!, $siteID: Int!) {
  Company(token: $token) {
    id
    district: children(id: $districtID) {
      id
      site: children(id: $siteID) {
        id
        name
        cabinets {
          id
          name
          type
          switches {
            id
            isOn
            name
          }
        }
      }
    }
  }
}
```
there being something wrong with it:
```
Network error: Can't find field id on result object $ROOT_QUERY.Company({"token":"8468e02d-26c6-4e2d-8395-ad1f25f7c9c7"}).children({"id":8}).0.children({"id":12}).0.cabinets.0.switches.0."
```
Only by removing switches field can I get proper data. So I think this problem is caused by a 2D array:
```graphql
type CabinetType {
  id: Int!
  name: String!
  type: String!
  switches: [[SwitchType]] # switches will have an array of array of switch
}
```
I don't know what's going on since I can run this query on the graphiql with proper feedback.

I'm not sure whether this is cause by react-apollo or not, But there is similar issue hints this is cause by redux. https://github.com/apollostack/apollo-client/issues/544

**Comment by linonetwo** [comment]
I found "temporary workaround" by adding new type in the schema:
```
type CabinetType {
  id: Int!
  name: String!
  type: String!
  switches: [SwitchType] # switches will have an array of array of switch
}

type SwitchesListType {
  switchesList: [SwitchType]
}
```
now query will return proper data without error:
```graphql
query ModuleListData($token: String!, $districtID: Int!, $siteID: Int!) {
  Company(token: $token) {
    id
    district: children(id: $districtID) {
      id
      site: children(id: $siteID) {
        id
        name
        cabinets {
          id
          name
          type
          switches {
            switchesList {
              id
              isOn
              name
            }
          }
        }
      }
    }
  }
}
```
But it's kind of redundent. If I need higher dimentional array this is still a problem.

**Comment by stubailo** [comment]
This could definitely be a bug in multidimensional array handling. Should be easy to fix!

**Comment by linonetwo** [comment]
And what does ```Network error: Cannot read property '0' of undefined``` means, when I query for array.

**Comment by stubailo** [comment]
Any way you could post an example of a query and result that fails? Then we can add that as a unit test, and fix it for sure.

**Comment by linonetwo** [comment]
@stubailo I found it.
```
const queryConfig = {
  options: ({ token, districtID, siteID }) => ({
    variables: { token, districtID, siteID },
    pollInterval: 10000
  }),
  props: ({ ownProps, data: { refetch, loading, Company, error } }) => ({
    refetch,
    loading,
    error,
    cabinets: loading ? [] : Company.district[0].site[0].cabinets,
  })
};

@connect(mapStateToProps)
@graphql(ModuleListData, queryConfig)
export default class ModuleList extends Component {
```
Where cabinets will be an array of obj that has array, for example:
[ { myArray: [...] }, { myArray: [...] }, { myArray: [...] } ]

By mistake, I use ```cabinets[0].myArray[0].qwerasdf[0]``` where qwerasdf will be undefined, ApolloError will show up reading ```Network error: Cannot read property '0' of undefined```.
  
This could have been a local error, but somehow it blocks react-apollo ( I guess ), so trowing an ApolloError .

I solve it by removing misused ```qwerasdf```.

**Comment by stubailo** [comment]
@jbaxleyiii here's an example of a misidentified network error I guess?

**Comment by linonetwo** [comment]
It being somehow disturbing. Whenever there is an "TypeError: null is not an object (evaluating 'this.state.openSourceFilter' " kind of error ( sometimes can't be deal with immediately in engineering, I have to keep it) , Apollo will stop functioning, throws "Unexpected batch number (current 439, pending 438)" and no data will be loaded.

**Comment by stubailo** [comment]
Multidimensional arrays are fixed in #785, should come out soon.

**Comment by thebigredgeek** [comment]
@stubailo any update here?  Just started getting this error seemingly out of nowhere :(

**Comment by VikR1000** [comment]
Same here!

> Network error: Can't find field id on object

**Comment by VikR1000** [comment]
Hmmm..... I think it happened when I tried to store >255 characters to a postgres field that is specced for a maximum of 255 characters.

**Comment by helfer** [comment]
@thebigredgeek @VikR1000 this particular bug seems to have been fixed a while back. If you're seeing something similar, please open a new issue so we can track it separately.
