### ISSUE TITLE
What is localStorage and why are there Meteor references in it?

### ISSUE THREAD

**Issue by ashah888** [apollostack/apollo-client#665]
When I look at my front-end only app using Apollo-Client, I see variables named "Meteor.loginToken", "Meteor.loginTokenExpires" and "Meteor.userId".

Why are they there? What is localStorage? Is it a browser based cookie?

**Comment by stubailo** [comment]
@ashah888 did you perhaps run a Meteor app locally on the same port before, and not clear local storage? Try clearing the storage, then running an apollo client app without Meteor, and then reopen this issue if you see anything like that. This repository has no code that writes to local storage in any way.
