### ISSUE TITLE
Look into store contents that can be eliminated when using server-side hydration

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#666]
There is some data like the query AST that could be eliminated from the server-side hydrated state, reducing its size dramatically. We should look into eliminating that stuff, and having the client deal with its absence appropriately.

One aspect is that #615 will remove one instance of the query AST right away.

Continuation of https://github.com/apollostack/apollo-client/issues/660

**Comment by helfer** [comment]
This is done afaik.
