### ISSUE TITLE
Deprecated reduxRootKey is now mandatory if we want to use react-apollo

### ISSUE THREAD

**Issue by rricard** [apollostack/apollo-client#676]
Right now, if you want to use the latest apollo-client with the latest react-apollo, **you have to set reduxRootKey**. This is a breaking bug!

In this subversion set (0.4.x) we should make default reduxRootKey to the value of reduxRootSelector that should itself default to "apollo".

If this is not done, a breaking bug will appear in react-apollo (that should be fixed as well: https://github.com/apollostack/react-apollo/issues/221).

**Comment by rewop** [comment]
I don't know if this is as intended or not, but when a store is already provided, `reduxRootKey` is undefined both if I provide `reduxRootSelector` and I don't. 

I have noticed this one when I use `apollo-client` with redux integration and ssr from 'react-apollo', 

```javascript
const client = new ApolloClient({
   reduxRootSelector: 'apollo'
});

console.log(client.reduxRootKey); // => undefined
```

```javascript
const client = new ApolloClient();

console.log(client.reduxRootKey); // => undefined
```

**Comment by stubailo** [comment]
Ah I think I failed at backwards compatibility. Let me add a few fixes and publish a new version.

**Comment by rricard** [comment]
I have an another really annoying bugs, if you could wait a bit ...

**Comment by rricard** [comment]
For now we're going to freeze to 0.4.15

**Comment by rricard** [comment]
Can't we just deprecate 0.4.16 while we publish 0.4.17 ?

**Comment by stubailo** [comment]
> Can't we just deprecate 0.4.16 while we publish 0.4.17 ?

Unfortunately on npm there's no way to deprecate a version without having a future one.

**Comment by rricard** [comment]
Ok, we better move fast then ...

**Comment by stubailo** [comment]
I can't think of any other change that could have caused such an issue.

**Comment by rricard** [comment]
@stubailo I agree on this issue but we also have this one which is hurting us pretty bad (all of our local+staging envs are broken right now): #678

**Comment by stubailo** [comment]
OK I'm going to publish a 0.4.17 that's identical to 0.4.15 for now.

**Comment by rricard** [comment]
Thanks! I'll start to investigate right now because there are actually some features in 0.4.16 that are actually really great (deep fragment merging for instance), so the sooner we ship 0.4.18, the better!

**Comment by stubailo** [comment]
@rricard 0.4.17 should be good now. Just deprecated 0.4.16.

**Comment by rricard** [comment]
@stubailo awesome! Thanks for the reactivity !

**Comment by stubailo** [comment]
Yeah, thanks - sorry I wasn't careful enough, really wasn't trying to break anything. I won't be able to look in detail until the afternoon.

> Thanks for the reactivity !

No problem - we should figure out how we can avoid the issue - maybe have some kind of RC process for a day or two where you can try it!

**Comment by helfer** [comment]
Alright, so if I'm reading this right the problem is that react-apollo expects ApolloClient to have the property `reduxRootKey`, which the latest version removed. For now I'll set it to the same as what`reduxRootSelector` returns.

Going forward we need to define very clearly what is part of ApolloClient's external API and what isn't, so we can avoid surprises like this one.

**Comment by stubailo** [comment]
Good call!

**Comment by rricard** [comment]
You guys rock if I can help defining this API just ask me!
