### ISSUE TITLE
Getting "Can't find field" errors on null fields (even if the field is nullable)

### ISSUE THREAD

**Issue by rricard** [apollostack/apollo-client#678]
Since 0.4.16.

Once a mutation comes back and its results are reinjected into the store via `updateQueries`

```
Can't find field cursor on result object $ROOT_QUERY.connection({"id":"xxx"}).nodeChildren({"id":"root","limit":40,"cursor":null,"sortBy":null}).
Error
    at new ApolloError (webpack:///./~/apollo-client/lib/src/errors.js?:14:22)
    at eval (webpack:///./~/apollo-client/lib/src/data/writeToStore.js?:59:23)
    at Array.forEach (native)
    at writeSelectionSetToStore (webpack:///./~/apollo-client/lib/src/data/writeToStore.js?:53:29)
    at eval (webpack:///./~/apollo-client/lib/src/data/writeToStore.js?:121:21)
    at Array.forEach (native)
    at writeSelectionSetToStore (webpack:///./~/apollo-client/lib/src/data/writeToStore.js?:53:29)
    at writeFieldToStore (webpack:///./~/apollo-client/lib/src/data/writeToStore.js?:226:9)
    at eval (webpack:///./~/apollo-client/lib/src/data/writeToStore.js?:75:17)
    at Array.forEach (native)

**Comment by stubailo** [comment]
This error should happen on `master` - can you submit a failing test as a PR?

**Comment by rricard** [comment]
Working on it 😉 !

**Comment by rricard** [comment]
Harder to reproduce than expected. Seems like I have to throw fragments in the mix!

**Comment by stubailo** [comment]
OK, maybe it's a result of that deep-assign PR for fragments then? That's the only relevant change I can think of.

**Comment by rricard** [comment]
Urr, I'm based on an older version and can't get it to fail, trying with the **latest** master now!

**Comment by rricard** [comment]
But, yes, I think this PR, even if it'll help us **a lot** may be the one responsible

**Comment by rricard** [comment]
Okay, maybe I'm not in a good setting to write the test but I see how it's happening in our app: basically, the deepMerge seems to "transform" null fields into undefined.

**Comment by stubailo** [comment]
Wow that would be really silly.

**Comment by rricard** [comment]
Yes, I agree, that's why I want to get the test first because it seems crazy

**Comment by rricard** [comment]
Okay I need to go for today, we'll freeze for now, I'll try to get the test ASAP, I think I'm not writing it at the right place: any advice on where I should write it ? For now I tried in `mutationResults` don't really see where to put it apart from there but I tried to make it fail there by adding an `undefined` (which we want to see fail) and didn't.

**Comment by rricard** [comment]
Tried it here: https://github.com/apollostack/apollo-client/compare/fix-678?expand=1

**Comment by helfer** [comment]
@rricard is that last link for a test that successfully reproduces the bug, or was it just an (unsuccessful) attempt?

**Comment by helfer** [comment]
Guys, I don't even think we need to write a fancy test for this, deep-assign doesn't copy null values:

https://github.com/sindresorhus/deep-assign/blob/699948936d466e2ea738610fcf7cc80aa21babf7/test.js#L13

```
test('do not assign null values', t => {
	t.deepEqual(fn({}, {foo: null}), {});
});
```

**Comment by helfer** [comment]
I'll find some other deep-copy thing we can use, or I'll write one myself if there's nothing decent out there.

**Comment by rricard** [comment]
@helfer it was unsuccessful. A test would be great though just in case I'll still try to do it and integrate lodash.merge !

**Comment by helfer** [comment]
@rricard 0.4.18 released. Fingers crossed it will work this time 🚀

**Comment by rricard** [comment]
@helfer wow, that went fast, thanks! We'll try that today, if there is any feedback I'll tell you!

**Comment by flamerohr** [comment]
Hi, I've recently run into this issue recently with `store.readQuery({ query });` and had traced it down to `getDefaultValues()` in `getFromAST`:
https://github.com/apollographql/apollo-client/blob/3b5045dfe74183fe060d2027e31317d890755b99/src/queries/getFromAST.ts#L269
where the null values are being filtered out, but I'm pretty that filter is also required by the map following it...

A screenshot of the error I had run into:
<img width="431" alt="screen shot 2017-07-24 at 12 36 01 am" src="https://user-images.githubusercontent.com/1064889/28499373-3d753700-7008-11e7-81c5-a81d36796dec.png">
