### ISSUE TITLE
Honor afterware promises when querying

### ISSUE THREAD

**Issue by shanonvl** [apollostack/apollo-client#682]
When `query`'ing using the default network interface, [applyMiddleware](https://github.com/apollostack/apollo-client/blob/master/src/networkInterface.ts#L136) and [applyAfterware](https://github.com/apollostack/apollo-client/blob/master/src/networkInterface.ts#L161) both return promises, and the query logic [waits for middleware promises](https://github.com/apollostack/apollo-client/blob/master/src/networkInterface.ts#L200-L203) but [ignores afterware promises](https://github.com/apollostack/apollo-client/blob/master/src/networkInterface.ts#L204-L210).

I've created [tests for both middleware and afterware promises](https://github.com/shanonvl/apollo-client/blob/after-middleware-promises/test/networkInterface.ts#L397-L434) to validate the behavior and the afterware test fails.

Given that this works for middleware and [applyAfterwares method returns a Promise](https://github.com/shanonvl/apollo-client/blob/after-middleware-promises/src/networkInterface.ts#L161), this seems to be a bug?

If it is a bug, I've [implemented a fix in my branch](https://github.com/shanonvl/apollo-client/blob/after-middleware-promises/src/networkInterface.ts#L204-L217) and can submit a PR once I get confirmation from the team.  

Thanks!

**Comment by stubailo** [comment]
Is there something you want to do in an afterWare that requires a promise? Just curious about the use case.

**Comment by shanonvl** [comment]
I’ve actually figured out a workaround where I don’t need a Promise, but my actual use case is such that I want to specify my own reviver function to parse the JSON vs. receiving the output of `response.json()` (via `query()`) and then processing it from there.   

I could write a custom network interface for this, but given the existing behavior for middleware, I wanted to see if honoring promises in the afterware *should* be supported.

My workaround is to just override the `json` function in the response with my own flavor ( via async/await vs. Promises just b/c this project is using es7 via Babel ):
```js
{
  applyAfterware: ({response}, next) => {
    if (response.status === 200) {
      Object.defineProperty(response, 'json', {
        value: async() => JSON.parse(await response.text(), this.reviver)
      });
    }
    next();
  }
}
```

Given this info, let me know if you’d like me to leave this open / submit a PR — otherwise, I’m happy to close.   

Thanks for the quick response and also for all of the work on this client!

**Comment by shanonvl** [comment]
I’ve actually figured out a workaround where I don’t need a Promise, but my actual use case is such that I want to specify my own reviver function to parse the JSON vs. receiving the output of `response.json()` (via `query()`) and then processing it from there.   

I could write a custom network interface for this, but given the existing behavior for middleware, I wanted to see if honoring promises in the afterware *should* be supported.

My workaround is to just override the `json` function in the response with my own flavor ( via async/await vs. Promises just b/c this project is using es7 via Babel ):
```js
{
  applyAfterware: ({response}, next) => {
    if (response.status === 200) {
      Object.defineProperty(response, 'json', {
        value: async() => JSON.parse(await response.text(), this.reviver)
      });
    }
    next();
  }
}
```

Given this info, let me know if you’d like me to leave this open / submit a PR — otherwise, I’m happy to close.   

Thanks for the quick response and also for all of the work on this client!

**Comment by helfer** [comment]
@shanonvl A PR would be appreciated! I think it was a simple omission and not intentional, so we should fix it, even if there's a workaround.

**Comment by helfer** [comment]
recently fixed, I believe.
