### ISSUE TITLE
JSON type | requirement | please help

### ISSUE THREAD

**Issue by seeden** [apollostack/apollo-client#689]
How I am able to use JSON type as graphql type? Is it possible to add a new type?

**Comment by seeden** [comment]
I am closing this because I found http://dev.apollodata.com/tools/graphql-tools/scalars.html

**Comment by stubailo** [comment]
Yeah, and apollo-client supports it out of the box.

**Comment by seeden** [comment]
Thanks @stubailo . You are doing a great job with apollo
