### ISSUE TITLE
refetchQueries fails if a query has not yet been executed

### ISSUE THREAD

**Issue by jasonphillips** [apollostack/apollo-client#690]
I'm running into a situation where this line throws an error by calling forEach on undefined:

https://github.com/apollostack/apollo-client/blob/master/src/QueryManager.ts#L1002

The situation emerges when I use the `refetchQueries` option on a mutation but have not yet (due to sometimes varied user paths to the mutation) fetched the particular query named. 

It seems preferable to allow a list of invalidated queries to be provided without throwing an error when one hasn't been fetched yet; unless I'm missing something.

**Comment by helfer** [comment]
@jasonphillips yes, you're right, we should just ignore the query if it hasn't run yet, or maybe print a warning to the console just to help people discover typos.

**Comment by helfer** [comment]
I assume this is fixed now since we merged the PR. Please holler if that's not the case.
