### ISSUE TITLE
client.resetStore() is not available

### ISSUE THREAD

**Issue by ashah888** [apollostack/apollo-client#692]
According to the documentation, I should be able to call client.resetStore() to reset the store and let cache reset. However I do not see that in my apollo client I create from new ApolloClient()

**Comment by helfer** [comment]
Which version are you using? I'm pretty sure the method is there, we even have a test for it.

**Comment by andrewnoh** [comment]
I definitely see it after creating an Apollo Client from new ApolloClient(), but how do I access it from within my component? ApolloProvider doesn't seem to pass it down for me.
