### ISSUE TITLE
Node v6.6.0 - UnhandledPromiseRejectionWarning emitted from tests 

### ISSUE THREAD

**Issue by shanonvl** [apollostack/apollo-client#699]
Node v6.6.0 (the _current_ node build) now emits an warning for unhandled promise rejections (see _Notable Changes_ in the [Node 6.6.0 Release Notes](https://nodejs.org/en/blog/release/v6.6.0/)).   When running the test suite on this version on node, multiple warnings (like the sample below) are emitted to the console.

``` js
(node:20070) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: Network error: No more mocked responses for the query: {
  author {
    firstName
    lastName
  }
}

fragment authorDetails on Author {
  firstName
  lastName
}
, variables: undefined
```

To replicate:

``` shell
$ node --version
v6.6.0
$ npm install && npm test
```

**Comment by stubailo** [comment]
Oh! That explains why a lot of tests fail on Travis but not on my local computer... let me upgrade node and try again.

**Comment by feddyups** [comment]
getting the same errors, when using node v6.6.0 and having tests running with mocha, using done()  in the assertions.

**Comment by JonathanNasc** [comment]
The only way to solve this in my case, was go back to use bluebird module

**Comment by stubailo** [comment]
Can someone identify any unhandled rejections inside the client? I just quieted this in the tests by overriding the unhandled rejection warning.

**Comment by DxCx** [comment]
@stubailo looks like this one is coming from test file not the actual client..
somewhere test are not handling reject..

**Comment by stubailo** [comment]
I think it's fine to not handle every single rejection in the tests -- at least, it doesn't seem like a top priority to hunt every single one down.

**Comment by stubailo** [comment]
I'm just wondering what @JonathanNasc was referring to, because it didn't sound like he was talking about the tests.

**Comment by JonathanNasc** [comment]
I am sorry, I was referring to use the ES6 native Promises in general.

**Comment by calebmer** [comment]
Looks like this no longer effects us. Just ran the current test suite against Node.js v7.2.1 and we’re all green. Thanks for the report @shanonvl :+1:
