### ISSUE TITLE
updatequeries my component is not unmounting

### ISSUE THREAD

**Issue by gmchaturvedi1** [apollostack/apollo-client#708]
i am using update queries and after update data is coming but on update both ui is coming means before and after rendering. 

Kindly suggest what to do to unmount before rerendering ui.

Regards
gmchaturvedi

**Comment by gmchaturvedi1** [comment]
my issue is solved i am updating my updatequey with unshift in place of set method. 

reagrsd
gm

**Comment by stubailo** [comment]
Thanks!
