### ISSUE TITLE
npm install fails on fresh clone

### ISSUE THREAD

**Issue by helfer** [apollostack/apollo-client#71]
After cloning a fresh repo, `npm install` runs `tsc`, which fails with the following error:

error TS6053: File 'typings/main.d.ts' not found.

Am I missing some dependencies?

**Comment by johnthepink** [comment]
@helfer I think you need typings and tsc. 

npm install -g typings tsc

Do you have those?

**Comment by helfer** [comment]
I found it, this commit has the solution: https://github.com/apollostack/apollo-client/commit/40b59f82fe19cc198a09e6b0f5da8a3e60e463f7

I just had to run `typings install` first, then `npm install`. It's a bit of a chicken and egg situation with npm, but I hope we can figure something out that works for both installing from npm and cloning from github.

**Comment by stubailo** [comment]
Yeah I think we just need to update the readme to explain how to set it up. Alternatively I think committing the typing a to git could be a great choice - I bet they don't change that often!

**Comment by mquandalle** [comment]
@stubailo Committing third-party typing files doesn’t seems extremely right. Could you expand on why the previous `postinstall` script to run typing fetching wasn’t working?

**Comment by stubailo** [comment]
Mostly because I couldn't figure out how to not make that step run when installing from NPM. If you have any ideas I'd love to put it back

**Comment by mquandalle** [comment]
Why do you want to skirt this step?

**Comment by jbaxleyiii** [comment]
@mquandalle @stubailo I think this comes down to two issues. Development from github vs using this package in npm.

- Locally I want typings, the raw files, test, etc
- on the CI I want the same
- when pushed to npm, I only want the compiled code

I think the npm script hooks (e.g. postinstall) should be reserved for the package on npm. That way when a user downloads it, we know exactly what is being run.

I'd recommend a `npm run setup` command that handles the typings / setup for local dev and make it part of the documentation personally

**Comment by stubailo** [comment]
Yeah that makes sense to me. On the other hand, I really don't feel like committing development-only dependencies, like the typings, is that bad. It has the added benefit that if something about the typings installation stops working our builds don't spontaneously fail.

Last week, there was some incident where all of our tests on CI started failing because something was broken in the `typings` tool, or the repository, or something - if we commit those it can never happen.
