### ISSUE TITLE
When using batching, the client constantly runs intervals

### ISSUE THREAD

**Issue by Pajn** [apollostack/apollo-client#710]
The current implementation of batching runs code every 10ms, no matter if there are active queries not.
It would be better if the timeouts only were run during active queries.

For example, I would imagine something like the following

```
when a query is performed:
  check if there is an active timer, if not:
    set activeTimer = true
    start a timer that fires after pollInterval

when the timer fires:
  set activeTimer = false
  run consumeQueue
```

Is there a reason for the current implementation that I'm missing?

**Comment by stubailo** [comment]
I think you're right: it would be better to kill the timeout if no queries are happening, and only start it when there are queries to batch.

Is this causing a concrete problem for you? My impression was that it was fine to run some very cheap code on a small interval. Otherwise, I'd be happy to look at a PR adding this functionality.

**Comment by Pajn** [comment]
>Is this causing a concrete problem for you?

I'm not sure so treat it as no, for now. 
I noticed some strange slowdowns in Firefox and that was the first immediately visible thing that happened in the trace that I wasn't expecting, but I didn't have time to dig into it deeper.
Will look into making a PR when I get time to come back to this. From the quick look before opening the issue it felt like the change should be pretty well contained.

**Comment by stubailo** [comment]
I agree! Let me know if I can help.

**Comment by helfer** [comment]
I don't think the current implementation is a reason for concern as it's a single timer and it runs very little code if no query is currently being batched. It should be an easy change though, so if anyone wants to make a PR, go for it!
