### ISSUE TITLE
Consider moving @types packages from devDependencies to dependencies

### ISSUE THREAD

**Issue by antmdvs** [apollostack/apollo-client#713]
The rationale is discussed here:
https://github.com/Microsoft/types-publisher/issues/81

This doesn't prevent my app from running, but the TS errors are pretty annoying especially because they break HMR (with the overlay configured) as shown below:

![apollo ts declaration dependencies_censored](https://cloud.githubusercontent.com/assets/17127310/18840626/327648fc-83dd-11e6-8bb1-9821cc0b59fa.jpg)

**Comment by helfer** [comment]
@antmdvs Yeah, that makes sense. Can you make a PR so we can see how much that would add to the gzipped bundle size?

**Comment by stubailo** [comment]
In theory it shouldn't add anything at all since it wouldn't be bundled.

**Comment by antmdvs** [comment]
@helfer I would love to contribute, but i'm swamped at the moment. I'll check back in a couple days to see if this is still actionable and try to help out then.

**Comment by antmdvs** [comment]
Ok, I'm looking into this now.
