### ISSUE TITLE
Middleware is only applied on first request

### ISSUE THREAD

**Issue by djinindi** [apollostack/apollo-client#719]
I have a GraphQL server with some fields you can query if you include auth headers in the request. I'm using angular2-apollo.
```
// Example query
this.apollo.query({
  query: gql`
    query getUser($guid: String!) {
      user(guid: $guid) {
        name
        email
      }
    }
  `,
  variables: {
    guid: 'guid'
  }
}).then(success => {...}).catch(error => {...});
```
`email` here is a restricted field that will be `null` if there is no auth headers in the request.

I define the middleware like this in my `app.module.ts`:
```
const apolloNetworkInterface = createNetworkInterface(url);
apolloNetworkInterface.use([{
  applyMiddleware: (req, next) => {
    if (!req.options.headers) {
      req.options.headers = {};
    }
    if (localStorage.getItem('token')) {
      req.options.headers.token = localStorage.getItem('token');
      req.options.headers.userid = localStorage.getItem('guid');
    }
    next();
  }
}]);
const apolloClient: ApolloClient = new ApolloClient({
  networkInterface: apolloNetworkInterface
});
```

First time I run the query I'm **not** logged in, so there is nothing in `localStorage` and therefore `req.options.headers` is empty.
The response is as expected:
```
user: {
  name: "John",
  email: null
}
```
Now as a user I want to know Johns email, so I decide to login and try to run the same query again. When I login a token and my userid is saved in `localStorage`.

This time I expect the `req.options.headers` to have `token` and `userid` in it, so that `email` is not `null`. 

To my surprise `req.options.headers` is the same as before I logged in, and Johns email is still `null`.

**Comment by stubailo** [comment]
Can you put a log or `debugger` to verify when your middleware function is ever called?

**Comment by stubailo** [comment]
And when it is called, what the headers end up being? This is the primary way people use middlewares so I would be surprised if it didn't work.

**Comment by djinindi** [comment]
After some digging, I found out that I needed to add `forceFetch: true` to my query
```
// Example query
this.apollo.query({
  query: gql`
    query getUser($guid: String!) {
      user(guid: $guid) {
        name
        email
      }
    }
  `,
  variables: {
    guid: 'guid'
  },
  forceFetch: true
}).then(success => {...}).catch(error => {...});
```
💣
