### ISSUE TITLE
stopPolling and startPolling

### ISSUE THREAD

**Issue by townmulti** [apollostack/apollo-client#723]
Is stopPolling and startPolling able to be used to toggle polling? Like should I be able to stopPolling at will, then start it back at will and as many times as needed like by pressing a button that triggers the function calls?

Asking this question because when I try this toggle effect, they only work once. I can start and stop but not start again. Or I can stop then start, but not stop again.

**Comment by tmeasday** [comment]
I think this is a bug, because it uses a static `isPollingQuery` here: https://github.com/apollostack/apollo-client/blob/master/src/ObservableQuery.ts#L174

**Comment by helfer** [comment]
Ok, we'll have to fix this when we refactor polling after 0.5

**Comment by helfer** [comment]
@townmulti I think this was fixed in #938. Can you give it a try and let me know?

**Comment by townmulti** [comment]
Okay thanks! I would be happy to try it, but I will have to try it when I update my project. I'm using the meteor-integration and apollo-client 0.4.22 right now. Should I close this until I get a chance to test this, and re-open if I have any issue when I test it?

**Comment by townmulti** [comment]
Will close and reopen if have the same issue. Thanks!
