### ISSUE TITLE
Allow access to parsed response in afterware

### ISSUE THREAD

**Issue by morgante** [apollostack/apollo-client#730]
Currently, I am writing some afterware which checks if there were any GraphQL errors with JWT signature validation. It's meant to resend the request if the JWT failed (which is reflected in the graphql errors array).

Unfortunately, there does not seem to be any way to access the actual response body from afterware.

Attempting to parse it directly (with `response.json()`) of course generates an already read error when GraphQL goes to read it:

> TypeError: Already read at TypeError (native) at eval

There are two alternative options which might make sense to me:
1. Move afterware to after the response is parsed. This might things for people who want to modify/handle the response before it is parsed into a GraphQLResult.
2. Add "parseware" which runs after the GraphQLResult and could potentially change the GraphQLResult and pass it along.

Is there an alternative way to do this that I hadn't considered?

**Comment by DxCx** [comment]
see #774 :)

**Comment by helfer** [comment]
We'll track this in #774.
