### ISSUE TITLE
Fragment on Query doesn't work

### ISSUE THREAD

**Issue by armstrjare** [apollostack/apollo-client#736]
Haven't looked into the cause of this, but the seems to drop the fragment for the query root.

eg.

```graphql
query {
   ...QueryFragment
   
   records {
     id
   }
}

fragment QueryFragment on Query {
  records {
     name
  }
}
```

results in the query:

```graphql
query {
   records {
     id
   }
}

fragment QueryFragment on Query {
  records {
     name
  }
}
```
(note omitting the fragment spread)

Ideas?

**Comment by stubailo** [comment]
That's surprising - perhaps query diffing kicked in and noticed you already have the names for the records?

In the next version of Apollo Client we're removing all query manipulation, so nothing of this sort should happen anymore.

**Comment by armstrjare** [comment]
That's not the case since this was the first query run. It also leaves the Fragment definition in the query so the server will crash on an unused fragment. This only became an issue when adding the fragment to the root Query rather than fields.

Sounds like probably just should work around for now and wait for next version if this stuff is changing heavily :-) Any ideas on timing for that?

**Comment by stubailo** [comment]
Passing test for this here: https://github.com/apollostack/apollo-client/pull/786

Hoping to release a 0.5 preview in the next day or two.
