### ISSUE TITLE
Consider modifying npm scripts to be cross-platform

### ISSUE THREAD

**Issue by antmdvs** [apollostack/apollo-client#741]
Several of the npm scripts in package.json don't work on Windows and will result in errors. The offending scripts are those containing:
1. `rm -rf` (rm is not a Windows command)
2. `mkdir` with _forward_ slash directory separators ("./dist") -- (This will only work in PowerShell)
3. `./**/*.js` without `node` prefix
4. `./**/*.sh` bash scripts
### Recommendations:
- Instances of `rm -rf` could be replaced with `rimraf`
- Instances of `mkdir` could be replaced with `mkdirp`
- Prefix `./**/*.js` instances with `node`

I'm not sure how to approach the bash scripts.

**Comment by stubailo** [comment]
Some of the scripts are critical to be able to develop stuff, such as testing and linting, and those are all cross-platform. We actually run the tests on Windows on AppVeyor specifically for this reason.

The bash scripts are mostly for auxiliary stuff like filesize, etc. which we mostly run on Travis CI anyway.

If you think it's important to be able to run those other scripts on Windows, I'd love to take a PR but we can't prioritize making sure _all_ of the scripts run flawlessly on Windows.

**Comment by antmdvs** [comment]
Very good. I'll leave this up-for-grabs for now and post back here if I take this on.

**Comment by helfer** [comment]
closing up some old issues. If anyone still wants to try this, please ping me.
