### ISSUE TITLE
Module or jsnext:main in package.json

### ISSUE THREAD

**Issue by danbucholtz** [apollostack/apollo-client#746]
Since this is a Typescript app, can you distribute `es5` code (es5 target) with `es2015` modules in addition to the `commonjs` modules you distribute?

Set the `moduleResolution` to `node` as well to make everything work well in the `tsconfig.json`.

`jsnext:main` and `module` are the fields that point to the entrypoint for the es5 code with es2015 modules. Angular uses `module` and it seems most bundlers look for `module`, then `jsnext:main`, then `main` in that order.

I'm happy to help more if needed.

Thanks,
Dan

**Comment by stubailo** [comment]
> I'm happy to help more if needed.

We'd be happy to take a PR adding this to the package.json, if you know how to set it up.

**Comment by Urigo** [comment]
@danbucholtz would love to hear your thoughts about this PR - https://github.com/apollostack/apollo-client/pull/1069

**Comment by danbucholtz** [comment]
@Urigo,

Looks reasonable to me at first glance.

Thanks,
Dan

**Comment by kamilkisiela** [comment]
@danbucholtz I added `jsnext:main` too https://github.com/apollostack/apollo-client/pull/1069/commits/5ba7fe5000332103ece0dd570d6f692b193d9af5

**Comment by helfer** [comment]
@danbucholtz let us know if this issue is solved with the new release for you!
