### ISSUE TITLE
Thought: Renaming networkInterface

### ISSUE THREAD

**Issue by Schniz** [apollostack/apollo-client#750]
Hey there!
Really love the work on this project 😄 🎉 

For a project I'm working on, I wrote my own `networkInterface` - because I am getting the data from the indexedDB (local web storage).

I had a little thought: `createNetworkInterface` is a solid name, but it is a special case: local database is not a `networkInterface` since it is not using the network at all. therefore, IMHO, when creating a new ApolloClient, we should use an `interface`, and `networkInterface` is just one interface you support OOTB.

What are you guys saying? 😄

**Comment by stubailo** [comment]
I guess it could be called `GraphQLInterface` or something. Does it matter that much what it's called though?

**Comment by Schniz** [comment]
idk, naming things is fairly important to me ¯\_(ツ)_/¯

**Comment by viridia** [comment]
How about createTransport?

**Comment by DxCx** [comment]
I would use createTransport and transportInterface

**Comment by Schniz** [comment]
transport sounds good to me 👍

**Comment by helfer** [comment]
I think `createNetworkInterface` is okay as a name. The vast majority of users will request something over the network. Even when that's not the case, I think it's pretty clear what it does so I'd rather keep it like this.
