### ISSUE TITLE
Server rehydration cause first client query fail

### ISSUE THREAD

**Issue by fikriauliya** [apollostack/apollo-client#759]
My app has main Redux store which Apollo attached to, with store rehydration and server side rendering.

When the page is first loaded (*Server side rendering*), `apollo/queries/0` has the following initial value (which seems valid):

<img width="756" alt="screen shot 2016-10-11 at 4 58 50 pm" src="https://cloud.githubusercontent.com/assets/341555/19266551/3ccb1834-8fd4-11e6-9257-c75db956f5cd.png">

The query is as follow (`$page` = 1):
```
apollo.query({
  variables: translatedQueries,
  query: gql`
    query Search($page:Int) {
      search(page: $page)
      {
        products {
          id
          name
        }
      }
    }
` })
.then(response => {console.log(response.data.search); response.data.search}
```
**Problem**

When the same query is run again on **client** but with different $page variable (i.e. move to 2nd page), `apollo.query` returns prematurely after `APOLLO_QUERY_INIT` **but before** `APOLLO_QUERY_STOP` and `APOLLO_QUERY_RESULT`. And the result printed from `console.log` above is wrong: the **same** as the one on the first page.

Moreover I think it's weird that`APOLLO_QUERY_INIT` modify `apollo/queries/0/variables/page` from `1` to `2` (shouldn't it just append new queries: `apollo/queries/1` instead of updating the existing one?).
<img width="1275" alt="screen shot 2016-10-11 at 5 10 29 pm" src="https://cloud.githubusercontent.com/assets/341555/19266830/a550ba02-8fd5-11e6-9ac1-1d7a9e7864bc.png">

**More insight**

Without refreshing the page, the same query is run again with even different $page variable (i.e. move to 3rd page). Now it prints correct result. Subsequent query also works correctly

**Comment by stubailo** [comment]
Thanks for reporting. The solution is to only include the `data` field on the Apollo store when doing hydration. We should make that happen automatically when using `react-apollo`, and document it better.

Can you try the fix of deleting every field except `data` on the server before hydrating?

**Comment by fikriauliya** [comment]
Thank you for the suggestion. That's exactly what I did yesterday, patchy solution though but it solves the problem.
The drawback of that approach: refetch happen when navigating back to the first page (which had been fetched by server pre-rendering).

I don't really understand the whole code, but I guess the solution is to change the following in `QueryManager.ts`? => `private idCounter = <id from store>`

===

For those experiencing the same problem, my solution is:

```
  delete state.apollo
  return `
    <script>
      window.__INITIAL_STATE__ = ${serialize(state)};
    </script>
  `;
```
