### ISSUE TITLE
missing notification about changes in refetch

### ISSUE THREAD

**Issue by seeden** [apollostack/apollo-client#765]
Hi 

I reported isssue (https://github.com/apollostack/react-apollo/issues/269) in react-apollo but I think that the problem is somewhere here:
https://github.com/apollostack/apollo-client/blob/master/src/core/ObservableQuery.ts#L125

I am not able to find any line where you are going to inform subscribed functions about changes. Am I missing something?

It is not working with apollo-client@0.4.19 and 0.4.20 too

**Comment by stubailo** [comment]
You should be seeing an `APOLLO_QUERY_RESULT` action be dispatched: https://github.com/apollostack/apollo-client/blob/37b3513ae72b5dc94322bafbf8255225ca293e4f/src/core/QueryManager.ts#L826

In your dev tools, do you see it?

**Comment by seeden** [comment]
Hi @stubailo .Yes I can see APOLLO_QUERY_RESULT. If I want to be correct I can see 5 same APOLLO_QUERY_RESULT with same query (the reason is another reported bug here https://github.com/apollostack/react-apollo/issues/252).

I am trying to debug it by myself but I am little bit lost in the apollo-client in this moment.

**Comment by seeden** [comment]
I am not sure but maybe this issue is caused by same queries somehow.
When I call refetchQueries I can see on the line 
https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L911

refetchedQueries is equals ["2", "1", "0", "1", "0", "8"]

first strange thing is that there are same values.
the second thing is that each query (0,1,2,8) is same with same response from the server as well (the response is correct)

**Comment by seeden** [comment]
@stubailo I have new information about this issue. I can see that apollo-client has a correct data from graphql response. React component is correctly subscribed. React component is in the state **loading === true** and has a correct new data(this is caused by another component with same query). But it will never go to state loading === false; I am not sure why but it is somehow connected with https://github.com/apollostack/apollo-client/blob/master/src/core/QueryManager.ts#L346

**Comment by seeden** [comment]
The problematic line in react-apollo is https://github.com/apollostack/react-apollo/blob/master/src/graphql.tsx#L382

As you can see loading will be changed to value "true". But this function is called from componentWillReceiveProps and no componentDidMount. Anyway after that loading value will be equals true forever.

**Comment by seeden** [comment]
I have tried current version of apollo-client from trunk and the problem is still there.

**Comment by seeden** [comment]
I am trying to simulate this issue with test case but without any luck
Here is my current test case

```js
  it('test case is failing', (done) => {
    const query = gql`
      query getViewer {
        viewer {
          id
        }
      }
    `;

    const dataFirst = {
      viewer: null,
    };

    const dataSecond = {
      viewer: {
        __typename: 'User',
        id: 123
      },
    };

    const mutation = gql`
      mutation nothing {
        nothing {
          status
        }
      }
    `;

    const networkInterface = mockNetworkInterface(
      {
        request: { query, variables: {} },
        result: { data: dataFirst },
        newData: () => ({ data: dataSecond })
      },
      {
        request: { query: mutation },
        result: { data: { nothing: { status: true } } } }
    );
    const client = new ApolloClient({
      networkInterface,
      dataIdFromObject: o => {
        if (!o.__typename) {
          throw new Error('Typename is not defined');
        }

        return `${o.__typename}:${o.id}`;
      },
    });

    @graphql(query, {
      props: ({ data: { loading, viewer, error } }) => ({ loading, viewer, error }),
    })
    class JustConsumerOfQuery extends React.Component<any, any> {
      render() {
        return (
          <div>Consumer</div>
        );
      }
    };

    @graphql(query, {
      props: ({ data: { loading, viewer, error } }) => ({ loading, viewer, error }),
    })
    class ViewerProvider extends React.Component<any, any> {
      render() {
        const { loading, viewer, children } = this.props;
        if (loading) {
          return (
            <span>
              Loading
              <JustConsumerOfQuery />
              <JustConsumerOfQuery />
            </span>
          );
        }

        if (viewer) {
          done();
        }

        return children;
      }
    };

    @graphql(mutation, {
      options: {
        refetchQueries: ['getViewer'],
      }
    })
    class Header extends React.Component<any, any> {
      componentDidMount() {
        setTimeout(() => {
          this.props.mutate()
            .then(result => {
              console.log(result);
            });
        }, 200);
      }
      render() {
        return <JustConsumerOfQuery />;
      }
    };

    renderer.create((
      <ProviderMock client={client}>
        <ViewerProvider>
          <Header />
        </ViewerProvider>
      </ProviderMock>));
  }, 20000);
```

**Comment by seeden** [comment]
I looks fine in the 0.4.21

**Comment by seeden** [comment]
I am closing this issue because it looks fine in the 0.5.0-1 too

**Comment by stubailo** [comment]
Awesome, thanks!
