### ISSUE TITLE
Add generic type to ApolloQueryResult

### ISSUE THREAD

**Issue by kamilkisiela** [apollostack/apollo-client#777]
Idea:

``` ts
ApolloQueryResult<T>
```

``` ts
client.watchQuery<T>(opts).subscribe(result => {
 // result.data: T;
 // result.loading: boolean;
});
```

---

Besides that, imagine GraphQL Documents compiled into TypeScript interfaces combined with this `ApolloQueryResult` that has generic type. We can easily find bugs while writing an app.

**Comment by stubailo** [comment]
This looks great, I'd accept a PR for it.

**Comment by dcworldwide** [comment]
Typed results would be very nice. I'm also looking for a way to mixin state and behaviour to results, this is a start though.

**Comment by kamilkisiela** [comment]
Don't have time to do this but if someone wants to implement this, I could help :)
