### ISSUE TITLE
Query returning incorrect data

### ISSUE THREAD

**Issue by viridia** [apollostack/apollo-client#789]
I've got a query that looks like this:

```
query IssueQuery($project: ID!) {
  issues(project: $project) {
    id
    custom {
      name
      value
    }
  }
}

```

When I execute this query in GraphiQL, I get results that look like this:

```
{
  "data": {
    "issues": [
      {
        "id": "6",
        "custom": [
          {
            "name": "priority",
            "value": "P2"
          },
          {
            "name": "severity",
            "value": "S2"
          }
        ]
      },
// etc...

```
However, when I execute the same query in Apollo, the props.data looks like this instead:
```
[
  {
    "id": "6",
    "custom": [
      {
        "name": "severity",
        "value": "S2"
      },
      {
        "name": "severity",
        "value": "S2"
      }
    ]
  },

```

Notice how the contents of the 'custom' field aren't the same - instead of seeing two separate objects I'm seeing the same object twice.

**Comment by stubailo** [comment]
Are you supplying a `dataIdFromObject` option to `ApolloClient`? What does it look like?

**Comment by viridia** [comment]
I copied the line from the example in the docs:

  dataIdFromObject: o => `${o.__typename}:${o.id},`,

Note that 'custom' fields are not database records and don't have ids. It's just an array of key/value pairs.

**Comment by viridia** [comment]
OK changing to this makes it work:

  dataIdFromObject: o => o.id && `${o.__typename}:${o.id},`,

Might want to update the example in the doc.

**Comment by stubailo** [comment]
ohhhhhh - that explains why we have been seeing a lot of these types of bugs. Here's what we have in the example app: https://github.com/apollostack/GitHunt-React/blob/380bedaef97f2a0932c1ab33bd964812d4a8a65e/ui/client.js#L43-L48

```js
  dataIdFromObject: (result) => {
    if (result.id && result.__typename) {
      return result.__typename + result.id;
    }
    return null;
  },
```

**Comment by stubailo** [comment]
Good call, just updated the documentation.
