### ISSUE TITLE
Feature request: assistance in not rendering wrapped component till data.loading is true

### ISSUE THREAD

**Issue by GreenAsJade** [apollostack/apollo-client#793]
When I make a component like this:

`export default graphql(keyValueQuery)(CreateProjectFormLayout)`

I have to put this into the `render()` of `CreateProjectFormLayout`, in order to avoid issues with the requested data elements not being present yet:

```
render() {
    return(this.props.data.loading? null : {/* the rest of the form */} )
}
```

It would be good if the graphql() provided this assistance itself as part of the job it does in wrapping.

(Note: this ticket emerged out of slack, here:  https://apollostack.slack.com/archives/react-apollo/p1476619845000682)

**Comment by NeoPhi** [comment]
How are you handling any errors that the query might generate?

**Comment by GreenAsJade** [comment]
Well, that's an embarrasing question :)   

The answer, of course, right now is that I am ignoring them.    I'm not sure what else I could do anyhow, other than say "oops something went wrong"?

**Comment by jbaxleyiii** [comment]
@GreenAsJade I'm going to move this to react-apollo 👍
