### ISSUE TITLE
Support named fragments

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#80]
Some questions:

1. Do we inline the fragments, or try to keep the original names?
2. What do we do about variables?
3. Do the fragments return their own data, or does the UI component get it passed in from the parent?

More to think about later. The main question is, how critical is named fragment support for the alpha launch? It's one of the flagship features of the Relay API.

**Comment by stubailo** [comment]
This issue is about using fragments for improved query readability. For including fragments from other places, refer to #148. This feature could be implemented first.

**Comment by stubailo** [comment]
After talking to @helfer, my strategy is going to be to inline all of the fragments before doing anything else, and fall onto the inline fragment feature.

**Comment by helfer** [comment]
#251 will solve this completely, afaict.
