### ISSUE TITLE
Implement error handling in subscribeToMore

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#803]

**Comment by DxCx** [comment]
hi @stubailo i'm thinking about taking this one,
but i need elaboration.
the idea is to convert return value into observable (that supports errors) ?
this way it will be aligned with fetchMore but will return Observable instead of promise.

if that's not the case, please elaborate :)

**Comment by helfer** [comment]
@DxCx a simple alternative for now could be to accept a callback, which would be called with errors and results. That would be easier, because I don't think we want anyone to actually subscribe to the results of that observable (those go to updateQuery).

**Comment by DxCx** [comment]
When using fetchMore, do you expect the user to use the result received?

**Comment by helfer** [comment]
I don't think they really need it, but they might need to know _when_ the result arrived. I think the main reason we let people use the result is because there might be some use-case that we don't yet know of. It's the same for subscriptions, but since it's an unlikely use-case we shouldn't worry too much about the developer ergonomics for now. Does that make sense?

**Comment by DxCx** [comment]
yes.

then IMO, both fetchMore and subscribeToMore should return type of void.
which means:
1. fetchMore => Promise<void>
2. subscribeToMore => Observable<void>

this way, the user can register callbacks for ready notification, and catch errors as well

**Comment by stubailo** [comment]
I think for subscribeToMore it should be possible to get a notification for every new result.

Any reason we would return a `void` if we could pass through the result?

**Comment by DxCx** [comment]
if i got helfer right, he doesnt want the user to get the results directly..
anyway, after speaking with him we decided to postpone this decision to after the summit..

**Comment by helfer** [comment]
Implemented a simple version in #886
