### ISSUE TITLE
createNetworkInterface does not work as documented in 0.5.0

### ISSUE THREAD

**Issue by eagsalazar** [apollostack/apollo-client#806]
In generated js on npm, transport/networkinterface.js has this code:

```
function createNetworkInterface(interfaceOpts) {
    var _a = interfaceOpts || {}, _b = _a.opts, opts = _b === void 0 ? {} : _b, uri = _a.uri;
    return new HTTPFetchNetworkInterface(uri, opts);
}
```

Documentation says we can pass interface opts like this:

```js
const networkInterface = createNetworkInterface(
  `${Config.REINDEX_URL}/graphql`
)
```

Which does not work as uri is not set.  This results in this error:
```ExceptionsManager.js:62 A remote enpdoint is required for a network layer```

  Doing this instead does work:
```js
const networkInterface = createNetworkInterface({
  uri: `${Config.REINDEX_URL}/graphql`
})
```

**Comment by helfer** [comment]
@eagsalazar Are you intentionally running the prerelease or did you just run `npm install` and got 0.5.0-1? If you did it intentionally, thanks a lot for helping us iron out the kinks! Would you mind making a PR to update the docs? 🙂

**Comment by eagsalazar** [comment]
Huh, I just did npm install, I think...  Anyway, sure.

**Comment by helfer** [comment]
actually, nvm, it seems someone already made a PR: https://github.com/apollostack/react-docs/pull/78

**Comment by helfer** [comment]
@eagsalazar oh, ok. It seems I didn't properly do the prerelease on npm (even though I tried very hard). For the time being, can you install 0.4.21, which should be the latest recommended version.
