### ISSUE TITLE
"Uncaught TypeError: Cannot set property 'middleware' of undefined" while following instructions for React

### ISSUE THREAD

**Issue by BobWhitelock** [apollostack/apollo-client#808]
Hi - while following the instructions [here](http://dev.apollodata.com/react/initialization.html) I get `Uncaught TypeError: Cannot set property 'middleware' of undefined` when trying to create an `ApolloClient`. Here's the relevant code:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import ApolloClient, {createNetworkInterface} from 'apollo-client';
import { ApolloProvider } from 'react-apollo';
import App from './App';
import './index.css';

const client = ApolloClient({
  networkInterface: createNetworkInterface('https://api.github.com/graphql')
});

ReactDOM.render(
  <ApolloProvider client={client}>
    <App />
  </ApolloProvider>,
  document.getElementById('root')
);
```

I also saw [this](https://github.com/apollostack/apollo-client/issues/806) issue, which suggests I might need to do this instead:
```js
const client = ApolloClient({
  networkInterface: createNetworkInterface({uri: 'https://api.github.com/graphql'})
});
```
This gives exactly the same error however.

Using `apollo-client@0.4.21` with `react-apollo@0.5.11`. Any idea what I might be doing wrong?

Also here's a [repo](https://github.com/BobWhitelock/similar-repos/tree/apollo-client-issue) with the issue, if that helps. Thanks!

**Comment by pfulop** [comment]
It should be new ApolloClient

**Comment by BobWhitelock** [comment]
Doh! Yep that works, thanks!

**Comment by stubailo** [comment]
Someone could send a pr to throw an error when the constructor is called without new!

**Comment by julian-rare** [comment]
why not make it return the new class?
