### ISSUE TITLE
Changelog alert about createNetworkInterface change

### ISSUE THREAD

**Issue by drFabio** [apollostack/apollo-client#812]
Currently createNetworkInterface is like [this](https://github.com/apollostack/apollo-client/blob/5dd8eeae5c359dc807657e4b03c087914e2aa39f/src/transport/networkInterface.ts#L220)
It expects an object.

On [0.4.2.1](https://github.com/apollostack/apollo-client/blob/v0.4.21/src/networkInterface.ts#L265) for example it accepted a string.

I would consider that a breaking change worth of a changeLog entry

**Comment by helfer** [comment]
@drFabio good point, I think that was an omission. Can you make a PR?

**Comment by stubailo** [comment]
https://github.com/apollostack/apollo-client/pull/798

**Comment by drFabio** [comment]
Well it appears @stubailo  is on it already @helfer  closing the issue as it's already addressed on #798
