### ISSUE TITLE
Doc error in fragments section of vanilla chapter

### ISSUE THREAD

**Issue by viridia** [apollostack/apollo-client#816]
In the code example it shows a single fragment being passed:

`  fragments: bookInfoFragment,
`

But I believe it should be a list:

`  fragments: [bookInfoFragment],
`

**Comment by stubailo** [comment]
Have you tried the code? It actually works both ways.

**Comment by viridia** [comment]
Hmmm, OK, I thought it didn't work but it turned out to be a different problem.
