### ISSUE TITLE
Make breaking API changes to align with docs

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#82]
When I was writing the docs, I decided to write them for the API I want, not the one I have :P

So we should make some changes to the library itself to bring it up to date:

- [x] Make ApolloClient a default export of the package
- [x] Make the arguments to ApolloClient an object instead of positional
- [x] Make sure `ApolloClient#query` doesn't take a `returnPartialResults` option
- [ ] Add a few more functions to WatchedQueryHandle

@jbaxleyiii @johnthepink heads up, these are definitely breaking changes. Let me know if you disagree with any of them. You can see the docs for examples of how it would look: https://apollostack.gitbooks.io/apollo-client/content/

**Comment by johnthepink** [comment]
@stubailo cool I'll be thinking about it, but on first glance looks good to me!

**Comment by jbaxleyiii** [comment]
@stubailo I'm always a fan of documentation driven development :+1: 

Those look good to me, espeically tmaking the client the default export. I'd also personally prefer if the default for `forceFetch` was `false`. It seems like defaulting to cached data is the more often desired action, rather than forcing entirely new data. I can see how `returnPartialData`'s default makes a lot of sense though due to the UI concerns.

**Comment by stubailo** [comment]
@jbaxleyiii yeah, I think you're right. My only concern is that to make forceFetch false the default, we need a lot more testing about how it interacts with different servers that may or may not support certain features.

**Comment by stubailo** [comment]
Perhaps by default, we should just assume the server doesn't support the Relay Node spec, and just check if we have all of the query results on the client. Then we can set forceFetch to false, and it will help a lot for stuff like navigating to a route you just visited.

**Comment by jbaxleyiii** [comment]
> Perhaps by default, we should just assume the server doesn't support the Relay Node spec, and just check if we have all of the query results on the client.

@stubailo I think this sounds great
