### ISSUE TITLE
Error fetching schema from an apollo server

### ISSUE THREAD

**Issue by gouroujo** [apollostack/apollo-client#822]
Hi there,

I would like to thank you for your great work, it's a pleasure to use apollo stack to build my next generation API!

However, I've spotted a bug in the Apollo Client leading to a "Must provide schema" (400) error on the first call. The same request work on Graphiql.
Here is my logs:
- In Apollo Client:
```
Request URL:http://localhost:3030/graphql
Request Method:OPTIONS
Status Code:204 No Content

Request URL:http://localhost:3030/graphql
Request Method:POST
Status Code:400 Bad Request
Request Payload: {OperationName:"", query:"{organisations { id}}"}
```
- In graphiql:
```
Request URL:http://localhost:3030/graphql?
Request Method:POST  (Introspection query)
Status Code:200 OK

Request URL:http://localhost:3030/graphql?
Request Method:POST
Status Code:200 OK
Request Payload: {query: "{organisations { id}}", variables: "{}", operationName: null}
```

I can solve my issue by commenting `formatParams` in my router configuration:
```
router.post('/graphql',
  apolloKoa( (ctx) => {
    const token = ctx.header.authorization
    return {
      schema,
      context: { token },
      formatResponse,
      // formatParams,
    };
  })
);
```
which is a function returning a promise:
```
const formatParams = (query) => {
  const token = (query.context && query.context.token) || (query.variables && query.variables.token);
  if (token) {
    return db.models.User.findByToken(token)
    .then((user) => {
      if (user) {
        query.context = { user };
      }
      return query;
    });
  }
  return query;
}
```

As you can see, I've tuned the initial purpose of this to implement an auth systeme both available in graphiql and in an graphql client. Maybe It's not the good way and you have other solutions?

I'm asking my question here because I thinks it's more related how the apollo client fetch the schema during loading.

I'm looking forward to read your answers.

Thanks !

**Comment by helfer** [comment]
@gouroujo I'm not sure what you are referring to, because Apollo Client does not need the GraphQL schema to work. Maybe this is a problem with the server?

**Comment by gouroujo** [comment]
Hi @helfer you're right I think it was a problem with my server.
To follow up and for anyone who find this issue later, i've solve my issue by getting the user before passing the object to the apollo server middleware:
```javascript
router.post('/graphql',
  apolloKoa(async (ctx) => {
    const token = ctx.header.authorization;
    let user = {};
    if (token) {
      user = await db.models.User.findByToken(token);
    }
    return {
      schema,
      context: { user },
      formatResponse,
    };
  })
);
```
