### ISSUE TITLE
Error: returnPartialData option only supported on watchQuery.

### ISSUE THREAD

**Issue by bgentry** [apollostack/apollo-client#826]
Hi there,

I was playing around with this client and encountered an error when trying to use the `returnPartialData` option on a regular `query()`:

```
Error: returnPartialData option only supported on watchQuery.
```

Looks like this is [explicitly disallowed](https://github.com/apollostack/apollo-client/blob/afcc478b1ccd4142e6d0ffb78d924fe76bc47877/src/core/QueryManager.ts#L412), though the docs list is as an option for `query()`.

Given the description of the option, it does make sense that this wouldn't work on a single query. Thought it might be worth opening an issue in case you want to tweak the docs to remove the option from `query()`.

Cheers :v::beers:

**Comment by stubailo** [comment]
Good call, thanks for the feedback! The docs are indeed incorrect, since I think this doesn't make sense as an option.
