### ISSUE TITLE
Properly catch errors in tests

### ISSUE THREAD

**Issue by helfer** [apollostack/apollo-client#830]
Right now a bunch of tests in QueryManager cause mocha to stop running when they fail. Instead of getting useful errors with line numbers, we just see the tests stopping at the last successful test, and an error with a not-so-useful stack trace in the console.

**Comment by stubailo** [comment]
Some of these I added intentionally because the alternative was the tests passing with just an error log to the console. But I'll admit it's not ideal.

**Comment by helfer** [comment]
I agree that this is better than passing and printing errors to the console, but we should refactor to make sure the exceptions aren't uncaught.

**Comment by helfer** [comment]
I no longer think it makes sense to do this in a big refactor. We should pay attention to this when we write future tests, and update old tests when we touch them.
