### ISSUE TITLE
Internal Error: may not update existing query string in store | bug - AC@0.5

### ISSUE THREAD

**Issue by seeden** [apollostack/apollo-client#845]
Hi I have tried to use latest 0.5 version but I can see error in the console for simple query like:
```
query getViewer {
  viewer {
    id
    locale
    __typename
  }
}
```

Error in the console:

```
Internal Error: may not update existing query string in store
```

I am using SSR maybe it is connected somehow with this issue. The second thing is that I am using same query in the multiple components in this moment.

Here is the stacktrace
![stacktrace](https://s18.postimg.org/efea5ztzd/Screen_Shot_2016_10_26_at_16_02_55.png)

**Comment by seeden** [comment]
It is working correctly when I don't use initial state from server. The conflict is with query from server side rendering.

**Comment by helfer** [comment]
@seeden When dehydrating the state from the server, are you making sure that it only contains the `data` field? If so, can you paste the relevant lines here so I can see how you initialize apollo client and the store? Thanks!

**Comment by seeden** [comment]
Hi @helfer 

My state looks:

```js
{
	"request": {
		"acceptLanguage": "sk,en-US;q=0.8,en;q=0.6,cs;q=0.4"
	},
	"routing": {
		"locationBeforeTransitions": null
	},
	"apollo": {
		"queries": {
			"2": {
				"queryString": "query getViewer {\n  viewer {\n    id\n    locale\n    __typename\n  }\n}\n",
				"previousVariables": null,
				"stopped": true,
				"loading": false,
				"networkError": null,
				"graphQLErrors": null,
				"networkStatus": 7,
				"forceFetch": false,
				"returnPartialData": false,
				"lastRequestId": 3
			},
			"6": {
				"queryString": "query getViewer {\n  viewer {\n    id\n    firstName\n    ...userPhotoThumb\n    ...userStatistics\n    __typename\n  }\n}\n\nfragment userPhotoThumb on User {\n  picture\n  slug\n  __typename\n}\n\nfragment userStatistics on User {\n  followersCount\n  quizzesCount\n  pointsCount\n  __typename\n}\n",
				"previousVariables": null,
				"stopped": false,
				"loading": false,
				"networkError": null,
				"graphQLErrors": null,
				"networkStatus": 7,
				"forceFetch": false,
				"returnPartialData": false,
				"lastRequestId": 7
			}
		},
		"mutations": {},
		"data": {
			"User:1": {
				"id": "1",
				"locale": "en_US",
				"__typename": "User",
				"firstName": "Zlatko",
				"slug": "zlatko-fedor",
				"followersCount": 0,
				"quizzesCount": 0,
				"pointsCount": 0
			},
			"ROOT_QUERY": {
				"viewer": {
					"type": "id",
					"id": "User:1",
					"generated": false
				}
			}
		},
		"optimistic": []
	}
}
```

Here is how I am creating store
```js
  const middlewares = [
    apolloClient.middleware(),
    promise,
    reduxRouterMiddleware,
  ];

const store = createStore(reducer, initialState, compose(
    applyMiddleware(...middlewares),
    devToolsExt || (f => f),
));
```

After render I am storing whole state from redux because I have in redux store another data like request information.

```js
const state = store.getState();

and in the HTML render
const initialState = `window.__INITIAL_STATE__ = ${JSON.stringify(state)};`;
...
```

**Comment by helfer** [comment]
Ok, can you try getting rid of the queries part of the state? I think that will fix your problem.

**Comment by seeden** [comment]
It is working fine without queries in the store

**Comment by vlasenko** [comment]
I have faced this too with 0.5.0.

Doing
`delete window.__APOLLO_STATE__.apollo.queries`
resolves the problem.

But why are these apollo.queries in the initial state produced on server-side if they should be removed later on client-side?

**Comment by Roy9102** [comment]
@helfer ,how to get rid of the queries part of the state

**Comment by helfer** [comment]
@Roy9102 just remove that property from the resulting initial state. The only thing you need to keep is `data` and anything below it.
