### ISSUE TITLE
call refetchQueries without mutation

### ISSUE THREAD

**Issue by seeden** [apollostack/apollo-client#850]
Is it possible to call refetchQueries without mutation? 
Here is my scenario:
Logged user is trying to logout. That means I will just delete bearer token locally. But I need to refetch viewer from server after this operation.

something like:

``` js
@graphql(gql'', { refetchQueries: ['viewer'] })
```

I tried but without any success

``` js
this.context.client.mutate({ refetchQueries: ['viewer'] });
```

This ticket is related to react-apollo ticket https://github.com/apollostack/react-apollo/issues/241

**Comment by helfer** [comment]
I would either call refetch on the individual queries, or use `resetStore`, which refetches all active queries. I think in your case `resetStore` is the right approach anyway, because you want to make sure there's no other data in the store that should no longer be there after logging out.

**Comment by seeden** [comment]
@helfer I see. I will use resetStore for login/logout but I think that sometimes you want to call refetchQueries without mutation as well

**Comment by helfer** [comment]
@seeden Yeah, sure! When you have a specific use-case for it, I will be happy to accept a PR 🙂

**Comment by TSMMark** [comment]
Would very much like this feature.

**Comment by Bobryk** [comment]
@helfer @TSMMark @seeden  Currently, I am doing `apolloclient.queryManager.refetchQueryByName('queryName')`

**Comment by helfer** [comment]
Why not just call `refetch` on that query? Or run the same query again with `forceFetch` set to `true`?

I've slowly changed my opinion over time and now think it's not a good pattern to have to refer to queries by name. I think it would be better to pass around query documents and refer to them as variables.

**Comment by TSMMark** [comment]
@helfer if we're using react-apollo, how would we access, from outside of its component, a query by reference rather than by name?

**Comment by calebmer** [comment]
@TSMMark by moving the query to a variable:

```js
const myQuery = gql`...`;

graphql(myQuery)(...)
```

We could also add a static method to the container component. Something like `getGraphQLDocument`.

**Comment by ralexrdz** [comment]
how do get the queryManager,refetchQueryByName object? I've tried this:
``` js
import withApollo from 'react-apollo'
// ...
console.log(this.props.client) // ApolloClient {...}
console.log (this.props.client.queryManager) // undefined
// ...
export default withApollo(myComponent)
```
but withou success
