### ISSUE TITLE
Proposal: co-locate queries with fragments

### ISSUE THREAD

**Issue by svrcekmichal** [apollostack/apollo-client#853]
From my point of way, query without fragments are not complete and it would be better if we colocate query with fragments it need, like with fragments. I suggest to create new function `createQuery` which will accept Document and FragmentDefinition.

**Comment by stubailo** [comment]
Neat idea! I think it would be great if you could pass queries and fragments around as one object rather than passing in options to `watchQuery`, `mutate`, etc.

Mind adding a code snippet of what it could look like?

**Comment by stubailo** [comment]
It would be awesome if this allowed us to remove the `fragments` option from the API entirely, since that should really be part of the query.

**Comment by helfer** [comment]
This will be implemented in graphql-tag and can be tracked there.

**Comment by stubailo** [comment]
It's done! https://github.com/apollostack/graphql-tag/pull/17

**Comment by stubailo** [comment]
Still working on docs, here's a PR to GitHunt: https://github.com/apollostack/GitHunt-React/pull/147
