### ISSUE TITLE
addId for queryTransformer | feature

### ISSUE THREAD

**Issue by seeden** [apollostack/apollo-client#855]
It would be nice to have something like addTypename (queryTransformer) but for object ids.
All my models has attribute id but sometimes I will forget to add id property into the query and then apollo-client is not working properly because it has data like User:undefined. I think that it will help some developers too.

**Comment by seeden** [comment]
Currently I am using addTypename and it is great.

**Comment by helfer** [comment]
I think that's a great proposal and we'll make Apollo Client add that to queries automatically as soon as the `__id` proposal is implemented in most GraphQL servers. Right now it would cause queries to fail if you add `id` to a type that doesn't have that field (presumably your query type doesn't have an id, or does it?).

**Comment by seeden** [comment]
I did not know about __id proposal. I added id field to all my queries because I was able to **completely remove refetchQueries after my mutations**. For models I am using ID from database but for other responses I am using "virtual id" Very often it is combination of the query arguments. 

```js
  query getLike($userId: ID!, $modelId: ID!, $modelName: String!) {
    like(userId: $userId, modelId: $modelId, modelName: $modelName) {
      id,
      type,
      isLiked,
    }
  }
```

id will be computed as ${userId}-${modelId}-${modelName}

**Comment by helfer** [comment]
We're considering adding a default `dataIdFromObject` function, and we might expose an option to add the necessary fields for that (id and __typename), but for generic modifications I think it makes more sense to do those outside of apollo-client. Maybe graphql-tag could provide such functionality. In Apollo Client core we prefer not to modify the query that's passed in (even though we currently do).
