### ISSUE TITLE
Source map console error in production builds

### ISSUE THREAD

**Issue by viridia** [apollostack/apollo-client#858]
A really minor thing, but I thought I'd mention it: when I run my app in production, I get the following error message on the console:

`failed to parse sourcemap shallowequal.js.map`

It appears to be benign, I'm not seeing any problems because of it. In fact, I wasn't even sure if it was related to apollo at all, except that when I Google for the term 'shallowequal.js.map' it shows the apollo travis build logs.

**Comment by helfer** [comment]
@viridia thanks! Since it's not serious I won't look into it, but if someone figured out how to fix it, I wouldn't mind :wink:

**Comment by oricordeau** [comment]
Hi,

I've googled 'shallowequal.js.map' like you said, and the travis build log I get (just looked the first one) is not from this repo but from [apollostack/react-apollo](https://github.com/apollostack/react-apollo).

1. There is no shallowequal in node_modules in a clone of this repo (I used `find node_modules|grep shallow` to search) and did `npm install` before. And `grep -rniI shallowequal *` prints nothing.
2. I can find a node_modules/shallowequal folder in a clone of apollostack/react-apollo after installing the npm dependencies.

My 2 cents.

I'll try to have a look at the issue itself (I mean why shallowequal.js.map can't be parsed and where the error comes from).

**Comment by oricordeau** [comment]
More info :
In the react-apollo repository, there is an indirect dependency on the `shallowequal` npm package. There is also a source file named `src/shallowEqual.ts` (notice the uppercase 'E'). I tried building and I get a `lib/src/shallowEqual.js.map` file (which can be parsed using a simple test script - I checked just in case). But anyway there is no uppercase 'E' in the error you mentioned.

I'm not sure so far, but I think this is related to your app and the way it is built. Or related to some other tool that your app uses.

**Comment by viridia** [comment]
Apologies, the error message does have an uppercase 'E'. The exact message in the chrome dev console is:

```
DevTools failed to parse SourceMap:
https://klendathu.herokuapp.com/builds/shallowEqual.js.map
```

I'm using webpack 2 if that's of any relevance. If you are super-ambitious, you can look at my package.json here: https://github.com/viridia/klendathu/blob/master/package.json which will tell you exactly what my build environment looks like.

**Comment by oricordeau** [comment]
I tried to wget https://klendathu.herokuapp.com/builds/shallowEqual.js.map and the downloaded file contains :
```html
<html>
<head>
  <title>Klendathu</title>
  <link rel="icon" type="image/png" href="/favicon/klendathu.png"/>
</head>
<body>
  <div id="react-root"></div>
  <script type="text/javascript" src="/builds/main.bundle.js"></script>
</body>
</html>
```

So yes, it seems it has to do with your app and the issue can be closed.

Regards

**Comment by viridia** [comment]
Ah, it must be the history api fallback in express. Thanks for digging in to that, and apologies for wasting your time...

**Comment by helfer** [comment]
Thanks @oricordeau!
