### ISSUE TITLE
Error when calling resetStore()

### ISSUE THREAD

**Issue by viridia** [apollostack/apollo-client#859]
Not sure how to debug this - this happens in the middle of a call to resetStore() (I'm trying to log the user out).

```
Error: Can't find field profile on object (ROOT_QUERY) undefined.
Perhaps you want to use the `returnPartialData` option?
    at readStoreResolver (http://localhost:8080/builds/main.bundle.js:28727:19)
    at executeField (http://localhost:8080/builds/main.bundle.js:91754:18)
    at http://localhost:8080/builds/main.bundle.js:91717:31
    at Array.forEach (native)
    at executeSelectionSet (http://localhost:8080/builds/main.bundle.js:91712:29)
    at Object.graphql [as default] (http://localhost:8080/builds/main.bundle.js:91705:12)
    at diffQueryAgainstStore (http://localhost:8080/builds/main.bundle.js:28748:44)
    at Object.readQueryFromStore (http://localhost:8080/builds/main.bundle.js:28690:18)
    at http://localhost:8080/builds/main.bundle.js:34225:51
    at http://localhost:8080/builds/main.bundle.js:34663:25
```

The 'profile' field is the user record of the current logged-in user, and should be null in this case since this happens right after I've posted a /logout XHR. The field definition in the schema is nullable, so that should not be a problem.

The actual code that's throwing the error is here:

```
var readStoreResolver = function (fieldName, objId, args, context) {
    var obj = context.store[objId];
    var storeKeyName = storeUtils_2.storeKeyNameFromFieldNameAndArgs(fieldName, args);
    var fieldValue = (obj || {})[storeKeyName];
    if (typeof fieldValue === 'undefined') {
        if (!context.returnPartialData) {
            throw new Error("Can't find field " + storeKeyName + " on object (" + objId + ") " + JSON.stringify(obj, null, 2) + ".\nPerhaps you want to use the `returnPartialData` option?");
        }
```

BTW I should mention that all things considered, Apollo is working extremely well for me. :)

**Comment by wis-ekubesh** [comment]
Hi, I've the same problem on both of usage versions apollo-client(0.4.20 && 0.5.0) and angular2-apollo (0.4.6 && 0.6.0)

**Comment by helfer** [comment]
@viridia Thanks for reporting this. resetStore is a bit tricky, and this looks like a bug. I will try to document a logout flow with resetStore tomorrow, and with a bit of luck I'll be able to reproduce your issue.

**Comment by jonathanheilmann** [comment]
I'm running into this error, too.

The [Angular2 documentation](http://dev.apollodata.com/angular2/auth.html) says:
> The easiest way to ensure that the UI and store state reflects the current user’s permissions is to call ApolloClient.resetStore() after the login or logout actions have completed. This will cause the store to be cleared and all queries to be refetched. Another option is to reload the page, which will have a similar effect.

But even reloading the page by location.reload() or location.reload(true), doesn't reset the store.

**Comment by helfer** [comment]
@jonathanheilmann I'd be very surprised if refreshing the page didn't clear the store, since it basically re-initializes everything. Are you sure about that?
