### ISSUE TITLE
es6-shim conflict (can't make update apollo-client)

### ISSUE THREAD

**Issue by wis-ekubesh** [apollostack/apollo-client#861]
Hi everyone. After latest update of apollo-client was added 
/// <reference types="es6-shim" /> and we are got a problems when we want make a compile with "target": "es6"....

Could you please fix this bug or suggest any way for solving my problem?

**Comment by metzc** [comment]
@wis-ekubesh as a temporary fix you can remove those references in the apollo-client code (together with adding the es2015 lib in your tsconfig which i assume you have)

**Comment by wis-ekubesh** [comment]
@metzc yep, I can, but I think that this problem must be solved in feature in package

**Comment by paralin** [comment]
Same thing happening here. Broke my project :(. I am using core-js typings, not es6-shim. This shouldn't remain in the compiled package.

**Comment by helfer** [comment]
It seems to me that typescript builds are very brittle. There are often many ways of including typings, but each of them fails in different scenarios.

The main reason we included the es6-shim was that we couldn't get typedoc to work with the previous approach. If someone could get typedoc to work with the typings we had before, I would merge that right away (it would probably involve adding support for all tsc arguments to typedoc).

**Comment by paralin** [comment]
I'm actually having the exact same problem with my project. My tests won't compile without es6-shim.

Maybe I will add a build step to delete the `/// <reference` line.

**Comment by kamilkisiela** [comment]
Should be fixed by #865
