### ISSUE TITLE
Cryptic message given when passing array of fragments

### ISSUE THREAD

**Issue by viridia** [apollostack/apollo-client#863]
I'm executing a mutation like so:

```
export function updateProject(id, project) {
  return client.mutate({
    mutation: UpdateProjectMutation,
    variables: { id, project },
    fragments: [ProjectContent],
  });
}
```

The error I get is:

`getFromAST.js:26 Uncaught Error: Schema type definitions not allowed in queries. Found: "undefined"`

However, when I change the 'fragments' parameter from [ProjectContent] to ProjectContent, it works.

**Comment by stubailo** [comment]
Are you using the newest version of Apollo Client?

**Comment by viridia** [comment]
0.5.0

**Comment by viridia** [comment]
Exception is thrown here:

```
function checkDocument(doc) {
    if (doc.kind !== 'Document') {
        throw new Error("Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a \"gql\" tag? http://docs.apollostack.com/apollo-client/core.html#gql");
    }
    var definitionTypes = doc.definitions.map(function (definition) {
        if (definition.kind !== 'OperationDefinition' && definition.kind !== 'FragmentDefinition') {
            throw new Error("Schema type definitions not allowed in queries. Found: \"" + definition.kind + "\"");
        }

```

The 'definition' variable containns an Array[1] and thus has no 'kind' property.

**Comment by helfer** [comment]
@viridia This looks like a bug and may be relatively easy to fix. Do you want to give it a try? If so, I can give you some pointers.

**Comment by viridia** [comment]
Sure.

**Comment by helfer** [comment]
Ok, great! Best start would be to open a PR with a failing test case, and then we can take it from there!

**Comment by helfer** [comment]
@viridia Can you write me on the apollo slack? I'd like to get a PR to fix this created and merged soon!

**Comment by viridia** [comment]
Started looking at the code, still reading through it - I noticed that all of the tests involving fragments are testing queries and not mutations.

**Comment by viridia** [comment]
OK so I attempted to write a test but I'm a bit confused - it won't allow me to pass an array of fragments in typescript because the type of the field is wrong. I get this error:

Argument of type '{ query: any; fragments: FragmentDefinition[][]; }' is not assignable to parameter of type 'DeprecatedWatchQueryOptions'.at line 1368 col 27

This would seem to imply that 'createFragment' is returning an array, which is not what I would have expected - I assumed that I would be able to take several fragments created via createFragment and pass an array of them into the 'fragment:' parameter. It sounds like what I need to do is concatenate the array instead, or use new Fragment instead of createFragment. I only started using createFragment because the documentation for 'fragment:' in the vanilla docs specifically mentions it.

**Comment by viridia** [comment]
So the bottom line is:

1) I think I'm using createFragment wrong.
2) If the name were changed to 'createFragments' it would be less likely for people to make this mistake.
3) It's not possible to write a unit test for this case in TypeScript because it would violate the static type guarantees.
4) It would also help to validate the inputs to client.mutate and show a more helpful error message.

**Comment by viridia** [comment]
It occurs to me that one things that would be useful is another set of unit tests that were written in JavaScript rather than TypeScript. This would allow you to test for erroneous inputs that are not possible in TypeScript.

In other words - a lot of people who use this library are going to be writing in JS, not TS. And the library should be doing run-time type checks to guard against the most common typing errors. But the TS compiler won't allow you to write those tests, since the test would violate static type safety.

**Comment by stubailo** [comment]
@viridia you can certainly write those tests in TS by casting to `any`, like `createFragment({ wrong: "object" } as any)` etc.

**Comment by helfer** [comment]
This way of defining fragments is no longer supported, so I'm closing this issue.
