### ISSUE TITLE
Observable.result() unsubscribes from all?

### ISSUE THREAD

**Issue by leebenson** [apollostack/apollo-client#864]
I'm trying to integrate Apollo with my current Mobx stores. I have this function inside my store:

```js
getSession = () => {
  if (this.getSessionWatched) {
    return this.getSessionWatched.refetch();
  }

  this.getSessionWatched = this.client.watchQuery({ ...sessionQuery });
  this.getSessionWatched.subscribe({
    next: res => {
      console.log('logged! ->', res);
      this.data.set('session.id', (res.data.session && res.data.session.id) || null);
    },
  });

  return this.getSessionWatched.result();
}
```

The purpose of this syntax is:

- Set up a watch query that'll re-run when queries are re-fetched
- Put the result data into a local Mobx store
- Return the result back to the caller, so a call to `getSession` returns a Promise that resolves to the data on the first query request.

**Version**

apollo-client 0.5.0

**Expected**

`Observable.result()` to return the initial result, with the original subscription persisting on future requests.

**Actual**

When I fire `getSession()`, I get `'logged!'` back in the console for the _first_ request... but not on any future mutations that use `refetchQueries`.

If I remove the `this.getSessionWatched.result()` line, it works fine.

Expanding `Observable.result`, the function becomes...

```js
getSession = () => {
  if (this.getSessionWatched) {
    return this.getSessionWatched.refetch();
  }

  this.getSessionWatched = this.client.watchQuery({ ...sessionQuery });
  this.getSessionWatched.subscribe({
    next: res => {
      console.log('logged! ->', res);
      this.data.set('session.id', (res.data.session && res.data.session.id) || null);
    },
  });

  return new Promise((resolve, reject) => {
    const subscription = this.getSessionWatched.subscribe({
      next(result) {
        console.log('logged from inside result!', result);
        resolve(result);
        setTimeout(() => {
          subscription.unsubscribe();
        }, 0);
      },
      error(error) {
        reject(error);
      },
    });
  });
}
```

... which also doesn't work.

However - when I comment out `subscription.unsubscribe();`, I get the expected output back from the console:

> logged! ...
> logged from inside result! ...

It appears that unsubscribing from the second subscription cancels out _both_.

Is this the intended behaviour?

**Comment by leebenson** [comment]
Btw, I can easily solve this with:

```js
  getSession = () => {
    if (this.getSessionWatched) {
      return this.getSessionWatched.refetch();
    }

    this.getSessionWatched = this.client.watchQuery({ ...sessionQuery });

    return new Promise(resolve => {
      this.getSessionWatched.subscribe({
        next: res => {
          resolve(res);
          this.data.set('session.id', (res.data.session && res.data.session.id) || null);
        },
      });
    });
  }
```

My question relates specifically to the `unsubscribe()` behaviour -- whether triggering it should remove _all_ subscriptions, or just the current handler.

**Comment by helfer** [comment]
@leebenson Thanks! Which version of Apollo Client are you using? I believe we fixed that exact issue with multiple subscriptions in 0.5. Please let me know if that's not the case.

**Comment by leebenson** [comment]
@helfer - I'm actually using 0.5. When I posted this originally, I was on the 0.4 branch, and I saw the changelog referencing the fix, so I quickly upgraded. Currently getting the same error, though.

**Comment by tmeasday** [comment]
@helfer do we have a test for this now? I added one at some point in a branch, but I don't see it..

**Comment by leebenson** [comment]
My bad. It turns out I _was_ using Apollo 0.4x.

I encountered an [edge case](https://github.com/sass/node-sass/issues/1781) in Yarn (which, due to my build process, was suppressing output, I was never alerted to) that failed to install `node-sass` and therefore never made it to the upgrade stage of apollo-client to the 0.5 branch.

Bumping to 0.5 fixes it. Thanks guys.
