### ISSUE TITLE
Document multiple fragments in mutations

### ISSUE THREAD

**Issue by leebenson** [apollostack/apollo-client#867]
Assuming a mutation like this...

```graphql
mutation login($email: String, $password: String) {
  login(email: $email, password: $password) {
    ...Errors
    ...Session
  }
}
```

With these fragments:

```graphql
fragment Errors on Errors {
  errors {
    field
    message
  }
}

fragment Session on Session {
  id
  User {
    id
    firstName
    lastName
  }
}

```

... it's not clear from the documentation how to apply multiple fragments in a single mutation request using a combination of `{mutation, fragments}` on `.mutate()` and `createFragment()`.

I tried the following combinations:

**1. Multiple `createFragment` requests**

```js
{
  mutation: loginMutationGQL,
  fragments: [
    createFragment(errorsFragmentGQL),
    createFragment(sessionFragmentGQL),
  ],
};
```

Error:
> Uncaught (in promise) Error: Schema type definitions not allowed in queries. Found: "undefined"

**2. Combining multiple fragments into a single `createFragment`**

```js
{
  mutation: loginMutationGQL,
  fragments: createFragment(errorsFragmentGQL, sessionFragmentGQL),
};
```

Error:
> "GraphQL error: Unknown fragment "Session"

(because it's treating the errors fragment as the Document, I presume, on which `Session` doesn't exist)

**3. Passing in the login mutation as the `Document` to `createFragment`**

```js
{
  mutation: loginMutationGQL,
  fragments: createFragment(loginMutationGQL, [errorsFragmentGQL, sessionFragmentGQL]),
};
```

Error:
> Schema type definitions not allowed in queries. Found: "Document"

----

I'm sure I'm goofing up somewhere, but there's no [usage in the docs](http://dev.apollodata.com/core/fragments.html) for referencing multiple 'root' fragments (only 'fragments in fragments')

**Comment by leebenson** [comment]
dupe of #863

**Comment by leebenson** [comment]
Actually I'll re-open this, because once the bug in #863 is fixed, it'd still be good to show a sample use case of passing in multiple fragments to a query/mutation. It wasn't clear to me which of the above three syntax choices was correct without sifting through the source code.

**Comment by joint-song** [comment]
So how can i use multiple fragment definitions in one query or mutate? I tried passing previous used fragment as the second parameter of createFragment method as below, it works. But as you said, docs are not clear.
```
const first = createFragment(gql`
    fragment person on Person {
         name
    }
`);

const second = createFragment(gql`
    fragment on Company {
        people {
            ...person
        }
    }
`, first);

apollo.query({
    fragments: second
});
```

**Comment by helfer** [comment]
@joint-song `createFragment` is now deprecated and should no longer be used. For the new way of using fragments, please check here: http://dev.apollodata.com/react/fragments.html

@leebenson do you think the new documentation (and new way of handling fragments) is clear enough?

**Comment by leebenson** [comment]
@helfer - this looks a lot more comprehensive than when I last reviewed it in November.

Good work 👍
