### ISSUE TITLE
Support for operationName when submitting queries

### ISSUE THREAD

**Issue by yurigenin** [apollostack/apollo-client#872]
The reference GraphQL implementation supports providing an operationName when the query doc contains multiple named queries (mutations). It would be nice if apollo client supported this idea so that I can have multiple named queries (mutations) in the doc and I could specify a current operationName through options object. So, currently you can specify variables for a query. In the same spirit, you could have operationName as an additional option. I see it very beneficial if I have a view (React) that can support two slightly different queries and I would like to select a query (operation) based on properties passed to a view.

**Comment by stubailo** [comment]
What's the benefit of this versus providing them as two separate query documents?

**Comment by yurigenin** [comment]
First, it would allow me to have just one HOC wrapping my view. Second, I could decide which operation to run based on the property passed to the view from the parent. 
Let's say I have a view called Customers that implements displaying a list of customers but could display it two ways: paged and non-paged. I would pass a prop called viewType to it. Based on that prop the view would render a slightly different UI and would submit a different query too. It would be wrapped in a single doc with two named queries and a view could specify which operation to run based on the passed prop viewType.

So, yes, you could do it the current way by creating two HOC elements with two different queries. I just think we could take advantage of the support of the operationName and optimize components if needed.

**Comment by helfer** [comment]
Personally, I don't think that's a good idea. It's better to keep the components and their data requirements simple. If you decide the data requirements based on the props passed in, it becomes more difficult to see what data that component actually uses.

That said, if you have a concrete convincing example that might help change my mind.

**Comment by stubailo** [comment]
Yeah, I think having two HOCs right now is the right way. That makes things much clearer, rather than having complex logic which might do one query or another.

**Comment by helfer** [comment]
It's been a while, so I'll close this.

**Comment by simonhaenisch** [comment]
I have a case in Angular with a query `const queryUser = gql`` `

```graphql
fragment userFields on User {
  id
  firstName
  lastName
}

query User {
  user {
    ...userFields
  }
}

query UserById($id: Int) {
  user(id: $id) {
    ...userFields
  }
}
```

Where I would want to do this in my provider:

```ts
queryUser(id?: Number) {
  return this.apollo.watchQuery<{ user: User }>({
    query: queryUser,
    operationName: id ? 'UserById' : 'User',
    variables: id ? { id } : null,
  });
}
```

That would query the logged in user if no `id` is passed or a user by id if it is passed.

I read that queries should be static, so what would be better: this or doing template string interpolation to include the same fragment in two separate queries?
