### ISSUE TITLE
Option to stringify variables

### ISSUE THREAD

**Issue by jpshelley** [apollostack/apollo-client#881]
Currently our backend graphql server only accepts a variable object which has been stringified:
```
"variables":"{\"after\": \"MyVariable\"}"
```
But Apollo React does the following:
```
"variables":{"after":"MyVariable"}
```

Does it make sense for Apollo to support this and if so where would the option be? I can submit a PR but curious if it makes sense for it to live in the `NetworkLayer` or the `graphql` object in `react-apollo`

**Comment by stubailo** [comment]
I think it would be best to update your server to accept variables in the other way. Several resources agree that this is the correct way to send variables:

- graphql.org: http://graphql.org/learn/serving-over-http/
- GraphiQL: https://github.com/graphql/graphiql/pull/168
- Apollo Client network interface

I would suggest that if you need this functionality you can implement it as a network interface middleware, which can modify the request in any way you like before sending it along: http://dev.apollodata.com/core/network.html#networkInterfaceMiddleware

Simply write a middleware that pulls out the `variables` from the request body and changes them to a string.

**Comment by jpshelley** [comment]
@stubailo currently using a middleware to do this actually. I noticed my GraphiQL app actually is still using a stringed version of variables (not sure if I need to update it)

Our backend server is also in the process of updating GraphQL and it will soon support non-stringifies variables, however I wanted to bring up the issue in case others ran into the same thing and if it should be supported.

If this is something that Apollo doesn't want to support thats fine the ticket can be closed.

For those that are curious as to how the middleware could work.
```
applyMiddleware(req, next) {
   req.request.variables = JSON.stringify(req.request.variables);
   next();
}
```

**Comment by stubailo** [comment]
Sounds great, I'm glad there is a simple workaround! I hope that works well for you, please let me know if problems arise.

**Comment by linonetwo** [comment]
@jpshelley Strangely, 

```javascript
      req.request = { ...req.request, variables: JSON.stringify(req.request.variables) };

      console.log({ ...req.request, variables: JSON.stringify(req.request.variables) });
      console.log(req.request);
```

gives

```txt
{ query:
   { kind: 'Document',
     definitions: [ [Object] ],
     loc: { start: 0, end: 251, source: [Object] } },
  variables: '"{\\"input\\":{\\"title\\":\\"testseed1\\",\\"type\\":\\"Explore\\",\\"url\\":\\"http://fakeurl.com\\",\\"clientMutationId\\":\\"qwerasdf\\"}}"',
  operationName: 'createSeed' }


{ query:
   { kind: 'Document',
     definitions: [ [Object] ],
     loc: { start: 0, end: 251, source: [Object] } },
  variables: '{"input":{"title":"testseed1","type":"Explore","url":"http://fakeurl.com","clientMutationId":"qwerasdf"}}',
  operationName: 'createSeed' }
```

Why I can't do an assignment?
