### ISSUE TITLE
With transportBatching enabled useAfter does not get raw response

### ISSUE THREAD

**Issue by svrcekmichal** [apollostack/apollo-client#889]
With transportBatching if request is returned with status like `401` afterwares does not receive response but only response body

After little bit of digging in source code I found comment `// made public for testing only` [link](https://github.com/apollostack/apollo-client/blob/master/src/transport/batchedNetworkInterface.ts#L51) Should we be afraid? What is the future of batching?

**Comment by helfer** [comment]
@svrcekmichal Are you sure this happens only when batching is turned on? If so, it shouldn't be too hard to write a PR with a failing test. Do you think you could help with that?

The batchQuery function is only called from the Network Interface [here](https://github.com/apollostack/apollo-client/blob/master/src/transport/batchedNetworkInterface.ts#L40). I just kept it public because there are a few legacy tests that use that interface, and I didn't want to rewrite those just yet.

The future of batching is transport batching.

**Comment by svrcekmichal** [comment]
Well, the issue is with this [line](https://github.com/apollostack/apollo-client/blob/master/src/transport/batchedNetworkInterface.ts#L68) because in afterwares you receive only response data, not whole response object. You can't check for response status etc.

For now I see only one solution and that is to little bit change the api of afterwares in batchedNetworkInterface and that is to call this  [line](https://github.com/apollostack/apollo-client/blob/master/src/transport/batchedNetworkInterface.ts#L78) with one more key.

I suggest to call it `result` but I don't mind if you change that. It will look like this:
```
let results = response.json();
return this.applyAfterwares({
  response, //here will be response object with status
  options: requestsAndOptions[index].options, //request options
  result: results[index] //result of single query
});
```
What do you think?

**Comment by helfer** [comment]
I think with transport batching returning HTTP error codes doesn't make that much sense, but I guess you need that when you're sitting behind a gateway? I don't think your suggestion solves this though. What you really want is the entire response object. Individual results in the array will not have any HTTP status code associated with them, only the raw response will.

I think we'll need to patch this somehow, so I'm open to a PR, but in the long term I think people should embrace GraphQL and stop returning HTTP error codes and use GraphQL-specific errors instead that provide more information. Most likely it will take time to develop standards around that.

**Comment by helfer** [comment]
@svrcekmichal if you have time to make a PR that adds the entire response object as rawResponse, I think that would be a good start. Just make sure to add a test as well!

**Comment by svrcekmichal** [comment]
I will have time probably next week so I will do that, if no one will be faster.

Offtopic: How are you doing auth over GraphQL? How are you handling unahtorized access and letting client know that?

**Comment by helfer** [comment]
@svrcekmichal do you think you'll still submit a PR for this? I'd be happy to merge it. For the other question, you should ask on stackoverflow or slack channel 🙂

**Comment by svrcekmichal** [comment]
Hi @helfer I rethinked my usega of graphql with status codes and also query batching does not work well with status code so I no longer use them and need this. The current solution is working well for me now and I would say this should be closed. If anyone else needs it I propose him to rethink that too 👍

**Comment by krzkaczor** [comment]
Hey!
I just hit the same problem. In my opinion middlewares/afterwares should have access to raw response. One of the greatest use cases for afterwares is session invalidating (even docs show this use case) but with current implementation it's impossible. Wares could just receive additional parameter which would be a raw response. What do you think?

**Comment by svrcekmichal** [comment]
@krzkaczor I solve my problem with using error code in graphql errors response, not http status code of response, because if you batch 3 queries, how will you decide which ended with 401?

**Comment by krzkaczor** [comment]
@svrcekmichal I got your point... I have a pretty weird case because server doesn't respond with valid json when authentication fails and thus `toJson` call also fails and middlewares are not called at all. But I agree that this is a problem with implementation of my server.

**Comment by majodev** [comment]
Any update on this? It would be pretty cool to get access to the raw response in afterwares of batched queries, especially for cases where the whole GraphQL endpoint is only allowed to be accessed by authorized users (thus handling logout on 401/403 responses).

**Comment by helfer** [comment]
@majodev @lewisf was working on something.

@lewisf Can you update us on the status of the PR? 🙂
