### ISSUE TITLE
Make tests play nice with addTypename

### ISSUE THREAD

**Issue by helfer** [apollostack/apollo-client#894]
Currently the mocking that we use for most tests doesn't let us test `addTypename`, because it matches queries to responses by comparing strings with ===.

**Comment by stubailo** [comment]
Right now we seem to be moving in the direction of a "standard transform", so it could be reasonable to have the network interface just apply it.

**Comment by helfer** [comment]
Yes, I think the transformation shouldn't happen where it currently does, because we don't want to return `__typename` to the user if it wasn't asked for. I'm not sure if we somehow need the information about what transform was applied in the client itself or not. If we don't, then the network interface sounds like a very reasonable place to do this.

**Comment by stubailo** [comment]
Oh, I meant just for the tests, but we could maybe do the same at runtime as well.

**Comment by helfer** [comment]
We got bigger fish to fry. If we run out of stuff to do, we can always check the closed issues for more work 😄
