### ISSUE TITLE
Move docs to guide infrastructure

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#90]
We've moving the docs and Galaxy guides to the same Hexo site as guide.meteor.com, so let's use that here too. GitBook doesn't really provide much value, and takes away a lot of control. I'll do this in collaboration with @tmeasday.

**Comment by tmeasday** [comment]
Let me know what you need from me. In the meantime you can just copy the first commit from https://github.com/meteor/galaxy-docs and tweak it.

**Comment by stubailo** [comment]
Made big progress today, still to do:

1. Set up continuous deployment
2. Customize theme to work better for Apollo stuff
3. Make sure analytics are all correct

Repo here: https://github.com/apollostack/docs
