### ISSUE TITLE
Can mockNetworkInterface be exported here?

### ISSUE THREAD

**Issue by linonetwo** [apollostack/apollo-client#905]
There is a fancy mockNetworkInterface at https://github.com/apollostack/react-apollo/blob/master/src/test-utils.tsx , can it be isolated or be exposed here?

It might be useful for client testing or playing with react's storybook.

**Comment by linonetwo** [comment]
https://github.com/apollostack/react-apollo/issues/316

**Comment by helfer** [comment]
@linonetwo I assume this is the same mockNetworkInterface as the one we have in apollo-client [here](https://github.com/apollostack/apollo-client/blob/master/test/mocks/mockNetworkInterface.ts)?

If you would find it useful, we can definitely export it. Would you mind making a PR (and later also a PR to react-apollo, to make sure that it doesn't have an extra copy of the mockNetworkInterface)?

**Comment by linonetwo** [comment]
Fine， do it after lunch

**Comment by linonetwo** [comment]
Fine， do it after lunch

**Comment by linonetwo** [comment]
Fine， do it after lunch

**Comment by linonetwo** [comment]
I just move them to /src since export something under /test is kind of weird.

https://github.com/apollostack/apollo-client/pull/917

**Comment by linonetwo** [comment]
First time to PR, please point out what I did wrong : )

**Comment by stubailo** [comment]
I don't think putting this in `src` is good - it adds more payload size to the library for no good reason.

**Comment by kamilkisiela** [comment]
Related issue #527

**Comment by linonetwo** [comment]
So, refer to previous discussions, a new testing suite package?

I'm glad to offer help, but opening new repo is not what I can do ...

**Comment by helfer** [comment]
@linonetwo yes, that's right, we want to have a separate package for this. Let's continue the discussion in #917!
