### ISSUE TITLE
Set up a CI job to measure the size of the library

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#91]
With client-side NPM, it's easy to code yourself into a huge client-side bundle. We should at least be aware of the size of our dependencies. Should be easy to set up with some kind of CI job.

**Comment by stubailo** [comment]
For example, I would like to know how much smaller it would be if we didn't depend on lodash.

**Comment by jbaxleyiii** [comment]
@stubailo okay so I really hope I'm doing something wrong but these are the stats that I ran:

```
┌──────────┬──────────┬──────────┬───────────┬─────────┐
│ File     │ Original │  Gzipped │  Minified │ Gzipped │
├──────────┼──────────┼──────────┼───────────┼─────────┤
│ index.js │  1.01 MB │ 188.3 kB │ 266.77 kB │ 72.4 kB │
├──────────┼──────────┼──────────┼───────────┼─────────┤
│          │  1.01 MB │ 188.3 kB │ 266.77 kB │ 72.4 kB │
└──────────┴──────────┴──────────┴───────────┴─────────┘
```

changing to lodash.* for the things we need does help (saves around 30kb gzipped) but GraphQL is our biggest weight

**Comment by stubailo** [comment]
Oh snap! Well it's a good thing we checked this out. I'll look into it in more detail today.

**Comment by jbaxleyiii** [comment]
getting better with direct imports of what we need:

```
┌──────────┬───────────┬──────────┬──────────┬─────────┐
│ File     │  Original │  Gzipped │ Minified │ Gzipped │
├──────────┼───────────┼──────────┼──────────┼─────────┤
│ index.js │ 301.33 kB │ 56.81 kB │ 85.38 kB │ 24.2 kB │
└──────────┴───────────┴──────────┴──────────┴─────────┘
```

but we will need to add type definitions for those files. Should be an easy thing to do though

**Comment by stubailo** [comment]
We don't have a target at the moment. How big is Riot? I'd like this library to feel lightweight, but we don't have to go overboard with code size hacks, especially this early in development.

**Comment by jbaxleyiii** [comment]
@stubailo riot is tiny (one of its major draws) it weighs in at 8.61 kb gzipped and minified

**Comment by stubailo** [comment]
Hmm. I think there are a few options to really really cut down the size:

1. Ship a "simple build" that has the same API but doesn't do any caching at all (so it's less efficient at fetching, but initial load is tiny)
2. Pre-compile queries at build time and get rid of the GraphQL parser dependencies

Probably something to consider later - is 24kB good enough for your needs right now?

**Comment by jbaxleyiii** [comment]
Yep! We are going through our entire app to cut cost where we can and 24kb is :+1: compared to some other libs. I'd be interested in 1. for the embed project I was telling you about though! May have to hack that together soon to try it out!

**Comment by stubailo** [comment]
This is done!
