### ISSUE TITLE
Can't get full markup from "renderToStringWithData"

### ISSUE THREAD

**Issue by novus57** [apollostack/apollo-client#912]
I can't get full page markup, only part without queries. Intial state come with data but markup doesn't full. Sorry for my English. Thanks a lot for help.
```
app.use((req, res) => {
  const memoryHistory = createMemoryHistory(req.url);
  const user = Object.assign({}, { current: req.user });
  if (user.current) {
    delete user.current.password;
  }

  const apolloClient = new ApolloClient({
    ssrMode: true,
    // Remember that this is the interface the SSR server will use to connect to the
    // API server, so we need to ensure it isn't firewalled, etc
    networkInterface: createNetworkInterface({
      uri: 'http://localhost:3000/graphql',
      credentials: 'same-origin',
      // transfer request headers to networkInterface so that they're
      // accessible to proxy server
      // Addresses this issue: https://github.com/matthew-andrews/isomorphic-fetch/issues/83
      headers: req.headers,
    }),
  });

  const initialState = { user };
  const store = configureStore(memoryHistory, initialState, apolloClient);
  const history = syncHistoryWithStore(memoryHistory, store);
  match(
    { history, routes: createRoutes(store), location: req.originalUrl },
    (error, redirectLocation, renderProps) => {
      if (error) {
        res.status(500).send(error.message);
      } else if (redirectLocation) {
        res.redirect(302, redirectLocation.pathname + redirectLocation.search);
      } else if (renderProps) {
        const component = (
          <ApolloProvider store={store} client={apolloClient}>
            <MuiThemeProvider muiTheme={getMuiTheme(null, { userAgent: req.headers['user-agent'] })}>
              <RouterContext {...renderProps} />
            </MuiThemeProvider>
          </ApolloProvider>
        );

        renderToStringWithData(component).then((content) => {
          res.send(renderInitialView(content.markup, content.initialState));
        }).catch(dataError => winston.error('RENDERING ERROR:', dataError));
      }
    }
  );
});
```

**Comment by helfer** [comment]
@novus57 sorry, I'd like to help but it's pretty hard without additional information. Could you provide a link to a repository with a minimal reproduction of the problem?

**Comment by acorcutt** [comment]
I had same problem, renderToStringWithData changed in react-apollo 0.6.0 update its just `content` now not `content.markup`
also you need to get the state from the client now not the callback..
const initialState = client.store.getState()[client.reduxRootKey].data;

See http://dev.apollodata.com/react/server-side-rendering.html#renderToStringWithData

**Comment by helfer** [comment]
@novus57 does @acorcutt 's solution solve your problem?

**Comment by novus57** [comment]
@helfer sorry, but I can't give more code due to license requirements. No, it doesn't.

**Comment by novus57** [comment]
@acorcutt thanks, but it doesn't help.

**Comment by helfer** [comment]
@novus57 ok, no problem, but as long as nobody else runs into the same issue and is able to somehow convince me that this is a bug in apollo-client, I can't spend time looking into it. I hope you understand.

You can also try to get help on the slack channel or on stackoverflow, maybe that will be easier.

**Comment by novus57** [comment]
The problem was solved. I set data from query in the componentWillReceiveProps but this method doesn't work on the server.

**Comment by helfer** [comment]
Ok, glad you solved it!
