### ISSUE TITLE
Uncaught TypeError: this.queryObservable._setOptionsNoResult is not a function

### ISSUE THREAD

**Issue by judikdavid** [apollostack/apollo-client#915]
I've wanted to use dataIdFromObject feature, to automatically update the cached versions of my queries, but sometimes I encouter this error:

`Uncaught TypeError: this.queryObservable._setOptionsNoResult is not a function`

The top of the stack trace:
```
GraphQL.subscribeToQuery	@	graphql.js:244
GraphQL.componentWillReceiveProps	@	graphql.js:168
updateComponent	@	ReactCompositeComponent.js:619
receiveComponent	@	ReactCompositeComponent.js:552
receiveComponent	@	ReactReconciler.js:126
updateChildren	@	ReactChildReconciler.js:110
```

I'm using 0.5.3 of apollo-client, if I downgrade to 0.4.21, I do not get this error.

I would provide more information, but I don't know what would be useful, but I'm happy to answer any question. 

Do you have any idea what should I investigate?

**Comment by helfer** [comment]
Maybe you forgot to update react-apollo when you updated apollo-client?

**Comment by judikdavid** [comment]
Yes, that did the trick. Thank you very much for the quick response.
