### ISSUE TITLE
cannot override request header with batchedNetworkInterface

### ISSUE THREAD

**Issue by cupools** [apollostack/apollo-client#920]
Hi all,
I found the follow code in [batchedNetworkInterface.ts](https://github.com/apollostack/apollo-client/blob/master/src/transport/batchedNetworkInterface.ts#L120-L127) which overrides the given `opts`, and thus I can't set my custom header. But it is possible with [networkInterface](https://github.com/apollostack/apollo-client/blob/master/src/transport/networkInterface.ts#L162-L170).

So any ideas about why `batchedNetworkInterface` overrides the given header `Accept` and `Content-Type`, or how can I deal with the question.

```ts
// networkInterface.ts
// ...
const printedRequests = requestsAndOptions.map(({ request }) => {
  return printRequest(request);
});

return fetch(this._uri, assign({}, this._opts, options, {
  body: JSON.stringify(printedRequests),
  headers: assign({}, options.headers, {
    Accept: '*/*',
    'Content-Type': 'application/json',
  }),
  method: 'POST',
}));
// ...
```

```js
// my custom header not work
const batchingNetworkInterface = createBatchingNetworkInterface({
  uri: '/graphql',
  batchInterval: 10,
  opts: {
    method: 'POST',
    headers: {
      'Accept': 'application/json, text/plain, */*',
      'Content-Type': 'x-www-form-urlencoded'
    },
    body: JSON.stringify({ foo: 1 })
  }
})
const apolloClient = new ApolloClient({
  networkInterface: batchingNetworkInterface
})
```

**Comment by helfer** [comment]
@cupools I think this was not intentional, just a mistake. It seems the order of the arguments to `assign` was swapped. Would you mind making a PR to fix it? You can just make it exactly the same as in NetworkInterface.ts. Also don't forget to make an entry in the changelog. Thanks!

**Comment by cupools** [comment]
I'm sorry that I am new to `apollo-client` and not familiar with ts. Test cases may be necessary but I can not do pretty good. So somebody else who resolves the question will be appreciated.

**Comment by helfer** [comment]
@cupools don't worry, you don't have to be an expert to give it a try! We all started at zero :wink:
For this pull request I was just thinking about changing that one line, and mentioning it in the changelog. A test would be nice, but I would say it's not required for such a minor change.

If you're interested in contributing to open-source software, this could be a good place to start contributing. It's also the fastest way to get the issue solved that you currently have 🙂

**Comment by cupools** [comment]
@helfer I will make a try. Thanks for your encouragement 🙂
