### ISSUE TITLE
Change typed-graphql to @types/graphql

### ISSUE THREAD

**Issue by intellix** [apollostack/apollo-client#927]
Created a PR against DefinitelyTyped repository to update GraphQL typings to at least 0.8.0 (now I need bed). Opening this issue to track it so we can update here when it's in: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12735

**Comment by helfer** [comment]
@DxCx can I assign this to you? You seem to be most familiar with the two typings packages.

**Comment by DxCx** [comment]
Wow pretty neat job on the DT repo.
Lets wait for it to be merged and released to npm.
After that ill make sure nothing else we are using is missing (seems not)
And then we can switch..

**Comment by intellix** [comment]
0.8.0 merged, 0.8.2 on it's way: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12767

**Comment by stubailo** [comment]
This is done now as of 0.6! wooohooooo
