### ISSUE TITLE
Is there a way to make queryVariables be available on reducer option?

### ISSUE THREAD

**Issue by drFabio** [apollostack/apollo-client#939]
Currently it seems that unlike [updateQueries](http://dev.apollodata.com/react/cache-updates.html#updateQueries), the [reducer](http://dev.apollodata.com/react/cache-updates.html#resultReducers) option can't get the query variables on the update.

Was this by design? Is there a way to achieve it or it is a constraint of some sort?

One example of why this may be needed is this:

- Suppose a query has a sort param that can have a field and a direction.
- Suppose that a mutation added a new item to that query and this query wants to be updated.
- With updateQueries there is a parameter [queryVariables](https://github.com/apollostack/react-apollo/blob/1c85c07996c529d17d6c04859717a5017aa8a246/test/react-web/client/graphql/mutations.test.tsx#L329) That allow it.
- With reducer this parameter does not seem to be reachable making it impossible to add the newly added item on the right place.

Thanks in advance

**Comment by helfer** [comment]
@drFabio I think that was just an omission. It should be pretty simple to add, and I'm happy to help  you with pointers if you would live to try making a PR 🙂

**Comment by drFabio** [comment]
If no one is already on top of that I can try to make a pr on the weekend.
The pointers would be more than welcomed

**Comment by drFabio** [comment]
So just to check if my line of reason is right.
The "plug" of the reducer that I passed to a mutation and the query is done [here ](https://github.com/apollostack/apollo-client/blob/f7c2d95c6ee7f62b2cba79da8c4fedf87d43adef/src/core/QueryManager.ts#L272), for each observed query I make the reducer and I do indeed pass the variavles [here ](https://github.com/apollostack/apollo-client/blob/f7c2d95c6ee7f62b2cba79da8c4fedf87d43adef/src/core/QueryManager.ts#L278)

And the problem actually is just that I do not make that available to the reducer [here ](https://github.com/apollostack/apollo-client/blob/f7c2d95c6ee7f62b2cba79da8c4fedf87d43adef/src/data/resultReducers.ts#L53) since I only pass the currentResult and the action.

Now if I got it right the only thing I would like to discuss is where to put it . Should we pass a third argument making someone that is experienced with the (result,action) way of redux to have a surprise. Or make a really unlikely key and put it on action? I am more of a fan of the later option

**Comment by drFabio** [comment]
Maybe tangentially related. It seems using multiple reducers on different queries may cause some bug.
I have a query that I just added the reducer on options.
Another totally unraleted query that also has a reducer suddenly have the this.props.data As undefined. Removing the reducer make it works as intended

**Comment by Siyfion** [comment]
After a bit of head-scratching, I found this issue, I'm in a similar state:

- I have a query `itemsInCategory(catId: $catId)`
- I use a reducer to watch for `insertItem` mutation results
- I need to know the category id that I am currently looking for, in order to know whether to add the item to the results set.

And I can't find a way to access the query variables!

**Comment by drFabio** [comment]
There isn't currently a way . @Siyfion on this issue https://github.com/apollostack/apollo-client/issues/903 it was made clear to me that the observeable query design would not suit my neeeds. (basically because I have multiple views of the same data on different sorts).

It's been a while and I don't quite remember why but I remember realizing based on that issue + digging on the code I would not be able to get the query parameter on the reducer. Or at least it was out of my league

**Comment by helfer** [comment]
@drFabio @Siyfion I think a PR to add `variables` [here](https://github.com/apollostack/apollo-client/blob/8eaeb8943fb0db217bb3c95f2345d34acb690737/src/data/resultReducers.ts#L53) would be all that's needed.

To prevent a breaking change, we could do this:
```
const nextResult = resultReducer(currentResult, action, variables);
```
But we should make a note to unify the API at some later point.

**Comment by Siyfion** [comment]
Well hopefully the Apollo team will get a chance to take a look at some point...

And as I write that @helfer chimes in! lol.

**Comment by Siyfion** [comment]
Thought I'd save us all some time and create a PR. Hopefully it'll get looked at and pulled soon @drFabio!

**Comment by helfer** [comment]
Should be all good now.
