### ISSUE TITLE
Authentication with header missing Bearer prefix

### ISSUE THREAD

**Issue by sedubois** [apollostack/apollo-client#957]
Moved over from https://github.com/apollostack/react-apollo/issues/320:

I copied the code snippet about authenticating with a header from this page: http://dev.apollodata.com/react/auth.html

But didn't pay close enough attention that it was missing the "Bearer" part, and the result was that authentication was simply ignored.

1. change the doc to something like this? `req.options.headers.authorization = token ? `Bearer ${token}` : null`
2. throw an error when it has a wrongly formatted auth header, instead of silently ignoring it?

Using Graphcool backend.

**Comment by tmeasday** [comment]
I guess 2. is really an issue with Graphcool? Unless you are suggesting that AC could somehow pick this up?

**Comment by tmeasday** [comment]
@helfer was it intended to include a `Bearer` part?

**Comment by helfer** [comment]
@sedubois thanks, it looks like we should have included the `Bearer` keyword. I've just fixed it now.
