### ISSUE TITLE
updateQueries on failed query does not update

### ISSUE THREAD

**Issue by cvburgess** [apollostack/apollo-client#958]
CONTEXT:

When the component is loaded, it attempts to fetch an entity (an edition) from the server. If one does not exist the server returns a GraphQL error.

Somewhat similar to the GutHunt example, I am creating a new entity (an edition) and when that mutation is complete, I update the store with the result.

RESULTS:

- If there is already an edition (the original query worked): Everything works fine and the `data` prop is updated with the new edition.

- If the original query failed: After the mutation, the data looks to be updated in the store (via redux dev tools) but the `render()` method never gets an updated `data` prop. It holds on to the original failed `data` prop.

If i do `this.props.data.refetch()` i get the proper data loaded as well, but obviously if i have the correct data already, id like to use it!

QUESTION:

Is there a way to update a failed query with `updateQueries`?

CODE:

```js
graphql(CREATE_MUTATION, {
    props: ({ mutate }) => ({
      createEdition: (publishDate) => mutate({
        variables: { publishDate },
        updateQueries: {
          currentEdition: (prev, { mutationResult }) => {
            const newEdition = mutationResult.data.createEdition;
            return update(prev, {
              edition: {
                $set: newEdition
              }
            });
          }
        }
      })
    })
  })
```

**Comment by tmeasday** [comment]
@cvburgess do you think it would be more correct to just return `null` from the original query, rather than an error? That might make doing what you want possible.

**Comment by cvburgess** [comment]
Totally, and that's what I will do.

Out of curiosity, is there a way to update a failed query or should they just be  re-executed?

**Comment by tmeasday** [comment]
I am actually not sure, but it wouldn't surprise me if it's not possible to update it; that certainly would make sense to me.

Shall we close this issue?

**Comment by cvburgess** [comment]
Will close - if you every have an answer, please tag me!

**Comment by tmeasday** [comment]
Thanks @cvburgess
