### ISSUE TITLE
Make it easier to subclass `HTTPFetchNetworkInterface` outside of AC

### ISSUE THREAD

**Issue by Poincare** [apollostack/apollo-client#959]
I'm currently working on [extractgql](https://github.com/Poincare/extractgql) which is supposed to extract queries out of a GraphQL project, apply transformations and place them inside a JSON map. This JSON map can then be used to build query whitelisting, persisted queries, etc.

In order to build persisted query support, I'm building a `NetworkInterface` for Apollo Client that sends only a query id rather than the whole query document. But, to do this, I need to be able to subclass `HTTPFetchNetworkInterface` so that I don't have to reimplement all of the middleware, afterware, etc. logic. 

As far as I can tell, this isn't possible since `HTTPFetchNetworkInterface` isn't exported by Apollo Client. Since we're likely to implement network interfaces outside of mainline Apollo Client, it probably makes sense to export this feature. Will submit a PR for this shortly - creating this issue so that we can discuss other possible solutions to this problem.

EDIT: Forgot to mention that it is currently possible to import from `apollo-client/transport/networkInterface` and get the right type definitions, although I think this was the type of thing we'd like to prevent.

**Comment by helfer** [comment]
@Poincare 👋 

Sure, that sounds good to me. Please submit the PR! Just a heads-up that @DxCx wanted to refactor the network interface to make it more generic. Not sure if he's still interested, but if he is, it's likely something that we'll do before 1.0.

**Comment by Poincare** [comment]
@helfer 👋  :)

Just submitted the PR. I wasn't sure how to test the export so no test associated with it but I think it has the intended behavior.

**Comment by helfer** [comment]
Sounds good! I'll merge it and will publish a new version shortly 🙂
