### ISSUE TITLE
ionic 2 and apollo-client issue on es5/es6 configuration in tsconfig.json

### ISSUE THREAD

**Issue by geocine** [apollostack/apollo-client#963]
I have read this on the documentation:

```
TypeScript 2.0 comes with a set of predefined type declarations.
If you're using one of them that brings ES2015 (ES6) you should disable it, because @types/es6-shim will cause an issue with multiple types definitons.

It's easy, just replace es6, es2015 or similar options from compilerOptions.lib for es5.
```
I wanted to report this to the Ionic team but this only started happening when I added he apollo-client so I will link this to them once someone starts answering.

Does anyone know why I have to do this on Ionic 2 + Angular 2 + Apollo Client on my `tsconfig.json`?
During `ionic serve`
```    "lib": [
      "dom",
      "es6"
    ]
```
But during `ionic build android` I should do this
```    "lib": [
      "dom",
      "es5"
    ]
```
Is there any work around so that I don't have to manually edit the file every time I execute the commands? If I don't change them these commands would throw error and interrupt webpack.

**Comment by tmeasday** [comment]
@Urigo / @kamilkisiela any ideas about this one?

**Comment by kamilkisiela** [comment]
@geocine @tmeasday  `apollo-client` since #865 doesn't require to change anything in your tsconfig. 

But... if you're using the release that contains that PR then it's something we need to fix :)

I wrote about it in the documentation, in ["Initialization" chapter](http://dev.apollodata.com/angular2/initialization.html#typescript)

**Comment by geocine** [comment]
@kamilkisiela 

Thank you for letting us know. I just did
`npm uninstall @types/es6-shim`

**Comment by helfer** [comment]
@geocine does that mean we can close this issue?
