### ISSUE TITLE
Using GraphQL subscriptions

### ISSUE THREAD

**Issue by anhldbk** [apollostack/apollo-client#967]
Hi guys. I want to ask a question about subscriptions.

The code at https://github.com/apollostack/GitHunt-React/blob/master/ui/routes/CommentsPage.js#L273 suggests that: there's a field named `subscribeToMore` in `props`. But I can't find it in [the documentation](http://dev.apollodata.com/react/queries.html#default-result-props)

The code below always gives me `subscribeToMore` = `undefined`

```js
import React, { Component } from 'react';
import gql from 'graphql-tag';
import {  graphql } from 'react-apollo';

class PostList extends Component {
   // blah blah blah
}

export default graphql(gql `
  query{
    posts {
      id
      title
      votes
      author {
        id
        firstName
        lastName
      }
    }
  }`,
  {
    props: ({ data: { loading, posts, subscribeToMore } }) => {
      console.log(subscribeToMore) // *** print `undefined`
      return ({
        loading, posts
      })
    }
  }
)(PostList);
```

Would you please tell me what wrong is?

**Comment by helfer** [comment]
@anhldbk I think this question might be better suited for react-apollo. The prop should be there if you have the newest versions of apollo-client and react-apollo installed. You can check by running `npm list | grep apollo`.

**Comment by batjko** [comment]
Have subscriptions been removed from the clients? I can't find any mention of it anywhere in the docs, either for apollo-client or react-apollo.

**Comment by calebmer** [comment]
@batjko read https://dev-blog.apollodata.com/graphql-subscriptions-in-apollo-client-9a2457f015fb#.7splm9100 and make sure to check out https://github.com/apollographql/GitHunt-React/tree/master which has subscriptions 😊

**Comment by batjko** [comment]
Thanks, @calebmer. I'm just a little concerned that, if a feature isn't officially documented (maybe used to be, but not currently), it's not really recommended to implement.

Perhaps they make a comeback soon.

**Comment by helfer** [comment]
@batjko We never documented it so far, because we were still working out the API. I think you'll see some documentation soon, because @Urigo just finished implementing subscriptions in Galaxy.
