### ISSUE TITLE
Error handling bug for nullable fields

### ISSUE THREAD

**Issue by yurigenin** [apollostack/apollo-client#979]
GraphQL server goes a long way to gracefully handle errors that happen in resolvers. A resolver can throw an error, return an error object, or reject a promise. If a field's type is marked as nullable it sets the field result to null and adds an error to the global error list. If a field's type is marked as non-nullable it goes up the chain of parent fields and tries to set to null first parent that is marked as nullable. This is a very powerful concept that allows clients to get as much 'good' data as possible while getting a list of errors as well.
Unfortunately, Apollo-client undoes all this good work and throws away all data if there is at list one error in the returned error list. The data is not even placed into the cache and just silently discarded.
If I have a list of 50 customers and one of their orders came back as null because order's resolver threw an error I end up with an empty screen whereas I could still show my clients all customers with all orders except one customer's order would be missing and I would show an error in the error bar so that data could be refetched if needed.
Please fix.

**Comment by helfer** [comment]
See https://github.com/apollostack/apollo-client/issues/51

You might also be interested in https://github.com/apollostack/apollo-client/blob/master/designs/errors.md

**Comment by doranen** [comment]
+1
