### ISSUE TITLE
Do not require individual lodash packages

### ISSUE THREAD

**Issue by gajus** [apollostack/apollo-client#983]
https://github.com/apollostack/apollo-client/blob/b2d9a7c8c969e3b03f47e349e8b0702547e20e48/package.json#L42-L60

This is an anti-pattern. When you include a package this way, it cannot be de-duped across different projects. It results in this mess:

<img width="1920" alt="screen shot 2016-12-02 at 13 42 28" src="https://cloud.githubusercontent.com/assets/973543/20835965/3394fdcc-b895-11e6-8fc9-af996a5c5dab.png">

These packages are deprecated and will no longer be supported as of lodash v5.

https://github.com/lodash/lodash/wiki/Roadmap

Instead, you should be depending on the main library, but importing individual packages, e.g.

```js
const find = require('lodash/find');
```

There is a Babel plugin that does this for you,

https://github.com/lodash/babel-plugin-lodash

However, seeing that you are using ts, unless there is a ts equivalent, you'd need to code all the references by hand.

If you are going to go this way, please add a suggestion for the consumers to also use https://github.com/lodash/lodash-webpack-plugin to further decrease bundle size.

**Comment by helfer** [comment]
@gajus We do want to move away from using the individual lodash pacakges, but ideally without introducing another build step.

**Comment by gajus** [comment]
We have dropped the entire Apollo stack from product more or less because of the above screenshot. A simple query mechanism with in-built state management should not weight half of the application. I'd say therefore it is an important issue (and the entire bundle size in general).

However, this was only one of the reasons. The other being poor integration with immutable.js and very hacky integration with isomorphic rendering tools.

**Comment by seeden** [comment]
I think that 

import merge from 'lodash/merge';

instead of 

import merge from 'lodash.merge';

is a good start

**Comment by helfer** [comment]
@seeden Yeah, I think that's a good star. I would definitely merge it if you made a PR. I can also do it myself, but I don't think I would get to it this week.

**Comment by seeden** [comment]
@helfer I have created PR #995

**Comment by seeden** [comment]
@helfer I created PR #997
