### ISSUE TITLE
Getting 404 with client when accessing valid graphql endpoint

### ISSUE THREAD

**Issue by MaximeHeckel** [apollostack/apollo-client#990]
I have a small golang graphql server using graphql-go (https://github.com/graphql-go/graphql) and graphql-go handlers (https://github.com/graphql-go/handler).
I'm currently able to send a query to that server and have the appropriate response back when using `curl`

For example:
`curl http://192.168.99.100:8000/graphql -H 'Content-Type: application/graphql' -d 'query Root{ CyclingDistance(date: "2016124") { value } }'`

However when using apollo client I'm getting:
`POST http://192.168.99.100:8000/graphql 404 (Not Found)`

My client is configured as such:

```
const client = new ApolloClient({
  networkInterface:
    createNetworkInterface({ uri: `http://192.168.99.100:8000/graphql` }),
});
```

and here's my class:

```
...
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';

const myQuery =
  gql`query Root{ CyclingDistance(date: "2016124") { value } }`;

@graphql(myQuery)
class Main extends Component {
  static propTypes = {
    dispatch: PropTypes.func,
    data: PropTypes.shape({
      loading: PropTypes.bool.isRequired,
      CyclingDistance: PropTypes.object,
    }).isRequired,
  }

...

})
```

Could it be due to some incompatibility between my golang graphql server and apollo client?
My guess would be my server requiring `Content-Type: application/graphql`

EDIT 1: I'm having the same issue on localhost

**Comment by MaximeHeckel** [comment]
Seems to be more server related since I get 404 with he following curl and since apollo client using json type:
`curl http://192.168.99.100:8000/graphql -X POST -H 'Content-Type: application/json' -d 'query Root{ CyclingDistance(date: "2016124") { value } }
'
404 page not found`

**Comment by rubangarmon** [comment]
Hello @MaximeHeckel  did you resolve it? I have this problem. My node server is hosting like Windows Service on port 3000 and the expose service on IIS Port 433. There is a reverse proxy, then when a request is incoming IIS reverse proxy sends to windows service. But my problem is when in the frontend (ReactJS) try to made a request to apollo service, I get this error:

```
bundle.js:37 OPTIONS https://name_app_service.com/graphql 404 (Not Found)
(index):1 Failed to load https://name_app_service.com/graphql: Response for preflight has invalid HTTP status code 404.
```

**Comment by MaximeHeckel** [comment]
Yes I did @rubangarmon. In my case it was due to my server requiring a `Content-Type: application/graphql` and Apollo making requests with `Content-Type: application/json` if I remember correctly (it was almost 1.5 year ago and the version of Apollo was almost surely not the same as the latest one)

**Comment by owencm** [comment]
Just in case anybody else had this issue - I was using a custom path "gql" but you must put a leading slash, i.e. "/gql". If you don't do this, you get 404s.
