### ISSUE TITLE
Client will not work at all with Star Wars GraphQL API

### ISSUE THREAD

**Issue by dlai286** [apollostack/apollo-client#998]
The following will result in errors stated here: https://github.com/Akryum/frontpage-vue-app/issues/3 using latest release of the apollo client.
```
import ApolloClient, { createNetworkInterface } from 'apollo-client';

// Create the apollo client
const apolloClient = new ApolloClient({
  networkInterface: createNetworkInterface({
    uri: 'http://graphql-swapi.parseapp.com/',
    transportBatching: true,
    opts: {
      mode: 'no-cors',
    },
  }),
});

import gql from 'graphql-tag';
const query = gql`
  {
    allFilms {
      films {
        title
      }
    }
  }
`
apolloClient.query({
  query,
}).then(result => {
  console.log(result)
})
```
Any clues to why this is happening?

I've tried creating my own GraphQL endpoint with a PHP library which also doesn't work. The only time I've gotten apollo client working with another GraphQL backend was https://github.com/apollostack/frontpage-server. Forgive me if I read wrong but is the client supposed to be backend agnostic or it doesn't work with non-JS stacks?

**Comment by stubailo** [comment]
People have used AC with basically every backend that exists out there. This is pretty surprising. Can you post the actual request that was sent from the Chrome network tools?

**Comment by stubailo** [comment]
Are you sure that you want `mode: 'no-cors',`? Perhaps that could be part of the issue?

**Comment by dlai286** [comment]
Thanks for taking a look @stubailo 

Originally I didn't have it in place but`mode: 'no-cors'` is necessary otherwise the server will return
```
Fetch API cannot load http://graphql-swapi.parseapp.com/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8081' is therefore not allowed access. The response had HTTP status code 405. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Here is the request sent:

<img width="1192" alt="screenshot 2016-12-06 19 37 41" src="https://cloud.githubusercontent.com/assets/17719485/20918601/059ca97e-bbec-11e6-93f7-754baf29cea0.png">

I'm unsure why the query sent has `__typename` fields injected when they weren't declared in the original query but I'm still learning GraphQL, is that normal?

**Comment by stubailo** [comment]
Apollo Client does inject `__typename` for you since it's used for resolving fragments etc. This is something many GraphQL clients do.

Anyway, I don't think you can avoid the error you listed simply by passing `no-cors`. I think the server is specifically designed not to accept requests from other clients. Since CURL is not being called from a browser, it works. I would suggest using a different API for trying apollo client, for example GitHub: https://github.com/katopz/react-apollo-graphql-github-example
