### ISSUE TITLE
Write subscription results under `ROOT_SUBSCRIPTION` ID instead of `ROOT_QUERY`

### ISSUE THREAD

**Issue by stubailo** [apollostack/apollo-client#999]
This will help show in the Apollo dev tools whether data came from a subscription or query.

**Comment by dko-slapdash** [comment]
Could you please clarify, is it true (and on intent) that ROOT_SUBSCRIPTION is never read anywhere in the code, it's only written?

The following search shows that there are no more references to ROOT_SUBSCRIPTION (including dev tools): https://github.com/search?q=org%3Aapollographql+ROOT_SUBSCRIPTION&unscoped_q=ROOT_SUBSCRIPTION

**Comment by jedwards1211** [comment]
Not only that, subscription data shouldn't overwrite cached query data automatically anyway, right?
